/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.chronicle.labs.api.resources.sdk;

import com.chronicle.labs.api.core.ClientOptions;
import com.chronicle.labs.api.core.RequestOptions;
import com.chronicle.labs.api.resources.sdk.requests.IdentifyUserRequest;
import com.chronicle.labs.api.resources.sdk.requests.TrackSignalsRequest;
import com.chronicle.labs.api.resources.sdk.requests.TrackTracesRequest;
import com.chronicle.labs.api.types.AcceptedResponse;

public class SdkClient {
    protected final ClientOptions clientOptions;

    private final RawSdkClient rawClient;

    public SdkClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawSdkClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawSdkClient withRawResponse() {
        return this.rawClient;
    }

    /**
     * Requires scope users:write.
     */
    public AcceptedResponse identifyUser(IdentifyUserRequest request) {
        return this.rawClient.identifyUser(request).body();
    }

    /**
     * Requires scope users:write.
     */
    public AcceptedResponse identifyUser(IdentifyUserRequest request, RequestOptions requestOptions) {
        return this.rawClient.identifyUser(request, requestOptions).body();
    }

    /**
     * Requires scope signals:write. Maximum 1000 signals per request; larger batches are rejected with 422. Each request consumes 10 rate-limit units.
     */
    public AcceptedResponse trackSignals() {
        return this.rawClient.trackSignals().body();
    }

    /**
     * Requires scope signals:write. Maximum 1000 signals per request; larger batches are rejected with 422. Each request consumes 10 rate-limit units.
     */
    public AcceptedResponse trackSignals(RequestOptions requestOptions) {
        return this.rawClient.trackSignals(requestOptions).body();
    }

    /**
     * Requires scope signals:write. Maximum 1000 signals per request; larger batches are rejected with 422. Each request consumes 10 rate-limit units.
     */
    public AcceptedResponse trackSignals(TrackSignalsRequest request) {
        return this.rawClient.trackSignals(request).body();
    }

    /**
     * Requires scope signals:write. Maximum 1000 signals per request; larger batches are rejected with 422. Each request consumes 10 rate-limit units.
     */
    public AcceptedResponse trackSignals(TrackSignalsRequest request, RequestOptions requestOptions) {
        return this.rawClient.trackSignals(request, requestOptions).body();
    }

    /**
     * Requires scope traces:write. Maximum 1000 traces or total spans per request; larger batches are rejected with 422. Each request consumes 10 rate-limit units.
     */
    public AcceptedResponse trackTraces() {
        return this.rawClient.trackTraces().body();
    }

    /**
     * Requires scope traces:write. Maximum 1000 traces or total spans per request; larger batches are rejected with 422. Each request consumes 10 rate-limit units.
     */
    public AcceptedResponse trackTraces(RequestOptions requestOptions) {
        return this.rawClient.trackTraces(requestOptions).body();
    }

    /**
     * Requires scope traces:write. Maximum 1000 traces or total spans per request; larger batches are rejected with 422. Each request consumes 10 rate-limit units.
     */
    public AcceptedResponse trackTraces(TrackTracesRequest request) {
        return this.rawClient.trackTraces(request).body();
    }

    /**
     * Requires scope traces:write. Maximum 1000 traces or total spans per request; larger batches are rejected with 422. Each request consumes 10 rate-limit units.
     */
    public AcceptedResponse trackTraces(TrackTracesRequest request, RequestOptions requestOptions) {
        return this.rawClient.trackTraces(request, requestOptions).body();
    }
}
