/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.chronicle.labs.api.resources.agents.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class RecordAgentRunsRequestRunsItemOperation {
  public static final RecordAgentRunsRequestRunsItemOperation GENERATE = new RecordAgentRunsRequestRunsItemOperation(Value.GENERATE, "generate");

  public static final RecordAgentRunsRequestRunsItemOperation STREAM = new RecordAgentRunsRequestRunsItemOperation(Value.STREAM, "stream");

  private final Value value;

  private final String string;

  RecordAgentRunsRequestRunsItemOperation(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof RecordAgentRunsRequestRunsItemOperation && this.string.equals(((RecordAgentRunsRequestRunsItemOperation) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case GENERATE:
        return visitor.visitGenerate();
      case STREAM:
        return visitor.visitStream();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static RecordAgentRunsRequestRunsItemOperation valueOf(String value) {
    switch (value) {
      case "generate":
        return GENERATE;
      case "stream":
        return STREAM;
      default:
        return new RecordAgentRunsRequestRunsItemOperation(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    GENERATE,

    STREAM,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitGenerate();

    T visitStream();

    T visitUnknown(String unknownType);
  }
}
