/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.chronicle.labs.api.resources.agents.types;

import com.chronicle.labs.api.core.Nullable;
import com.chronicle.labs.api.core.NullableNonemptyFilter;
import com.chronicle.labs.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = RecordAgentRunsRequestRunsItemResponse.Builder.class
)
public final class RecordAgentRunsRequestRunsItemResponse {
  private final Optional<String> bodyHash;

  private final Optional<String> finishReason;

  private final Optional<Map<String, Optional<String>>> headers;

  private final Optional<String> id;

  private final Optional<String> modelId;

  private final Optional<Map<String, Object>> modelMetadata;

  private final Optional<Map<String, Object>> providerMetadata;

  private final Optional<RecordAgentRunsRequestRunsItemResponseUsage> usage;

  private final Map<String, Object> additionalProperties;

  private RecordAgentRunsRequestRunsItemResponse(Optional<String> bodyHash,
      Optional<String> finishReason, Optional<Map<String, Optional<String>>> headers,
      Optional<String> id, Optional<String> modelId, Optional<Map<String, Object>> modelMetadata,
      Optional<Map<String, Object>> providerMetadata,
      Optional<RecordAgentRunsRequestRunsItemResponseUsage> usage,
      Map<String, Object> additionalProperties) {
    this.bodyHash = bodyHash;
    this.finishReason = finishReason;
    this.headers = headers;
    this.id = id;
    this.modelId = modelId;
    this.modelMetadata = modelMetadata;
    this.providerMetadata = providerMetadata;
    this.usage = usage;
    this.additionalProperties = additionalProperties;
  }

  @JsonIgnore
  public Optional<String> getBodyHash() {
    if (bodyHash == null) {
      return Optional.empty();
    }
    return bodyHash;
  }

  @JsonIgnore
  public Optional<String> getFinishReason() {
    if (finishReason == null) {
      return Optional.empty();
    }
    return finishReason;
  }

  /**
   * @return Subset of headers preserved for the run drawer.
   */
  @JsonIgnore
  public Optional<Map<String, Optional<String>>> getHeaders() {
    if (headers == null) {
      return Optional.empty();
    }
    return headers;
  }

  @JsonIgnore
  public Optional<String> getId() {
    if (id == null) {
      return Optional.empty();
    }
    return id;
  }

  @JsonIgnore
  public Optional<String> getModelId() {
    if (modelId == null) {
      return Optional.empty();
    }
    return modelId;
  }

  @JsonIgnore
  public Optional<Map<String, Object>> getModelMetadata() {
    if (modelMetadata == null) {
      return Optional.empty();
    }
    return modelMetadata;
  }

  @JsonIgnore
  public Optional<Map<String, Object>> getProviderMetadata() {
    if (providerMetadata == null) {
      return Optional.empty();
    }
    return providerMetadata;
  }

  @JsonIgnore
  public Optional<RecordAgentRunsRequestRunsItemResponseUsage> getUsage() {
    if (usage == null) {
      return Optional.empty();
    }
    return usage;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("bodyHash")
  private Optional<String> _getBodyHash() {
    return bodyHash;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("finishReason")
  private Optional<String> _getFinishReason() {
    return finishReason;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("headers")
  private Optional<Map<String, Optional<String>>> _getHeaders() {
    return headers;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("id")
  private Optional<String> _getId() {
    return id;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("modelId")
  private Optional<String> _getModelId() {
    return modelId;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("modelMetadata")
  private Optional<Map<String, Object>> _getModelMetadata() {
    return modelMetadata;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("providerMetadata")
  private Optional<Map<String, Object>> _getProviderMetadata() {
    return providerMetadata;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("usage")
  private Optional<RecordAgentRunsRequestRunsItemResponseUsage> _getUsage() {
    return usage;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof RecordAgentRunsRequestRunsItemResponse && equalTo((RecordAgentRunsRequestRunsItemResponse) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(RecordAgentRunsRequestRunsItemResponse other) {
    return bodyHash.equals(other.bodyHash) && finishReason.equals(other.finishReason) && headers.equals(other.headers) && id.equals(other.id) && modelId.equals(other.modelId) && modelMetadata.equals(other.modelMetadata) && providerMetadata.equals(other.providerMetadata) && usage.equals(other.usage);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.bodyHash, this.finishReason, this.headers, this.id, this.modelId, this.modelMetadata, this.providerMetadata, this.usage);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> bodyHash = Optional.empty();

    private Optional<String> finishReason = Optional.empty();

    private Optional<Map<String, Optional<String>>> headers = Optional.empty();

    private Optional<String> id = Optional.empty();

    private Optional<String> modelId = Optional.empty();

    private Optional<Map<String, Object>> modelMetadata = Optional.empty();

    private Optional<Map<String, Object>> providerMetadata = Optional.empty();

    private Optional<RecordAgentRunsRequestRunsItemResponseUsage> usage = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(RecordAgentRunsRequestRunsItemResponse other) {
      bodyHash(other.getBodyHash());
      finishReason(other.getFinishReason());
      headers(other.getHeaders());
      id(other.getId());
      modelId(other.getModelId());
      modelMetadata(other.getModelMetadata());
      providerMetadata(other.getProviderMetadata());
      usage(other.getUsage());
      return this;
    }

    @JsonSetter(
        value = "bodyHash",
        nulls = Nulls.SKIP
    )
    public Builder bodyHash(Optional<String> bodyHash) {
      this.bodyHash = bodyHash;
      return this;
    }

    public Builder bodyHash(String bodyHash) {
      this.bodyHash = Optional.ofNullable(bodyHash);
      return this;
    }

    public Builder bodyHash(Nullable<String> bodyHash) {
      if (bodyHash.isNull()) {
        this.bodyHash = null;
      }
      else if (bodyHash.isEmpty()) {
        this.bodyHash = Optional.empty();
      }
      else {
        this.bodyHash = Optional.of(bodyHash.get());
      }
      return this;
    }

    @JsonSetter(
        value = "finishReason",
        nulls = Nulls.SKIP
    )
    public Builder finishReason(Optional<String> finishReason) {
      this.finishReason = finishReason;
      return this;
    }

    public Builder finishReason(String finishReason) {
      this.finishReason = Optional.ofNullable(finishReason);
      return this;
    }

    public Builder finishReason(Nullable<String> finishReason) {
      if (finishReason.isNull()) {
        this.finishReason = null;
      }
      else if (finishReason.isEmpty()) {
        this.finishReason = Optional.empty();
      }
      else {
        this.finishReason = Optional.of(finishReason.get());
      }
      return this;
    }

    /**
     * <p>Subset of headers preserved for the run drawer.</p>
     */
    @JsonSetter(
        value = "headers",
        nulls = Nulls.SKIP
    )
    public Builder headers(Optional<Map<String, Optional<String>>> headers) {
      this.headers = headers;
      return this;
    }

    public Builder headers(Map<String, Optional<String>> headers) {
      this.headers = Optional.ofNullable(headers);
      return this;
    }

    public Builder headers(Nullable<Map<String, Optional<String>>> headers) {
      if (headers.isNull()) {
        this.headers = null;
      }
      else if (headers.isEmpty()) {
        this.headers = Optional.empty();
      }
      else {
        this.headers = Optional.of(headers.get());
      }
      return this;
    }

    @JsonSetter(
        value = "id",
        nulls = Nulls.SKIP
    )
    public Builder id(Optional<String> id) {
      this.id = id;
      return this;
    }

    public Builder id(String id) {
      this.id = Optional.ofNullable(id);
      return this;
    }

    public Builder id(Nullable<String> id) {
      if (id.isNull()) {
        this.id = null;
      }
      else if (id.isEmpty()) {
        this.id = Optional.empty();
      }
      else {
        this.id = Optional.of(id.get());
      }
      return this;
    }

    @JsonSetter(
        value = "modelId",
        nulls = Nulls.SKIP
    )
    public Builder modelId(Optional<String> modelId) {
      this.modelId = modelId;
      return this;
    }

    public Builder modelId(String modelId) {
      this.modelId = Optional.ofNullable(modelId);
      return this;
    }

    public Builder modelId(Nullable<String> modelId) {
      if (modelId.isNull()) {
        this.modelId = null;
      }
      else if (modelId.isEmpty()) {
        this.modelId = Optional.empty();
      }
      else {
        this.modelId = Optional.of(modelId.get());
      }
      return this;
    }

    @JsonSetter(
        value = "modelMetadata",
        nulls = Nulls.SKIP
    )
    public Builder modelMetadata(Optional<Map<String, Object>> modelMetadata) {
      this.modelMetadata = modelMetadata;
      return this;
    }

    public Builder modelMetadata(Map<String, Object> modelMetadata) {
      this.modelMetadata = Optional.ofNullable(modelMetadata);
      return this;
    }

    public Builder modelMetadata(Nullable<Map<String, Object>> modelMetadata) {
      if (modelMetadata.isNull()) {
        this.modelMetadata = null;
      }
      else if (modelMetadata.isEmpty()) {
        this.modelMetadata = Optional.empty();
      }
      else {
        this.modelMetadata = Optional.of(modelMetadata.get());
      }
      return this;
    }

    @JsonSetter(
        value = "providerMetadata",
        nulls = Nulls.SKIP
    )
    public Builder providerMetadata(Optional<Map<String, Object>> providerMetadata) {
      this.providerMetadata = providerMetadata;
      return this;
    }

    public Builder providerMetadata(Map<String, Object> providerMetadata) {
      this.providerMetadata = Optional.ofNullable(providerMetadata);
      return this;
    }

    public Builder providerMetadata(Nullable<Map<String, Object>> providerMetadata) {
      if (providerMetadata.isNull()) {
        this.providerMetadata = null;
      }
      else if (providerMetadata.isEmpty()) {
        this.providerMetadata = Optional.empty();
      }
      else {
        this.providerMetadata = Optional.of(providerMetadata.get());
      }
      return this;
    }

    @JsonSetter(
        value = "usage",
        nulls = Nulls.SKIP
    )
    public Builder usage(Optional<RecordAgentRunsRequestRunsItemResponseUsage> usage) {
      this.usage = usage;
      return this;
    }

    public Builder usage(RecordAgentRunsRequestRunsItemResponseUsage usage) {
      this.usage = Optional.ofNullable(usage);
      return this;
    }

    public Builder usage(Nullable<RecordAgentRunsRequestRunsItemResponseUsage> usage) {
      if (usage.isNull()) {
        this.usage = null;
      }
      else if (usage.isEmpty()) {
        this.usage = Optional.empty();
      }
      else {
        this.usage = Optional.of(usage.get());
      }
      return this;
    }

    public RecordAgentRunsRequestRunsItemResponse build() {
      return new RecordAgentRunsRequestRunsItemResponse(bodyHash, finishReason, headers, id, modelId, modelMetadata, providerMetadata, usage, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
