/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.chronicle.labs.api.resources.discover;

import com.chronicle.labs.api.core.ClientOptions;
import com.chronicle.labs.api.core.RequestOptions;
import com.chronicle.labs.api.resources.discover.requests.GetEventSchemaRequest;
import com.chronicle.labs.api.resources.discover.requests.ListEntitiesRequest;
import com.chronicle.labs.api.types.EntityListResponse;
import com.chronicle.labs.api.types.EntityTypeListResponse;
import com.chronicle.labs.api.types.SourceListResponse;
import com.chronicle.labs.api.types.SourceSchema;
import java.lang.String;

public class DiscoverClient {
  protected final ClientOptions clientOptions;

  private final RawDiscoverClient rawClient;

  public DiscoverClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new RawDiscoverClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public RawDiscoverClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Requires scope events:read or events:write. Returns the complete source metadata set without pagination.
   */
  public SourceListResponse listSources() {
    return this.rawClient.listSources().body();
  }

  /**
   * Requires scope events:read or events:write. Returns the complete source metadata set without pagination.
   */
  public SourceListResponse listSources(RequestOptions requestOptions) {
    return this.rawClient.listSources(requestOptions).body();
  }

  /**
   * Requires scope events:read or events:write. Returns the complete entity-type metadata set without pagination.
   */
  public EntityTypeListResponse listEntityTypes() {
    return this.rawClient.listEntityTypes().body();
  }

  /**
   * Requires scope events:read or events:write. Returns the complete entity-type metadata set without pagination.
   */
  public EntityTypeListResponse listEntityTypes(RequestOptions requestOptions) {
    return this.rawClient.listEntityTypes(requestOptions).body();
  }

  /**
   * Requires scope events:read or events:write. Entities are ordered by event count and entity ID. The limit is capped at 200; pass <code>next_cursor</code> as <code>cursor</code>.
   */
  public EntityListResponse listEntities(String entityType) {
    return this.rawClient.listEntities(entityType).body();
  }

  /**
   * Requires scope events:read or events:write. Entities are ordered by event count and entity ID. The limit is capped at 200; pass <code>next_cursor</code> as <code>cursor</code>.
   */
  public EntityListResponse listEntities(String entityType, RequestOptions requestOptions) {
    return this.rawClient.listEntities(entityType, requestOptions).body();
  }

  /**
   * Requires scope events:read or events:write. Entities are ordered by event count and entity ID. The limit is capped at 200; pass <code>next_cursor</code> as <code>cursor</code>.
   */
  public EntityListResponse listEntities(String entityType, ListEntitiesRequest request) {
    return this.rawClient.listEntities(entityType, request).body();
  }

  /**
   * Requires scope events:read or events:write. Entities are ordered by event count and entity ID. The limit is capped at 200; pass <code>next_cursor</code> as <code>cursor</code>.
   */
  public EntityListResponse listEntities(String entityType, ListEntitiesRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.listEntities(entityType, request, requestOptions).body();
  }

  /**
   * Requires scope events:read or events:write.
   */
  public SourceSchema getEventSchema(String source, String eventType) {
    return this.rawClient.getEventSchema(source, eventType).body();
  }

  /**
   * Requires scope events:read or events:write.
   */
  public SourceSchema getEventSchema(String source, String eventType,
      RequestOptions requestOptions) {
    return this.rawClient.getEventSchema(source, eventType, requestOptions).body();
  }

  /**
   * Requires scope events:read or events:write.
   */
  public SourceSchema getEventSchema(String source, String eventType,
      GetEventSchemaRequest request) {
    return this.rawClient.getEventSchema(source, eventType, request).body();
  }

  /**
   * Requires scope events:read or events:write.
   */
  public SourceSchema getEventSchema(String source, String eventType, GetEventSchemaRequest request,
      RequestOptions requestOptions) {
    return this.rawClient.getEventSchema(source, eventType, request, requestOptions).body();
  }
}
