/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.chronicle.labs.api.resources.agents.requests;

import com.chronicle.labs.api.core.Nullable;
import com.chronicle.labs.api.core.NullableNonemptyFilter;
import com.chronicle.labs.api.core.ObjectMappers;
import com.chronicle.labs.api.resources.agents.types.RegisterAgentArtifactRequestArtifact;
import com.chronicle.labs.api.resources.agents.types.RegisterAgentArtifactRequestMetadata;
import com.chronicle.labs.api.resources.agents.types.RegisterAgentArtifactRequestStatus;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = RegisterAgentArtifactRequest.Builder.class)
public final class RegisterAgentArtifactRequest {
    private final RegisterAgentArtifactRequestArtifact artifact;

    private final Optional<RegisterAgentArtifactRequestMetadata> metadata;

    private final Optional<RegisterAgentArtifactRequestStatus> status;

    private final Map<String, Object> additionalProperties;

    private RegisterAgentArtifactRequest(
            RegisterAgentArtifactRequestArtifact artifact,
            Optional<RegisterAgentArtifactRequestMetadata> metadata,
            Optional<RegisterAgentArtifactRequestStatus> status,
            Map<String, Object> additionalProperties) {
        this.artifact = artifact;
        this.metadata = metadata;
        this.status = status;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("artifact")
    public RegisterAgentArtifactRequestArtifact getArtifact() {
        return artifact;
    }

    /**
     * @return Mutable, human-authored metadata attached to a logical Agent identity. Artifact configuration remains immutable inside <code>AgentRegistryVersionRecord</code>.
     */
    @JsonIgnore
    public Optional<RegisterAgentArtifactRequestMetadata> getMetadata() {
        if (metadata == null) {
            return Optional.empty();
        }
        return metadata;
    }

    /**
     * @return Defaults to <code>current</code>. Registering a new current version atomically demotes the previous current version to stable.
     */
    @JsonIgnore
    public Optional<RegisterAgentArtifactRequestStatus> getStatus() {
        if (status == null) {
            return Optional.empty();
        }
        return status;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("metadata")
    private Optional<RegisterAgentArtifactRequestMetadata> _getMetadata() {
        return metadata;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("status")
    private Optional<RegisterAgentArtifactRequestStatus> _getStatus() {
        return status;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof RegisterAgentArtifactRequest && equalTo((RegisterAgentArtifactRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(RegisterAgentArtifactRequest other) {
        return artifact.equals(other.artifact) && metadata.equals(other.metadata) && status.equals(other.status);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.artifact, this.metadata, this.status);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ArtifactStage builder() {
        return new Builder();
    }

    public interface ArtifactStage {
        _FinalStage artifact(@NotNull RegisterAgentArtifactRequestArtifact artifact);

        Builder from(RegisterAgentArtifactRequest other);
    }

    public interface _FinalStage {
        RegisterAgentArtifactRequest build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Mutable, human-authored metadata attached to a logical Agent identity. Artifact configuration remains immutable inside <code>AgentRegistryVersionRecord</code>.</p>
         */
        _FinalStage metadata(Optional<RegisterAgentArtifactRequestMetadata> metadata);

        _FinalStage metadata(RegisterAgentArtifactRequestMetadata metadata);

        _FinalStage metadata(Nullable<RegisterAgentArtifactRequestMetadata> metadata);

        /**
         * <p>Defaults to <code>current</code>. Registering a new current version atomically demotes the previous current version to stable.</p>
         */
        _FinalStage status(Optional<RegisterAgentArtifactRequestStatus> status);

        _FinalStage status(RegisterAgentArtifactRequestStatus status);

        _FinalStage status(Nullable<RegisterAgentArtifactRequestStatus> status);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements ArtifactStage, _FinalStage {
        private RegisterAgentArtifactRequestArtifact artifact;

        private Optional<RegisterAgentArtifactRequestStatus> status = Optional.empty();

        private Optional<RegisterAgentArtifactRequestMetadata> metadata = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(RegisterAgentArtifactRequest other) {
            artifact(other.getArtifact());
            metadata(other.getMetadata());
            status(other.getStatus());
            return this;
        }

        @java.lang.Override
        @JsonSetter("artifact")
        public _FinalStage artifact(@NotNull RegisterAgentArtifactRequestArtifact artifact) {
            this.artifact = Objects.requireNonNull(artifact, "artifact must not be null");
            return this;
        }

        /**
         * <p>Defaults to <code>current</code>. Registering a new current version atomically demotes the previous current version to stable.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage status(Nullable<RegisterAgentArtifactRequestStatus> status) {
            if (status.isNull()) {
                this.status = null;
            } else if (status.isEmpty()) {
                this.status = Optional.empty();
            } else {
                this.status = Optional.of(status.get());
            }
            return this;
        }

        /**
         * <p>Defaults to <code>current</code>. Registering a new current version atomically demotes the previous current version to stable.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage status(RegisterAgentArtifactRequestStatus status) {
            this.status = Optional.ofNullable(status);
            return this;
        }

        /**
         * <p>Defaults to <code>current</code>. Registering a new current version atomically demotes the previous current version to stable.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "status", nulls = Nulls.SKIP)
        public _FinalStage status(Optional<RegisterAgentArtifactRequestStatus> status) {
            this.status = status;
            return this;
        }

        /**
         * <p>Mutable, human-authored metadata attached to a logical Agent identity. Artifact configuration remains immutable inside <code>AgentRegistryVersionRecord</code>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage metadata(Nullable<RegisterAgentArtifactRequestMetadata> metadata) {
            if (metadata.isNull()) {
                this.metadata = null;
            } else if (metadata.isEmpty()) {
                this.metadata = Optional.empty();
            } else {
                this.metadata = Optional.of(metadata.get());
            }
            return this;
        }

        /**
         * <p>Mutable, human-authored metadata attached to a logical Agent identity. Artifact configuration remains immutable inside <code>AgentRegistryVersionRecord</code>.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage metadata(RegisterAgentArtifactRequestMetadata metadata) {
            this.metadata = Optional.ofNullable(metadata);
            return this;
        }

        /**
         * <p>Mutable, human-authored metadata attached to a logical Agent identity. Artifact configuration remains immutable inside <code>AgentRegistryVersionRecord</code>.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "metadata", nulls = Nulls.SKIP)
        public _FinalStage metadata(Optional<RegisterAgentArtifactRequestMetadata> metadata) {
            this.metadata = metadata;
            return this;
        }

        @java.lang.Override
        public RegisterAgentArtifactRequest build() {
            return new RegisterAgentArtifactRequest(artifact, metadata, status, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
