/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.chronicle.labs.api.resources.agents.requests;

import com.chronicle.labs.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = SearchAgentHashIndexRequest.Builder.class
)
public final class SearchAgentHashIndexRequest {
  private final Optional<String> q;

  private final Optional<String> domains;

  private final Map<String, Object> additionalProperties;

  private SearchAgentHashIndexRequest(Optional<String> q, Optional<String> domains,
      Map<String, Object> additionalProperties) {
    this.q = q;
    this.domains = domains;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("q")
  public Optional<String> getQ() {
    return q;
  }

  /**
   * @return Comma-separated hash domains.
   */
  @JsonProperty("domains")
  public Optional<String> getDomains() {
    return domains;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof SearchAgentHashIndexRequest && equalTo((SearchAgentHashIndexRequest) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(SearchAgentHashIndexRequest other) {
    return q.equals(other.q) && domains.equals(other.domains);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.q, this.domains);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<String> q = Optional.empty();

    private Optional<String> domains = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(SearchAgentHashIndexRequest other) {
      q(other.getQ());
      domains(other.getDomains());
      return this;
    }

    @JsonSetter(
        value = "q",
        nulls = Nulls.SKIP
    )
    public Builder q(Optional<String> q) {
      this.q = q;
      return this;
    }

    public Builder q(String q) {
      this.q = Optional.ofNullable(q);
      return this;
    }

    /**
     * <p>Comma-separated hash domains.</p>
     */
    @JsonSetter(
        value = "domains",
        nulls = Nulls.SKIP
    )
    public Builder domains(Optional<String> domains) {
      this.domains = domains;
      return this;
    }

    public Builder domains(String domains) {
      this.domains = Optional.ofNullable(domains);
      return this;
    }

    public SearchAgentHashIndexRequest build() {
      return new SearchAgentHashIndexRequest(q, domains, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
