/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.chronicle.labs.api.resources.environments;

import com.chronicle.labs.api.core.ClientOptions;
import com.chronicle.labs.api.core.RequestOptions;
import com.chronicle.labs.api.resources.environments.requests.CompileEnvironmentRequest;
import com.chronicle.labs.api.resources.environments.requests.CreateEnvironmentRequest;
import com.chronicle.labs.api.resources.environments.requests.CreateEnvironmentVersionRequest;
import com.chronicle.labs.api.resources.environments.requests.GetEnvironmentRequest;
import com.chronicle.labs.api.resources.environments.requests.GetEnvironmentVersionRequest;
import com.chronicle.labs.api.resources.environments.requests.ListEnvironmentVersionsRequest;
import com.chronicle.labs.api.types.CompileEnvironmentResponse;
import com.chronicle.labs.api.types.EnvironmentResponse;
import com.chronicle.labs.api.types.EnvironmentVersionRecord;
import com.chronicle.labs.api.types.EnvironmentVersionResponse;
import com.chronicle.labs.api.types.ListEnvironmentsResponse;
import java.util.List;

public class EnvironmentsClient {
    protected final ClientOptions clientOptions;

    private final RawEnvironmentsClient rawClient;

    public EnvironmentsClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.rawClient = new RawEnvironmentsClient(clientOptions);
    }

    /**
     * Get responses with HTTP metadata like headers
     */
    public RawEnvironmentsClient withRawResponse() {
        return this.rawClient;
    }

    public ListEnvironmentsResponse listEnvironments() {
        return this.rawClient.listEnvironments().body();
    }

    public ListEnvironmentsResponse listEnvironments(RequestOptions requestOptions) {
        return this.rawClient.listEnvironments(requestOptions).body();
    }

    public EnvironmentResponse createEnvironment(CreateEnvironmentRequest request) {
        return this.rawClient.createEnvironment(request).body();
    }

    public EnvironmentResponse createEnvironment(CreateEnvironmentRequest request, RequestOptions requestOptions) {
        return this.rawClient.createEnvironment(request, requestOptions).body();
    }

    public EnvironmentResponse getEnvironment(String environmentId) {
        return this.rawClient.getEnvironment(environmentId).body();
    }

    public EnvironmentResponse getEnvironment(String environmentId, RequestOptions requestOptions) {
        return this.rawClient.getEnvironment(environmentId, requestOptions).body();
    }

    public EnvironmentResponse getEnvironment(String environmentId, GetEnvironmentRequest request) {
        return this.rawClient.getEnvironment(environmentId, request).body();
    }

    public EnvironmentResponse getEnvironment(
            String environmentId, GetEnvironmentRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .getEnvironment(environmentId, request, requestOptions)
                .body();
    }

    public List<EnvironmentVersionRecord> listEnvironmentVersions(String environmentId) {
        return this.rawClient.listEnvironmentVersions(environmentId).body();
    }

    public List<EnvironmentVersionRecord> listEnvironmentVersions(String environmentId, RequestOptions requestOptions) {
        return this.rawClient
                .listEnvironmentVersions(environmentId, requestOptions)
                .body();
    }

    public List<EnvironmentVersionRecord> listEnvironmentVersions(
            String environmentId, ListEnvironmentVersionsRequest request) {
        return this.rawClient.listEnvironmentVersions(environmentId, request).body();
    }

    public List<EnvironmentVersionRecord> listEnvironmentVersions(
            String environmentId, ListEnvironmentVersionsRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .listEnvironmentVersions(environmentId, request, requestOptions)
                .body();
    }

    public EnvironmentVersionResponse createEnvironmentVersion(
            String environmentId, CreateEnvironmentVersionRequest request) {
        return this.rawClient.createEnvironmentVersion(environmentId, request).body();
    }

    public EnvironmentVersionResponse createEnvironmentVersion(
            String environmentId, CreateEnvironmentVersionRequest request, RequestOptions requestOptions) {
        return this.rawClient
                .createEnvironmentVersion(environmentId, request, requestOptions)
                .body();
    }

    public EnvironmentVersionResponse getEnvironmentVersion(String environmentId, String versionSelector) {
        return this.rawClient
                .getEnvironmentVersion(environmentId, versionSelector)
                .body();
    }

    public EnvironmentVersionResponse getEnvironmentVersion(
            String environmentId, String versionSelector, RequestOptions requestOptions) {
        return this.rawClient
                .getEnvironmentVersion(environmentId, versionSelector, requestOptions)
                .body();
    }

    public EnvironmentVersionResponse getEnvironmentVersion(
            String environmentId, String versionSelector, GetEnvironmentVersionRequest request) {
        return this.rawClient
                .getEnvironmentVersion(environmentId, versionSelector, request)
                .body();
    }

    public EnvironmentVersionResponse getEnvironmentVersion(
            String environmentId,
            String versionSelector,
            GetEnvironmentVersionRequest request,
            RequestOptions requestOptions) {
        return this.rawClient
                .getEnvironmentVersion(environmentId, versionSelector, request, requestOptions)
                .body();
    }

    public CompileEnvironmentResponse compileEnvironmentVersion(
            String environmentId, String versionSelector, CompileEnvironmentRequest request) {
        return this.rawClient
                .compileEnvironmentVersion(environmentId, versionSelector, request)
                .body();
    }

    public CompileEnvironmentResponse compileEnvironmentVersion(
            String environmentId,
            String versionSelector,
            CompileEnvironmentRequest request,
            RequestOptions requestOptions) {
        return this.rawClient
                .compileEnvironmentVersion(environmentId, versionSelector, request, requestOptions)
                .body();
    }
}
