/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.chronicle.labs.api.resources.events.requests;

import com.chronicle.labs.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = QueryEventsRequest.Builder.class)
public final class QueryEventsRequest {
    private final Optional<String> source;

    private final Optional<String> topic;

    private final Optional<String> eventType;

    private final Optional<String> entityType;

    private final Optional<String> entityId;

    private final Optional<Integer> limit;

    private final Optional<String> cursor;

    private final Optional<String> since;

    private final Map<String, Object> additionalProperties;

    private QueryEventsRequest(
            Optional<String> source,
            Optional<String> topic,
            Optional<String> eventType,
            Optional<String> entityType,
            Optional<String> entityId,
            Optional<Integer> limit,
            Optional<String> cursor,
            Optional<String> since,
            Map<String, Object> additionalProperties) {
        this.source = source;
        this.topic = topic;
        this.eventType = eventType;
        this.entityType = entityType;
        this.entityId = entityId;
        this.limit = limit;
        this.cursor = cursor;
        this.since = since;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("source")
    public Optional<String> getSource() {
        return source;
    }

    @JsonProperty("topic")
    public Optional<String> getTopic() {
        return topic;
    }

    @JsonProperty("event_type")
    public Optional<String> getEventType() {
        return eventType;
    }

    @JsonProperty("entity_type")
    public Optional<String> getEntityType() {
        return entityType;
    }

    @JsonProperty("entity_id")
    public Optional<String> getEntityId() {
        return entityId;
    }

    /**
     * @return Page size. Values above 200 are clamped to 200.
     */
    @JsonProperty("limit")
    public Optional<Integer> getLimit() {
        return limit;
    }

    /**
     * @return Opaque position returned as <code>next_cursor</code> by the preceding page.
     */
    @JsonProperty("cursor")
    public Optional<String> getCursor() {
        return cursor;
    }

    /**
     * @return Relative time window, for example last_7d.
     */
    @JsonProperty("since")
    public Optional<String> getSince() {
        return since;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof QueryEventsRequest && equalTo((QueryEventsRequest) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(QueryEventsRequest other) {
        return source.equals(other.source)
                && topic.equals(other.topic)
                && eventType.equals(other.eventType)
                && entityType.equals(other.entityType)
                && entityId.equals(other.entityId)
                && limit.equals(other.limit)
                && cursor.equals(other.cursor)
                && since.equals(other.since);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.source,
                this.topic,
                this.eventType,
                this.entityType,
                this.entityId,
                this.limit,
                this.cursor,
                this.since);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<String> source = Optional.empty();

        private Optional<String> topic = Optional.empty();

        private Optional<String> eventType = Optional.empty();

        private Optional<String> entityType = Optional.empty();

        private Optional<String> entityId = Optional.empty();

        private Optional<Integer> limit = Optional.empty();

        private Optional<String> cursor = Optional.empty();

        private Optional<String> since = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(QueryEventsRequest other) {
            source(other.getSource());
            topic(other.getTopic());
            eventType(other.getEventType());
            entityType(other.getEntityType());
            entityId(other.getEntityId());
            limit(other.getLimit());
            cursor(other.getCursor());
            since(other.getSince());
            return this;
        }

        @JsonSetter(value = "source", nulls = Nulls.SKIP)
        public Builder source(Optional<String> source) {
            this.source = source;
            return this;
        }

        public Builder source(String source) {
            this.source = Optional.ofNullable(source);
            return this;
        }

        @JsonSetter(value = "topic", nulls = Nulls.SKIP)
        public Builder topic(Optional<String> topic) {
            this.topic = topic;
            return this;
        }

        public Builder topic(String topic) {
            this.topic = Optional.ofNullable(topic);
            return this;
        }

        @JsonSetter(value = "event_type", nulls = Nulls.SKIP)
        public Builder eventType(Optional<String> eventType) {
            this.eventType = eventType;
            return this;
        }

        public Builder eventType(String eventType) {
            this.eventType = Optional.ofNullable(eventType);
            return this;
        }

        @JsonSetter(value = "entity_type", nulls = Nulls.SKIP)
        public Builder entityType(Optional<String> entityType) {
            this.entityType = entityType;
            return this;
        }

        public Builder entityType(String entityType) {
            this.entityType = Optional.ofNullable(entityType);
            return this;
        }

        @JsonSetter(value = "entity_id", nulls = Nulls.SKIP)
        public Builder entityId(Optional<String> entityId) {
            this.entityId = entityId;
            return this;
        }

        public Builder entityId(String entityId) {
            this.entityId = Optional.ofNullable(entityId);
            return this;
        }

        /**
         * <p>Page size. Values above 200 are clamped to 200.</p>
         */
        @JsonSetter(value = "limit", nulls = Nulls.SKIP)
        public Builder limit(Optional<Integer> limit) {
            this.limit = limit;
            return this;
        }

        public Builder limit(Integer limit) {
            this.limit = Optional.ofNullable(limit);
            return this;
        }

        /**
         * <p>Opaque position returned as <code>next_cursor</code> by the preceding page.</p>
         */
        @JsonSetter(value = "cursor", nulls = Nulls.SKIP)
        public Builder cursor(Optional<String> cursor) {
            this.cursor = cursor;
            return this;
        }

        public Builder cursor(String cursor) {
            this.cursor = Optional.ofNullable(cursor);
            return this;
        }

        /**
         * <p>Relative time window, for example last_7d.</p>
         */
        @JsonSetter(value = "since", nulls = Nulls.SKIP)
        public Builder since(Optional<String> since) {
            this.since = since;
            return this;
        }

        public Builder since(String since) {
            this.since = Optional.ofNullable(since);
            return this;
        }

        public QueryEventsRequest build() {
            return new QueryEventsRequest(
                    source, topic, eventType, entityType, entityId, limit, cursor, since, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
