/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.chronicle.labs.api.resources.backtests.types;

import com.chronicle.labs.api.core.Nullable;
import com.chronicle.labs.api.core.NullableNonemptyFilter;
import com.chronicle.labs.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = CreateBacktestJobRequestRecipeDataSourcesItemFilters.Builder.class)
public final class CreateBacktestJobRequestRecipeDataSourcesItemFilters {
    private final Optional<List<String>> clusters;

    private final Optional<String> outcome;

    private final Optional<String> seed;

    private final Optional<String> window;

    private final Map<String, Object> additionalProperties;

    private CreateBacktestJobRequestRecipeDataSourcesItemFilters(
            Optional<List<String>> clusters,
            Optional<String> outcome,
            Optional<String> seed,
            Optional<String> window,
            Map<String, Object> additionalProperties) {
        this.clusters = clusters;
        this.outcome = outcome;
        this.seed = seed;
        this.window = window;
        this.additionalProperties = additionalProperties;
    }

    @JsonIgnore
    public Optional<List<String>> getClusters() {
        if (clusters == null) {
            return Optional.empty();
        }
        return clusters;
    }

    @JsonIgnore
    public Optional<String> getOutcome() {
        if (outcome == null) {
            return Optional.empty();
        }
        return outcome;
    }

    @JsonIgnore
    public Optional<String> getSeed() {
        if (seed == null) {
            return Optional.empty();
        }
        return seed;
    }

    @JsonIgnore
    public Optional<String> getWindow() {
        if (window == null) {
            return Optional.empty();
        }
        return window;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("clusters")
    private Optional<List<String>> _getClusters() {
        return clusters;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("outcome")
    private Optional<String> _getOutcome() {
        return outcome;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("seed")
    private Optional<String> _getSeed() {
        return seed;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("window")
    private Optional<String> _getWindow() {
        return window;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof CreateBacktestJobRequestRecipeDataSourcesItemFilters
                && equalTo((CreateBacktestJobRequestRecipeDataSourcesItemFilters) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(CreateBacktestJobRequestRecipeDataSourcesItemFilters other) {
        return clusters.equals(other.clusters)
                && outcome.equals(other.outcome)
                && seed.equals(other.seed)
                && window.equals(other.window);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.clusters, this.outcome, this.seed, this.window);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<List<String>> clusters = Optional.empty();

        private Optional<String> outcome = Optional.empty();

        private Optional<String> seed = Optional.empty();

        private Optional<String> window = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(CreateBacktestJobRequestRecipeDataSourcesItemFilters other) {
            clusters(other.getClusters());
            outcome(other.getOutcome());
            seed(other.getSeed());
            window(other.getWindow());
            return this;
        }

        @JsonSetter(value = "clusters", nulls = Nulls.SKIP)
        public Builder clusters(Optional<List<String>> clusters) {
            this.clusters = clusters;
            return this;
        }

        public Builder clusters(List<String> clusters) {
            this.clusters = Optional.ofNullable(clusters);
            return this;
        }

        public Builder clusters(Nullable<List<String>> clusters) {
            if (clusters.isNull()) {
                this.clusters = null;
            } else if (clusters.isEmpty()) {
                this.clusters = Optional.empty();
            } else {
                this.clusters = Optional.of(clusters.get());
            }
            return this;
        }

        @JsonSetter(value = "outcome", nulls = Nulls.SKIP)
        public Builder outcome(Optional<String> outcome) {
            this.outcome = outcome;
            return this;
        }

        public Builder outcome(String outcome) {
            this.outcome = Optional.ofNullable(outcome);
            return this;
        }

        public Builder outcome(Nullable<String> outcome) {
            if (outcome.isNull()) {
                this.outcome = null;
            } else if (outcome.isEmpty()) {
                this.outcome = Optional.empty();
            } else {
                this.outcome = Optional.of(outcome.get());
            }
            return this;
        }

        @JsonSetter(value = "seed", nulls = Nulls.SKIP)
        public Builder seed(Optional<String> seed) {
            this.seed = seed;
            return this;
        }

        public Builder seed(String seed) {
            this.seed = Optional.ofNullable(seed);
            return this;
        }

        public Builder seed(Nullable<String> seed) {
            if (seed.isNull()) {
                this.seed = null;
            } else if (seed.isEmpty()) {
                this.seed = Optional.empty();
            } else {
                this.seed = Optional.of(seed.get());
            }
            return this;
        }

        @JsonSetter(value = "window", nulls = Nulls.SKIP)
        public Builder window(Optional<String> window) {
            this.window = window;
            return this;
        }

        public Builder window(String window) {
            this.window = Optional.ofNullable(window);
            return this;
        }

        public Builder window(Nullable<String> window) {
            if (window.isNull()) {
                this.window = null;
            } else if (window.isEmpty()) {
                this.window = Optional.empty();
            } else {
                this.window = Optional.of(window.get());
            }
            return this;
        }

        public CreateBacktestJobRequestRecipeDataSourcesItemFilters build() {
            return new CreateBacktestJobRequestRecipeDataSourcesItemFilters(
                    clusters, outcome, seed, window, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
