/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.chronicle.labs.api.resources.backtests.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class CreateBacktestJobRequestRecipeDataScenariosItemBucket {
    public static final CreateBacktestJobRequestRecipeDataScenariosItemBucket EDGE =
            new CreateBacktestJobRequestRecipeDataScenariosItemBucket(Value.EDGE, "edge");

    public static final CreateBacktestJobRequestRecipeDataScenariosItemBucket ADJACENT =
            new CreateBacktestJobRequestRecipeDataScenariosItemBucket(Value.ADJACENT, "adjacent");

    public static final CreateBacktestJobRequestRecipeDataScenariosItemBucket EMERGING =
            new CreateBacktestJobRequestRecipeDataScenariosItemBucket(Value.EMERGING, "emerging");

    public static final CreateBacktestJobRequestRecipeDataScenariosItemBucket CAPTURED =
            new CreateBacktestJobRequestRecipeDataScenariosItemBucket(Value.CAPTURED, "captured");

    private final Value value;

    private final String string;

    CreateBacktestJobRequestRecipeDataScenariosItemBucket(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof CreateBacktestJobRequestRecipeDataScenariosItemBucket
                        && this.string.equals(((CreateBacktestJobRequestRecipeDataScenariosItemBucket) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case EDGE:
                return visitor.visitEdge();
            case ADJACENT:
                return visitor.visitAdjacent();
            case EMERGING:
                return visitor.visitEmerging();
            case CAPTURED:
                return visitor.visitCaptured();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static CreateBacktestJobRequestRecipeDataScenariosItemBucket valueOf(String value) {
        switch (value) {
            case "edge":
                return EDGE;
            case "adjacent":
                return ADJACENT;
            case "emerging":
                return EMERGING;
            case "captured":
                return CAPTURED;
            default:
                return new CreateBacktestJobRequestRecipeDataScenariosItemBucket(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        CAPTURED,

        ADJACENT,

        EMERGING,

        EDGE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitCaptured();

        T visitAdjacent();

        T visitEmerging();

        T visitEdge();

        T visitUnknown(String unknownType);
    }
}
