/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.chronicle.labs.api.resources.backtests.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class CreateBacktestJobRequestRecipeGradersItemWeight {
    public static final CreateBacktestJobRequestRecipeGradersItemWeight LOW =
            new CreateBacktestJobRequestRecipeGradersItemWeight(Value.LOW, "low");

    public static final CreateBacktestJobRequestRecipeGradersItemWeight HIGH =
            new CreateBacktestJobRequestRecipeGradersItemWeight(Value.HIGH, "high");

    public static final CreateBacktestJobRequestRecipeGradersItemWeight MED =
            new CreateBacktestJobRequestRecipeGradersItemWeight(Value.MED, "med");

    private final Value value;

    private final String string;

    CreateBacktestJobRequestRecipeGradersItemWeight(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof CreateBacktestJobRequestRecipeGradersItemWeight
                        && this.string.equals(((CreateBacktestJobRequestRecipeGradersItemWeight) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case LOW:
                return visitor.visitLow();
            case HIGH:
                return visitor.visitHigh();
            case MED:
                return visitor.visitMed();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static CreateBacktestJobRequestRecipeGradersItemWeight valueOf(String value) {
        switch (value) {
            case "low":
                return LOW;
            case "high":
                return HIGH;
            case "med":
                return MED;
            default:
                return new CreateBacktestJobRequestRecipeGradersItemWeight(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        LOW,

        MED,

        HIGH,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitLow();

        T visitMed();

        T visitHigh();

        T visitUnknown(String unknownType);
    }
}
