/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.chronicle.labs.api.resources.backtests.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class CreateBacktestJobRequestRecipeDataScenariosItemKind {
    public static final CreateBacktestJobRequestRecipeDataScenariosItemKind LONG_TURN =
            new CreateBacktestJobRequestRecipeDataScenariosItemKind(Value.LONG_TURN, "longTurn");

    public static final CreateBacktestJobRequestRecipeDataScenariosItemKind NON_ENGLISH =
            new CreateBacktestJobRequestRecipeDataScenariosItemKind(Value.NON_ENGLISH, "nonEnglish");

    public static final CreateBacktestJobRequestRecipeDataScenariosItemKind ADVERSARIAL =
            new CreateBacktestJobRequestRecipeDataScenariosItemKind(Value.ADVERSARIAL, "adversarial");

    public static final CreateBacktestJobRequestRecipeDataScenariosItemKind TOOL_FAILURE =
            new CreateBacktestJobRequestRecipeDataScenariosItemKind(Value.TOOL_FAILURE, "toolFailure");

    private final Value value;

    private final String string;

    CreateBacktestJobRequestRecipeDataScenariosItemKind(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof CreateBacktestJobRequestRecipeDataScenariosItemKind
                        && this.string.equals(((CreateBacktestJobRequestRecipeDataScenariosItemKind) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case LONG_TURN:
                return visitor.visitLongTurn();
            case NON_ENGLISH:
                return visitor.visitNonEnglish();
            case ADVERSARIAL:
                return visitor.visitAdversarial();
            case TOOL_FAILURE:
                return visitor.visitToolFailure();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static CreateBacktestJobRequestRecipeDataScenariosItemKind valueOf(String value) {
        switch (value) {
            case "longTurn":
                return LONG_TURN;
            case "nonEnglish":
                return NON_ENGLISH;
            case "adversarial":
                return ADVERSARIAL;
            case "toolFailure":
                return TOOL_FAILURE;
            default:
                return new CreateBacktestJobRequestRecipeDataScenariosItemKind(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        ADVERSARIAL,

        NON_ENGLISH,

        TOOL_FAILURE,

        LONG_TURN,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitAdversarial();

        T visitNonEnglish();

        T visitToolFailure();

        T visitLongTurn();

        T visitUnknown(String unknownType);
    }
}
