/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.chronicle.labs.api;

import com.chronicle.labs.api.core.ClientOptions;
import com.chronicle.labs.api.core.Suppliers;
import com.chronicle.labs.api.resources.discover.AsyncDiscoverClient;
import com.chronicle.labs.api.resources.events.AsyncEventsClient;
import com.chronicle.labs.api.resources.links.AsyncLinksClient;
import com.chronicle.labs.api.resources.sdk.AsyncSdkClient;
import com.chronicle.labs.api.resources.search.AsyncSearchClient;
import com.chronicle.labs.api.resources.timeline.AsyncTimelineClient;
import java.util.function.Supplier;

public class AsyncChronicleLabsApiClient {
    protected final ClientOptions clientOptions;

    protected final Supplier<AsyncEventsClient> eventsClient;

    protected final Supplier<AsyncTimelineClient> timelineClient;

    protected final Supplier<AsyncSearchClient> searchClient;

    protected final Supplier<AsyncDiscoverClient> discoverClient;

    protected final Supplier<AsyncLinksClient> linksClient;

    protected final Supplier<AsyncSdkClient> sdkClient;

    public AsyncChronicleLabsApiClient(ClientOptions clientOptions) {
        this.clientOptions = clientOptions;
        this.eventsClient = Suppliers.memoize(() -> new AsyncEventsClient(clientOptions));
        this.timelineClient = Suppliers.memoize(() -> new AsyncTimelineClient(clientOptions));
        this.searchClient = Suppliers.memoize(() -> new AsyncSearchClient(clientOptions));
        this.discoverClient = Suppliers.memoize(() -> new AsyncDiscoverClient(clientOptions));
        this.linksClient = Suppliers.memoize(() -> new AsyncLinksClient(clientOptions));
        this.sdkClient = Suppliers.memoize(() -> new AsyncSdkClient(clientOptions));
    }

    public AsyncEventsClient events() {
        return this.eventsClient.get();
    }

    public AsyncTimelineClient timeline() {
        return this.timelineClient.get();
    }

    public AsyncSearchClient search() {
        return this.searchClient.get();
    }

    public AsyncDiscoverClient discover() {
        return this.discoverClient.get();
    }

    public AsyncLinksClient links() {
        return this.linksClient.get();
    }

    public AsyncSdkClient sdk() {
        return this.sdkClient.get();
    }

    public static AsyncChronicleLabsApiClientBuilder builder() {
        return new AsyncChronicleLabsApiClientBuilder();
    }
}
