/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.chronicle.labs.api.types;

import com.chronicle.labs.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = AcceptedResponse.Builder.class)
public final class AcceptedResponse {
    private final int accepted;

    private final Map<String, Object> additionalProperties;

    private AcceptedResponse(int accepted, Map<String, Object> additionalProperties) {
        this.accepted = accepted;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("accepted")
    public int getAccepted() {
        return accepted;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof AcceptedResponse && equalTo((AcceptedResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(AcceptedResponse other) {
        return accepted == other.accepted;
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.accepted);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static AcceptedStage builder() {
        return new Builder();
    }

    public interface AcceptedStage {
        _FinalStage accepted(int accepted);

        Builder from(AcceptedResponse other);
    }

    public interface _FinalStage {
        AcceptedResponse build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements AcceptedStage, _FinalStage {
        private int accepted;

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(AcceptedResponse other) {
            accepted(other.getAccepted());
            return this;
        }

        @java.lang.Override
        @JsonSetter("accepted")
        public _FinalStage accepted(int accepted) {
            this.accepted = accepted;
            return this;
        }

        @java.lang.Override
        public AcceptedResponse build() {
            return new AcceptedResponse(accepted, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
