/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.chronicle.labs.api.types;

import com.chronicle.labs.api.core.Nullable;
import com.chronicle.labs.api.core.NullableNonemptyFilter;
import com.chronicle.labs.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = AgentChatSessionMessagesItem.Builder.class
)
public final class AgentChatSessionMessagesItem {
  private final Optional<String> error;

  private final Optional<List<String>> eventIds;

  private final String messageId;

  private final OffsetDateTime occurredAt;

  private final AgentChatSessionMessagesItemRole role;

  private final Optional<List<AgentChatSessionMessagesItemStepsItem>> steps;

  private final String text;

  private final Map<String, Object> additionalProperties;

  private AgentChatSessionMessagesItem(Optional<String> error, Optional<List<String>> eventIds,
      String messageId, OffsetDateTime occurredAt, AgentChatSessionMessagesItemRole role,
      Optional<List<AgentChatSessionMessagesItemStepsItem>> steps, String text,
      Map<String, Object> additionalProperties) {
    this.error = error;
    this.eventIds = eventIds;
    this.messageId = messageId;
    this.occurredAt = occurredAt;
    this.role = role;
    this.steps = steps;
    this.text = text;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Present when the turn failed — the transcript keeps the user message and surfaces the failure instead of fabricating a reply.
   */
  @JsonIgnore
  public Optional<String> getError() {
    if (error == null) {
      return Optional.empty();
    }
    return error;
  }

  /**
   * @return Canonical event ids this message ingested into the event store.
   */
  @JsonProperty("eventIds")
  public Optional<List<String>> getEventIds() {
    return eventIds;
  }

  @JsonProperty("messageId")
  public String getMessageId() {
    return messageId;
  }

  @JsonProperty("occurredAt")
  public OffsetDateTime getOccurredAt() {
    return occurredAt;
  }

  @JsonProperty("role")
  public AgentChatSessionMessagesItemRole getRole() {
    return role;
  }

  /**
   * @return Tool calls made while producing this message. Empty for user messages and failed turns.
   */
  @JsonProperty("steps")
  public Optional<List<AgentChatSessionMessagesItemStepsItem>> getSteps() {
    return steps;
  }

  @JsonProperty("text")
  public String getText() {
    return text;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("error")
  private Optional<String> _getError() {
    return error;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof AgentChatSessionMessagesItem && equalTo((AgentChatSessionMessagesItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(AgentChatSessionMessagesItem other) {
    return error.equals(other.error) && eventIds.equals(other.eventIds) && messageId.equals(other.messageId) && occurredAt.equals(other.occurredAt) && role.equals(other.role) && steps.equals(other.steps) && text.equals(other.text);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.error, this.eventIds, this.messageId, this.occurredAt, this.role, this.steps, this.text);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static MessageIdStage builder() {
    return new Builder();
  }

  public interface MessageIdStage {
    OccurredAtStage messageId(@NotNull String messageId);

    Builder from(AgentChatSessionMessagesItem other);
  }

  public interface OccurredAtStage {
    RoleStage occurredAt(@NotNull OffsetDateTime occurredAt);
  }

  public interface RoleStage {
    TextStage role(@NotNull AgentChatSessionMessagesItemRole role);
  }

  public interface TextStage {
    _FinalStage text(@NotNull String text);
  }

  public interface _FinalStage {
    AgentChatSessionMessagesItem build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Present when the turn failed — the transcript keeps the user message and surfaces the failure instead of fabricating a reply.</p>
     */
    _FinalStage error(Optional<String> error);

    _FinalStage error(String error);

    _FinalStage error(Nullable<String> error);

    /**
     * <p>Canonical event ids this message ingested into the event store.</p>
     */
    _FinalStage eventIds(Optional<List<String>> eventIds);

    _FinalStage eventIds(List<String> eventIds);

    /**
     * <p>Tool calls made while producing this message. Empty for user messages and failed turns.</p>
     */
    _FinalStage steps(Optional<List<AgentChatSessionMessagesItemStepsItem>> steps);

    _FinalStage steps(List<AgentChatSessionMessagesItemStepsItem> steps);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements MessageIdStage, OccurredAtStage, RoleStage, TextStage, _FinalStage {
    private String messageId;

    private OffsetDateTime occurredAt;

    private AgentChatSessionMessagesItemRole role;

    private String text;

    private Optional<List<AgentChatSessionMessagesItemStepsItem>> steps = Optional.empty();

    private Optional<List<String>> eventIds = Optional.empty();

    private Optional<String> error = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(AgentChatSessionMessagesItem other) {
      error(other.getError());
      eventIds(other.getEventIds());
      messageId(other.getMessageId());
      occurredAt(other.getOccurredAt());
      role(other.getRole());
      steps(other.getSteps());
      text(other.getText());
      return this;
    }

    @java.lang.Override
    @JsonSetter("messageId")
    public OccurredAtStage messageId(@NotNull String messageId) {
      this.messageId = Objects.requireNonNull(messageId, "messageId must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("occurredAt")
    public RoleStage occurredAt(@NotNull OffsetDateTime occurredAt) {
      this.occurredAt = Objects.requireNonNull(occurredAt, "occurredAt must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("role")
    public TextStage role(@NotNull AgentChatSessionMessagesItemRole role) {
      this.role = Objects.requireNonNull(role, "role must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("text")
    public _FinalStage text(@NotNull String text) {
      this.text = Objects.requireNonNull(text, "text must not be null");
      return this;
    }

    /**
     * <p>Tool calls made while producing this message. Empty for user messages and failed turns.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage steps(List<AgentChatSessionMessagesItemStepsItem> steps) {
      this.steps = Optional.ofNullable(steps);
      return this;
    }

    /**
     * <p>Tool calls made while producing this message. Empty for user messages and failed turns.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "steps",
        nulls = Nulls.SKIP
    )
    public _FinalStage steps(Optional<List<AgentChatSessionMessagesItemStepsItem>> steps) {
      this.steps = steps;
      return this;
    }

    /**
     * <p>Canonical event ids this message ingested into the event store.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage eventIds(List<String> eventIds) {
      this.eventIds = Optional.ofNullable(eventIds);
      return this;
    }

    /**
     * <p>Canonical event ids this message ingested into the event store.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "eventIds",
        nulls = Nulls.SKIP
    )
    public _FinalStage eventIds(Optional<List<String>> eventIds) {
      this.eventIds = eventIds;
      return this;
    }

    /**
     * <p>Present when the turn failed — the transcript keeps the user message and surfaces the failure instead of fabricating a reply.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage error(Nullable<String> error) {
      if (error.isNull()) {
        this.error = null;
      }
      else if (error.isEmpty()) {
        this.error = Optional.empty();
      }
      else {
        this.error = Optional.of(error.get());
      }
      return this;
    }

    /**
     * <p>Present when the turn failed — the transcript keeps the user message and surfaces the failure instead of fabricating a reply.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage error(String error) {
      this.error = Optional.ofNullable(error);
      return this;
    }

    /**
     * <p>Present when the turn failed — the transcript keeps the user message and surfaces the failure instead of fabricating a reply.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "error",
        nulls = Nulls.SKIP
    )
    public _FinalStage error(Optional<String> error) {
      this.error = error;
      return this;
    }

    @java.lang.Override
    public AgentChatSessionMessagesItem build() {
      return new AgentChatSessionMessagesItem(error, eventIds, messageId, occurredAt, role, steps, text, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
