/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.chronicle.labs.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class AgentSnapshotVersionsItemArtifactWorkflowGraphPreviewNodesItemKind {
    public static final AgentSnapshotVersionsItemArtifactWorkflowGraphPreviewNodesItemKind TOOL =
            new AgentSnapshotVersionsItemArtifactWorkflowGraphPreviewNodesItemKind(Value.TOOL, "tool");

    public static final AgentSnapshotVersionsItemArtifactWorkflowGraphPreviewNodesItemKind MODEL =
            new AgentSnapshotVersionsItemArtifactWorkflowGraphPreviewNodesItemKind(Value.MODEL, "model");

    public static final AgentSnapshotVersionsItemArtifactWorkflowGraphPreviewNodesItemKind INPUT =
            new AgentSnapshotVersionsItemArtifactWorkflowGraphPreviewNodesItemKind(Value.INPUT, "input");

    public static final AgentSnapshotVersionsItemArtifactWorkflowGraphPreviewNodesItemKind OUTPUT =
            new AgentSnapshotVersionsItemArtifactWorkflowGraphPreviewNodesItemKind(Value.OUTPUT, "output");

    public static final AgentSnapshotVersionsItemArtifactWorkflowGraphPreviewNodesItemKind BRANCH =
            new AgentSnapshotVersionsItemArtifactWorkflowGraphPreviewNodesItemKind(Value.BRANCH, "branch");

    private final Value value;

    private final String string;

    AgentSnapshotVersionsItemArtifactWorkflowGraphPreviewNodesItemKind(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof AgentSnapshotVersionsItemArtifactWorkflowGraphPreviewNodesItemKind
                        && this.string.equals(
                                ((AgentSnapshotVersionsItemArtifactWorkflowGraphPreviewNodesItemKind) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case TOOL:
                return visitor.visitTool();
            case MODEL:
                return visitor.visitModel();
            case INPUT:
                return visitor.visitInput();
            case OUTPUT:
                return visitor.visitOutput();
            case BRANCH:
                return visitor.visitBranch();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static AgentSnapshotVersionsItemArtifactWorkflowGraphPreviewNodesItemKind valueOf(String value) {
        switch (value) {
            case "tool":
                return TOOL;
            case "model":
                return MODEL;
            case "input":
                return INPUT;
            case "output":
                return OUTPUT;
            case "branch":
                return BRANCH;
            default:
                return new AgentSnapshotVersionsItemArtifactWorkflowGraphPreviewNodesItemKind(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        INPUT,

        TOOL,

        MODEL,

        BRANCH,

        OUTPUT,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitInput();

        T visitTool();

        T visitModel();

        T visitBranch();

        T visitOutput();

        T visitUnknown(String unknownType);
    }
}
