/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.chronicle.labs.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class AgentSummaryFramework {
    public static final AgentSummaryFramework LLAMAINDEX = new AgentSummaryFramework(Value.LLAMAINDEX, "llamaindex");

    public static final AgentSummaryFramework OPENAI_AGENTS_PYTHON =
            new AgentSummaryFramework(Value.OPENAI_AGENTS_PYTHON, "openai-agents-python");

    public static final AgentSummaryFramework PYDANTIC_AI = new AgentSummaryFramework(Value.PYDANTIC_AI, "pydantic-ai");

    public static final AgentSummaryFramework GOOGLE_ADK = new AgentSummaryFramework(Value.GOOGLE_ADK, "google-adk");

    public static final AgentSummaryFramework CREWAI = new AgentSummaryFramework(Value.CREWAI, "crewai");

    public static final AgentSummaryFramework EVE = new AgentSummaryFramework(Value.EVE, "eve");

    public static final AgentSummaryFramework LANGCHAIN = new AgentSummaryFramework(Value.LANGCHAIN, "langchain");

    public static final AgentSummaryFramework STRANDS = new AgentSummaryFramework(Value.STRANDS, "strands");

    public static final AgentSummaryFramework SALESFORCE_AGENTFORCE =
            new AgentSummaryFramework(Value.SALESFORCE_AGENTFORCE, "salesforce-agentforce");

    public static final AgentSummaryFramework AUTOGEN = new AgentSummaryFramework(Value.AUTOGEN, "autogen");

    public static final AgentSummaryFramework LANGCHAIN_PYTHON =
            new AgentSummaryFramework(Value.LANGCHAIN_PYTHON, "langchain-python");

    public static final AgentSummaryFramework VERCEL_AI_SDK =
            new AgentSummaryFramework(Value.VERCEL_AI_SDK, "vercel-ai-sdk");

    public static final AgentSummaryFramework MASTRA = new AgentSummaryFramework(Value.MASTRA, "mastra");

    public static final AgentSummaryFramework SMOLAGENTS = new AgentSummaryFramework(Value.SMOLAGENTS, "smolagents");

    public static final AgentSummaryFramework OPENAI_AGENTS =
            new AgentSummaryFramework(Value.OPENAI_AGENTS, "openai-agents");

    private final Value value;

    private final String string;

    AgentSummaryFramework(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof AgentSummaryFramework
                        && this.string.equals(((AgentSummaryFramework) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case LLAMAINDEX:
                return visitor.visitLlamaindex();
            case OPENAI_AGENTS_PYTHON:
                return visitor.visitOpenaiAgentsPython();
            case PYDANTIC_AI:
                return visitor.visitPydanticAi();
            case GOOGLE_ADK:
                return visitor.visitGoogleAdk();
            case CREWAI:
                return visitor.visitCrewai();
            case EVE:
                return visitor.visitEve();
            case LANGCHAIN:
                return visitor.visitLangchain();
            case STRANDS:
                return visitor.visitStrands();
            case SALESFORCE_AGENTFORCE:
                return visitor.visitSalesforceAgentforce();
            case AUTOGEN:
                return visitor.visitAutogen();
            case LANGCHAIN_PYTHON:
                return visitor.visitLangchainPython();
            case VERCEL_AI_SDK:
                return visitor.visitVercelAiSdk();
            case MASTRA:
                return visitor.visitMastra();
            case SMOLAGENTS:
                return visitor.visitSmolagents();
            case OPENAI_AGENTS:
                return visitor.visitOpenaiAgents();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static AgentSummaryFramework valueOf(String value) {
        switch (value) {
            case "llamaindex":
                return LLAMAINDEX;
            case "openai-agents-python":
                return OPENAI_AGENTS_PYTHON;
            case "pydantic-ai":
                return PYDANTIC_AI;
            case "google-adk":
                return GOOGLE_ADK;
            case "crewai":
                return CREWAI;
            case "eve":
                return EVE;
            case "langchain":
                return LANGCHAIN;
            case "strands":
                return STRANDS;
            case "salesforce-agentforce":
                return SALESFORCE_AGENTFORCE;
            case "autogen":
                return AUTOGEN;
            case "langchain-python":
                return LANGCHAIN_PYTHON;
            case "vercel-ai-sdk":
                return VERCEL_AI_SDK;
            case "mastra":
                return MASTRA;
            case "smolagents":
                return SMOLAGENTS;
            case "openai-agents":
                return OPENAI_AGENTS;
            default:
                return new AgentSummaryFramework(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        VERCEL_AI_SDK,

        OPENAI_AGENTS,

        LANGCHAIN,

        MASTRA,

        LANGCHAIN_PYTHON,

        LLAMAINDEX,

        CREWAI,

        SMOLAGENTS,

        PYDANTIC_AI,

        STRANDS,

        GOOGLE_ADK,

        OPENAI_AGENTS_PYTHON,

        AUTOGEN,

        EVE,

        SALESFORCE_AGENTFORCE,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitVercelAiSdk();

        T visitOpenaiAgents();

        T visitLangchain();

        T visitMastra();

        T visitLangchainPython();

        T visitLlamaindex();

        T visitCrewai();

        T visitSmolagents();

        T visitPydanticAi();

        T visitStrands();

        T visitGoogleAdk();

        T visitOpenaiAgentsPython();

        T visitAutogen();

        T visitEve();

        T visitSalesforceAgentforce();

        T visitUnknown(String unknownType);
    }
}
