/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.chronicle.labs.api.types;

import com.chronicle.labs.api.core.Nullable;
import com.chronicle.labs.api.core.NullableNonemptyFilter;
import com.chronicle.labs.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = AgentSummary.Builder.class
)
public final class AgentSummary {
  private final Optional<List<String>> capabilityTags;

  private final Optional<String> category;

  private final Optional<String> description;

  private final Optional<String> environment;

  private final AgentSummaryFramework framework;

  private final Optional<OffsetDateTime> lastDriftAt;

  private final Optional<OffsetDateTime> lastRunAt;

  private final String latestVersion;

  private final AgentSummaryModel model;

  private final String modelLabel;

  private final String name;

  private final Optional<String> owner;

  private final Optional<String> personaSummary;

  private final Optional<String> playgroundUrl;

  private final Optional<String> purpose;

  private final Optional<String> runbookUrl;

  private final double successRate;

  private final int totalRuns;

  private final int versionCount;

  private final Map<String, Object> additionalProperties;

  private AgentSummary(Optional<List<String>> capabilityTags, Optional<String> category,
      Optional<String> description, Optional<String> environment, AgentSummaryFramework framework,
      Optional<OffsetDateTime> lastDriftAt, Optional<OffsetDateTime> lastRunAt,
      String latestVersion, AgentSummaryModel model, String modelLabel, String name,
      Optional<String> owner, Optional<String> personaSummary, Optional<String> playgroundUrl,
      Optional<String> purpose, Optional<String> runbookUrl, double successRate, int totalRuns,
      int versionCount, Map<String, Object> additionalProperties) {
    this.capabilityTags = capabilityTags;
    this.category = category;
    this.description = description;
    this.environment = environment;
    this.framework = framework;
    this.lastDriftAt = lastDriftAt;
    this.lastRunAt = lastRunAt;
    this.latestVersion = latestVersion;
    this.model = model;
    this.modelLabel = modelLabel;
    this.name = name;
    this.owner = owner;
    this.personaSummary = personaSummary;
    this.playgroundUrl = playgroundUrl;
    this.purpose = purpose;
    this.runbookUrl = runbookUrl;
    this.successRate = successRate;
    this.totalRuns = totalRuns;
    this.versionCount = versionCount;
    this.additionalProperties = additionalProperties;
  }

  @JsonIgnore
  public Optional<List<String>> getCapabilityTags() {
    if (capabilityTags == null) {
      return Optional.empty();
    }
    return capabilityTags;
  }

  @JsonIgnore
  public Optional<String> getCategory() {
    if (category == null) {
      return Optional.empty();
    }
    return category;
  }

  @JsonIgnore
  public Optional<String> getDescription() {
    if (description == null) {
      return Optional.empty();
    }
    return description;
  }

  @JsonIgnore
  public Optional<String> getEnvironment() {
    if (environment == null) {
      return Optional.empty();
    }
    return environment;
  }

  /**
   * @return Framework label. Multi-word kebab-case to match the existing TS union (<code>vercel-ai-sdk</code>, <code>openai-agents-python</code>, etc.).
   */
  @JsonProperty("framework")
  public AgentSummaryFramework getFramework() {
    return framework;
  }

  /**
   * @return Last drift event, if any.
   */
  @JsonIgnore
  public Optional<OffsetDateTime> getLastDriftAt() {
    if (lastDriftAt == null) {
      return Optional.empty();
    }
    return lastDriftAt;
  }

  @JsonIgnore
  public Optional<OffsetDateTime> getLastRunAt() {
    if (lastRunAt == null) {
      return Optional.empty();
    }
    return lastRunAt;
  }

  @JsonProperty("latestVersion")
  public String getLatestVersion() {
    return latestVersion;
  }

  @JsonProperty("model")
  public AgentSummaryModel getModel() {
    return model;
  }

  @JsonProperty("modelLabel")
  public String getModelLabel() {
    return modelLabel;
  }

  @JsonProperty("name")
  public String getName() {
    return name;
  }

  @JsonIgnore
  public Optional<String> getOwner() {
    if (owner == null) {
      return Optional.empty();
    }
    return owner;
  }

  @JsonIgnore
  public Optional<String> getPersonaSummary() {
    if (personaSummary == null) {
      return Optional.empty();
    }
    return personaSummary;
  }

  @JsonIgnore
  public Optional<String> getPlaygroundUrl() {
    if (playgroundUrl == null) {
      return Optional.empty();
    }
    return playgroundUrl;
  }

  @JsonIgnore
  public Optional<String> getPurpose() {
    if (purpose == null) {
      return Optional.empty();
    }
    return purpose;
  }

  @JsonIgnore
  public Optional<String> getRunbookUrl() {
    if (runbookUrl == null) {
      return Optional.empty();
    }
    return runbookUrl;
  }

  @JsonProperty("successRate")
  public double getSuccessRate() {
    return successRate;
  }

  @JsonProperty("totalRuns")
  public int getTotalRuns() {
    return totalRuns;
  }

  @JsonProperty("versionCount")
  public int getVersionCount() {
    return versionCount;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("capabilityTags")
  private Optional<List<String>> _getCapabilityTags() {
    return capabilityTags;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("category")
  private Optional<String> _getCategory() {
    return category;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("description")
  private Optional<String> _getDescription() {
    return description;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("environment")
  private Optional<String> _getEnvironment() {
    return environment;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("lastDriftAt")
  private Optional<OffsetDateTime> _getLastDriftAt() {
    return lastDriftAt;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("lastRunAt")
  private Optional<OffsetDateTime> _getLastRunAt() {
    return lastRunAt;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("owner")
  private Optional<String> _getOwner() {
    return owner;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("personaSummary")
  private Optional<String> _getPersonaSummary() {
    return personaSummary;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("playgroundUrl")
  private Optional<String> _getPlaygroundUrl() {
    return playgroundUrl;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("purpose")
  private Optional<String> _getPurpose() {
    return purpose;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("runbookUrl")
  private Optional<String> _getRunbookUrl() {
    return runbookUrl;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof AgentSummary && equalTo((AgentSummary) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(AgentSummary other) {
    return capabilityTags.equals(other.capabilityTags) && category.equals(other.category) && description.equals(other.description) && environment.equals(other.environment) && framework.equals(other.framework) && lastDriftAt.equals(other.lastDriftAt) && lastRunAt.equals(other.lastRunAt) && latestVersion.equals(other.latestVersion) && model.equals(other.model) && modelLabel.equals(other.modelLabel) && name.equals(other.name) && owner.equals(other.owner) && personaSummary.equals(other.personaSummary) && playgroundUrl.equals(other.playgroundUrl) && purpose.equals(other.purpose) && runbookUrl.equals(other.runbookUrl) && successRate == other.successRate && totalRuns == other.totalRuns && versionCount == other.versionCount;
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.capabilityTags, this.category, this.description, this.environment, this.framework, this.lastDriftAt, this.lastRunAt, this.latestVersion, this.model, this.modelLabel, this.name, this.owner, this.personaSummary, this.playgroundUrl, this.purpose, this.runbookUrl, this.successRate, this.totalRuns, this.versionCount);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static FrameworkStage builder() {
    return new Builder();
  }

  public interface FrameworkStage {
    /**
     * <p>Framework label. Multi-word kebab-case to match the existing TS union (<code>vercel-ai-sdk</code>, <code>openai-agents-python</code>, etc.).</p>
     */
    LatestVersionStage framework(@NotNull AgentSummaryFramework framework);

    Builder from(AgentSummary other);
  }

  public interface LatestVersionStage {
    ModelStage latestVersion(@NotNull String latestVersion);
  }

  public interface ModelStage {
    ModelLabelStage model(@NotNull AgentSummaryModel model);
  }

  public interface ModelLabelStage {
    NameStage modelLabel(@NotNull String modelLabel);
  }

  public interface NameStage {
    SuccessRateStage name(@NotNull String name);
  }

  public interface SuccessRateStage {
    TotalRunsStage successRate(double successRate);
  }

  public interface TotalRunsStage {
    VersionCountStage totalRuns(int totalRuns);
  }

  public interface VersionCountStage {
    _FinalStage versionCount(int versionCount);
  }

  public interface _FinalStage {
    AgentSummary build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage capabilityTags(Optional<List<String>> capabilityTags);

    _FinalStage capabilityTags(List<String> capabilityTags);

    _FinalStage capabilityTags(Nullable<List<String>> capabilityTags);

    _FinalStage category(Optional<String> category);

    _FinalStage category(String category);

    _FinalStage category(Nullable<String> category);

    _FinalStage description(Optional<String> description);

    _FinalStage description(String description);

    _FinalStage description(Nullable<String> description);

    _FinalStage environment(Optional<String> environment);

    _FinalStage environment(String environment);

    _FinalStage environment(Nullable<String> environment);

    /**
     * <p>Last drift event, if any.</p>
     */
    _FinalStage lastDriftAt(Optional<OffsetDateTime> lastDriftAt);

    _FinalStage lastDriftAt(OffsetDateTime lastDriftAt);

    _FinalStage lastDriftAt(Nullable<OffsetDateTime> lastDriftAt);

    _FinalStage lastRunAt(Optional<OffsetDateTime> lastRunAt);

    _FinalStage lastRunAt(OffsetDateTime lastRunAt);

    _FinalStage lastRunAt(Nullable<OffsetDateTime> lastRunAt);

    _FinalStage owner(Optional<String> owner);

    _FinalStage owner(String owner);

    _FinalStage owner(Nullable<String> owner);

    _FinalStage personaSummary(Optional<String> personaSummary);

    _FinalStage personaSummary(String personaSummary);

    _FinalStage personaSummary(Nullable<String> personaSummary);

    _FinalStage playgroundUrl(Optional<String> playgroundUrl);

    _FinalStage playgroundUrl(String playgroundUrl);

    _FinalStage playgroundUrl(Nullable<String> playgroundUrl);

    _FinalStage purpose(Optional<String> purpose);

    _FinalStage purpose(String purpose);

    _FinalStage purpose(Nullable<String> purpose);

    _FinalStage runbookUrl(Optional<String> runbookUrl);

    _FinalStage runbookUrl(String runbookUrl);

    _FinalStage runbookUrl(Nullable<String> runbookUrl);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements FrameworkStage, LatestVersionStage, ModelStage, ModelLabelStage, NameStage, SuccessRateStage, TotalRunsStage, VersionCountStage, _FinalStage {
    private AgentSummaryFramework framework;

    private String latestVersion;

    private AgentSummaryModel model;

    private String modelLabel;

    private String name;

    private double successRate;

    private int totalRuns;

    private int versionCount;

    private Optional<String> runbookUrl = Optional.empty();

    private Optional<String> purpose = Optional.empty();

    private Optional<String> playgroundUrl = Optional.empty();

    private Optional<String> personaSummary = Optional.empty();

    private Optional<String> owner = Optional.empty();

    private Optional<OffsetDateTime> lastRunAt = Optional.empty();

    private Optional<OffsetDateTime> lastDriftAt = Optional.empty();

    private Optional<String> environment = Optional.empty();

    private Optional<String> description = Optional.empty();

    private Optional<String> category = Optional.empty();

    private Optional<List<String>> capabilityTags = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(AgentSummary other) {
      capabilityTags(other.getCapabilityTags());
      category(other.getCategory());
      description(other.getDescription());
      environment(other.getEnvironment());
      framework(other.getFramework());
      lastDriftAt(other.getLastDriftAt());
      lastRunAt(other.getLastRunAt());
      latestVersion(other.getLatestVersion());
      model(other.getModel());
      modelLabel(other.getModelLabel());
      name(other.getName());
      owner(other.getOwner());
      personaSummary(other.getPersonaSummary());
      playgroundUrl(other.getPlaygroundUrl());
      purpose(other.getPurpose());
      runbookUrl(other.getRunbookUrl());
      successRate(other.getSuccessRate());
      totalRuns(other.getTotalRuns());
      versionCount(other.getVersionCount());
      return this;
    }

    /**
     * <p>Framework label. Multi-word kebab-case to match the existing TS union (<code>vercel-ai-sdk</code>, <code>openai-agents-python</code>, etc.).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("framework")
    public LatestVersionStage framework(@NotNull AgentSummaryFramework framework) {
      this.framework = Objects.requireNonNull(framework, "framework must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("latestVersion")
    public ModelStage latestVersion(@NotNull String latestVersion) {
      this.latestVersion = Objects.requireNonNull(latestVersion, "latestVersion must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("model")
    public ModelLabelStage model(@NotNull AgentSummaryModel model) {
      this.model = Objects.requireNonNull(model, "model must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("modelLabel")
    public NameStage modelLabel(@NotNull String modelLabel) {
      this.modelLabel = Objects.requireNonNull(modelLabel, "modelLabel must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("name")
    public SuccessRateStage name(@NotNull String name) {
      this.name = Objects.requireNonNull(name, "name must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("successRate")
    public TotalRunsStage successRate(double successRate) {
      this.successRate = successRate;
      return this;
    }

    @java.lang.Override
    @JsonSetter("totalRuns")
    public VersionCountStage totalRuns(int totalRuns) {
      this.totalRuns = totalRuns;
      return this;
    }

    @java.lang.Override
    @JsonSetter("versionCount")
    public _FinalStage versionCount(int versionCount) {
      this.versionCount = versionCount;
      return this;
    }

    @java.lang.Override
    public _FinalStage runbookUrl(Nullable<String> runbookUrl) {
      if (runbookUrl.isNull()) {
        this.runbookUrl = null;
      }
      else if (runbookUrl.isEmpty()) {
        this.runbookUrl = Optional.empty();
      }
      else {
        this.runbookUrl = Optional.of(runbookUrl.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage runbookUrl(String runbookUrl) {
      this.runbookUrl = Optional.ofNullable(runbookUrl);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "runbookUrl",
        nulls = Nulls.SKIP
    )
    public _FinalStage runbookUrl(Optional<String> runbookUrl) {
      this.runbookUrl = runbookUrl;
      return this;
    }

    @java.lang.Override
    public _FinalStage purpose(Nullable<String> purpose) {
      if (purpose.isNull()) {
        this.purpose = null;
      }
      else if (purpose.isEmpty()) {
        this.purpose = Optional.empty();
      }
      else {
        this.purpose = Optional.of(purpose.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage purpose(String purpose) {
      this.purpose = Optional.ofNullable(purpose);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "purpose",
        nulls = Nulls.SKIP
    )
    public _FinalStage purpose(Optional<String> purpose) {
      this.purpose = purpose;
      return this;
    }

    @java.lang.Override
    public _FinalStage playgroundUrl(Nullable<String> playgroundUrl) {
      if (playgroundUrl.isNull()) {
        this.playgroundUrl = null;
      }
      else if (playgroundUrl.isEmpty()) {
        this.playgroundUrl = Optional.empty();
      }
      else {
        this.playgroundUrl = Optional.of(playgroundUrl.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage playgroundUrl(String playgroundUrl) {
      this.playgroundUrl = Optional.ofNullable(playgroundUrl);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "playgroundUrl",
        nulls = Nulls.SKIP
    )
    public _FinalStage playgroundUrl(Optional<String> playgroundUrl) {
      this.playgroundUrl = playgroundUrl;
      return this;
    }

    @java.lang.Override
    public _FinalStage personaSummary(Nullable<String> personaSummary) {
      if (personaSummary.isNull()) {
        this.personaSummary = null;
      }
      else if (personaSummary.isEmpty()) {
        this.personaSummary = Optional.empty();
      }
      else {
        this.personaSummary = Optional.of(personaSummary.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage personaSummary(String personaSummary) {
      this.personaSummary = Optional.ofNullable(personaSummary);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "personaSummary",
        nulls = Nulls.SKIP
    )
    public _FinalStage personaSummary(Optional<String> personaSummary) {
      this.personaSummary = personaSummary;
      return this;
    }

    @java.lang.Override
    public _FinalStage owner(Nullable<String> owner) {
      if (owner.isNull()) {
        this.owner = null;
      }
      else if (owner.isEmpty()) {
        this.owner = Optional.empty();
      }
      else {
        this.owner = Optional.of(owner.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage owner(String owner) {
      this.owner = Optional.ofNullable(owner);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "owner",
        nulls = Nulls.SKIP
    )
    public _FinalStage owner(Optional<String> owner) {
      this.owner = owner;
      return this;
    }

    @java.lang.Override
    public _FinalStage lastRunAt(Nullable<OffsetDateTime> lastRunAt) {
      if (lastRunAt.isNull()) {
        this.lastRunAt = null;
      }
      else if (lastRunAt.isEmpty()) {
        this.lastRunAt = Optional.empty();
      }
      else {
        this.lastRunAt = Optional.of(lastRunAt.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage lastRunAt(OffsetDateTime lastRunAt) {
      this.lastRunAt = Optional.ofNullable(lastRunAt);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "lastRunAt",
        nulls = Nulls.SKIP
    )
    public _FinalStage lastRunAt(Optional<OffsetDateTime> lastRunAt) {
      this.lastRunAt = lastRunAt;
      return this;
    }

    /**
     * <p>Last drift event, if any.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage lastDriftAt(Nullable<OffsetDateTime> lastDriftAt) {
      if (lastDriftAt.isNull()) {
        this.lastDriftAt = null;
      }
      else if (lastDriftAt.isEmpty()) {
        this.lastDriftAt = Optional.empty();
      }
      else {
        this.lastDriftAt = Optional.of(lastDriftAt.get());
      }
      return this;
    }

    /**
     * <p>Last drift event, if any.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage lastDriftAt(OffsetDateTime lastDriftAt) {
      this.lastDriftAt = Optional.ofNullable(lastDriftAt);
      return this;
    }

    /**
     * <p>Last drift event, if any.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "lastDriftAt",
        nulls = Nulls.SKIP
    )
    public _FinalStage lastDriftAt(Optional<OffsetDateTime> lastDriftAt) {
      this.lastDriftAt = lastDriftAt;
      return this;
    }

    @java.lang.Override
    public _FinalStage environment(Nullable<String> environment) {
      if (environment.isNull()) {
        this.environment = null;
      }
      else if (environment.isEmpty()) {
        this.environment = Optional.empty();
      }
      else {
        this.environment = Optional.of(environment.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage environment(String environment) {
      this.environment = Optional.ofNullable(environment);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "environment",
        nulls = Nulls.SKIP
    )
    public _FinalStage environment(Optional<String> environment) {
      this.environment = environment;
      return this;
    }

    @java.lang.Override
    public _FinalStage description(Nullable<String> description) {
      if (description.isNull()) {
        this.description = null;
      }
      else if (description.isEmpty()) {
        this.description = Optional.empty();
      }
      else {
        this.description = Optional.of(description.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage description(String description) {
      this.description = Optional.ofNullable(description);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "description",
        nulls = Nulls.SKIP
    )
    public _FinalStage description(Optional<String> description) {
      this.description = description;
      return this;
    }

    @java.lang.Override
    public _FinalStage category(Nullable<String> category) {
      if (category.isNull()) {
        this.category = null;
      }
      else if (category.isEmpty()) {
        this.category = Optional.empty();
      }
      else {
        this.category = Optional.of(category.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage category(String category) {
      this.category = Optional.ofNullable(category);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "category",
        nulls = Nulls.SKIP
    )
    public _FinalStage category(Optional<String> category) {
      this.category = category;
      return this;
    }

    @java.lang.Override
    public _FinalStage capabilityTags(Nullable<List<String>> capabilityTags) {
      if (capabilityTags.isNull()) {
        this.capabilityTags = null;
      }
      else if (capabilityTags.isEmpty()) {
        this.capabilityTags = Optional.empty();
      }
      else {
        this.capabilityTags = Optional.of(capabilityTags.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage capabilityTags(List<String> capabilityTags) {
      this.capabilityTags = Optional.ofNullable(capabilityTags);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "capabilityTags",
        nulls = Nulls.SKIP
    )
    public _FinalStage capabilityTags(Optional<List<String>> capabilityTags) {
      this.capabilityTags = capabilityTags;
      return this;
    }

    @java.lang.Override
    public AgentSummary build() {
      return new AgentSummary(capabilityTags, category, description, environment, framework, lastDriftAt, lastRunAt, latestVersion, model, modelLabel, name, owner, personaSummary, playgroundUrl, purpose, runbookUrl, successRate, totalRuns, versionCount, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
