/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.chronicle.labs.api.types;

import com.chronicle.labs.api.core.Nullable;
import com.chronicle.labs.api.core.NullableNonemptyFilter;
import com.chronicle.labs.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = AgentSnapshotRunsItemToolCallsItem.Builder.class)
public final class AgentSnapshotRunsItemToolCallsItem {
    private final Optional<String> argsHash;

    private final Optional<Map<String, Object>> argsPreview;

    private final String callId;

    private final Optional<Integer> durationMs;

    private final Optional<AgentSnapshotRunsItemToolCallsItemError> error;

    private final Optional<OffsetDateTime> finishedAt;

    private final Optional<String> resultHash;

    private final Optional<Map<String, Object>> resultPreview;

    private final OffsetDateTime startedAt;

    private final AgentSnapshotRunsItemToolCallsItemStatus status;

    private final String toolName;

    private final Map<String, Object> additionalProperties;

    private AgentSnapshotRunsItemToolCallsItem(
            Optional<String> argsHash,
            Optional<Map<String, Object>> argsPreview,
            String callId,
            Optional<Integer> durationMs,
            Optional<AgentSnapshotRunsItemToolCallsItemError> error,
            Optional<OffsetDateTime> finishedAt,
            Optional<String> resultHash,
            Optional<Map<String, Object>> resultPreview,
            OffsetDateTime startedAt,
            AgentSnapshotRunsItemToolCallsItemStatus status,
            String toolName,
            Map<String, Object> additionalProperties) {
        this.argsHash = argsHash;
        this.argsPreview = argsPreview;
        this.callId = callId;
        this.durationMs = durationMs;
        this.error = error;
        this.finishedAt = finishedAt;
        this.resultHash = resultHash;
        this.resultPreview = resultPreview;
        this.startedAt = startedAt;
        this.status = status;
        this.toolName = toolName;
        this.additionalProperties = additionalProperties;
    }

    @JsonIgnore
    public Optional<String> getArgsHash() {
        if (argsHash == null) {
            return Optional.empty();
        }
        return argsHash;
    }

    /**
     * @return Optional small preview of the tool args.
     */
    @JsonIgnore
    public Optional<Map<String, Object>> getArgsPreview() {
        if (argsPreview == null) {
            return Optional.empty();
        }
        return argsPreview;
    }

    @JsonProperty("callId")
    public String getCallId() {
        return callId;
    }

    @JsonIgnore
    public Optional<Integer> getDurationMs() {
        if (durationMs == null) {
            return Optional.empty();
        }
        return durationMs;
    }

    @JsonIgnore
    public Optional<AgentSnapshotRunsItemToolCallsItemError> getError() {
        if (error == null) {
            return Optional.empty();
        }
        return error;
    }

    @JsonIgnore
    public Optional<OffsetDateTime> getFinishedAt() {
        if (finishedAt == null) {
            return Optional.empty();
        }
        return finishedAt;
    }

    @JsonIgnore
    public Optional<String> getResultHash() {
        if (resultHash == null) {
            return Optional.empty();
        }
        return resultHash;
    }

    @JsonIgnore
    public Optional<Map<String, Object>> getResultPreview() {
        if (resultPreview == null) {
            return Optional.empty();
        }
        return resultPreview;
    }

    @JsonProperty("startedAt")
    public OffsetDateTime getStartedAt() {
        return startedAt;
    }

    @JsonProperty("status")
    public AgentSnapshotRunsItemToolCallsItemStatus getStatus() {
        return status;
    }

    @JsonProperty("toolName")
    public String getToolName() {
        return toolName;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("argsHash")
    private Optional<String> _getArgsHash() {
        return argsHash;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("argsPreview")
    private Optional<Map<String, Object>> _getArgsPreview() {
        return argsPreview;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("durationMs")
    private Optional<Integer> _getDurationMs() {
        return durationMs;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("error")
    private Optional<AgentSnapshotRunsItemToolCallsItemError> _getError() {
        return error;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("finishedAt")
    private Optional<OffsetDateTime> _getFinishedAt() {
        return finishedAt;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("resultHash")
    private Optional<String> _getResultHash() {
        return resultHash;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("resultPreview")
    private Optional<Map<String, Object>> _getResultPreview() {
        return resultPreview;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof AgentSnapshotRunsItemToolCallsItem
                && equalTo((AgentSnapshotRunsItemToolCallsItem) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(AgentSnapshotRunsItemToolCallsItem other) {
        return argsHash.equals(other.argsHash)
                && argsPreview.equals(other.argsPreview)
                && callId.equals(other.callId)
                && durationMs.equals(other.durationMs)
                && error.equals(other.error)
                && finishedAt.equals(other.finishedAt)
                && resultHash.equals(other.resultHash)
                && resultPreview.equals(other.resultPreview)
                && startedAt.equals(other.startedAt)
                && status.equals(other.status)
                && toolName.equals(other.toolName);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.argsHash,
                this.argsPreview,
                this.callId,
                this.durationMs,
                this.error,
                this.finishedAt,
                this.resultHash,
                this.resultPreview,
                this.startedAt,
                this.status,
                this.toolName);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static CallIdStage builder() {
        return new Builder();
    }

    public interface CallIdStage {
        StartedAtStage callId(@NotNull String callId);

        Builder from(AgentSnapshotRunsItemToolCallsItem other);
    }

    public interface StartedAtStage {
        StatusStage startedAt(@NotNull OffsetDateTime startedAt);
    }

    public interface StatusStage {
        ToolNameStage status(@NotNull AgentSnapshotRunsItemToolCallsItemStatus status);
    }

    public interface ToolNameStage {
        _FinalStage toolName(@NotNull String toolName);
    }

    public interface _FinalStage {
        AgentSnapshotRunsItemToolCallsItem build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage argsHash(Optional<String> argsHash);

        _FinalStage argsHash(String argsHash);

        _FinalStage argsHash(Nullable<String> argsHash);

        /**
         * <p>Optional small preview of the tool args.</p>
         */
        _FinalStage argsPreview(Optional<Map<String, Object>> argsPreview);

        _FinalStage argsPreview(Map<String, Object> argsPreview);

        _FinalStage argsPreview(Nullable<Map<String, Object>> argsPreview);

        _FinalStage durationMs(Optional<Integer> durationMs);

        _FinalStage durationMs(Integer durationMs);

        _FinalStage durationMs(Nullable<Integer> durationMs);

        _FinalStage error(Optional<AgentSnapshotRunsItemToolCallsItemError> error);

        _FinalStage error(AgentSnapshotRunsItemToolCallsItemError error);

        _FinalStage error(Nullable<AgentSnapshotRunsItemToolCallsItemError> error);

        _FinalStage finishedAt(Optional<OffsetDateTime> finishedAt);

        _FinalStage finishedAt(OffsetDateTime finishedAt);

        _FinalStage finishedAt(Nullable<OffsetDateTime> finishedAt);

        _FinalStage resultHash(Optional<String> resultHash);

        _FinalStage resultHash(String resultHash);

        _FinalStage resultHash(Nullable<String> resultHash);

        _FinalStage resultPreview(Optional<Map<String, Object>> resultPreview);

        _FinalStage resultPreview(Map<String, Object> resultPreview);

        _FinalStage resultPreview(Nullable<Map<String, Object>> resultPreview);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements CallIdStage, StartedAtStage, StatusStage, ToolNameStage, _FinalStage {
        private String callId;

        private OffsetDateTime startedAt;

        private AgentSnapshotRunsItemToolCallsItemStatus status;

        private String toolName;

        private Optional<Map<String, Object>> resultPreview = Optional.empty();

        private Optional<String> resultHash = Optional.empty();

        private Optional<OffsetDateTime> finishedAt = Optional.empty();

        private Optional<AgentSnapshotRunsItemToolCallsItemError> error = Optional.empty();

        private Optional<Integer> durationMs = Optional.empty();

        private Optional<Map<String, Object>> argsPreview = Optional.empty();

        private Optional<String> argsHash = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(AgentSnapshotRunsItemToolCallsItem other) {
            argsHash(other.getArgsHash());
            argsPreview(other.getArgsPreview());
            callId(other.getCallId());
            durationMs(other.getDurationMs());
            error(other.getError());
            finishedAt(other.getFinishedAt());
            resultHash(other.getResultHash());
            resultPreview(other.getResultPreview());
            startedAt(other.getStartedAt());
            status(other.getStatus());
            toolName(other.getToolName());
            return this;
        }

        @java.lang.Override
        @JsonSetter("callId")
        public StartedAtStage callId(@NotNull String callId) {
            this.callId = Objects.requireNonNull(callId, "callId must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("startedAt")
        public StatusStage startedAt(@NotNull OffsetDateTime startedAt) {
            this.startedAt = Objects.requireNonNull(startedAt, "startedAt must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("status")
        public ToolNameStage status(@NotNull AgentSnapshotRunsItemToolCallsItemStatus status) {
            this.status = Objects.requireNonNull(status, "status must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("toolName")
        public _FinalStage toolName(@NotNull String toolName) {
            this.toolName = Objects.requireNonNull(toolName, "toolName must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage resultPreview(Nullable<Map<String, Object>> resultPreview) {
            if (resultPreview.isNull()) {
                this.resultPreview = null;
            } else if (resultPreview.isEmpty()) {
                this.resultPreview = Optional.empty();
            } else {
                this.resultPreview = Optional.of(resultPreview.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage resultPreview(Map<String, Object> resultPreview) {
            this.resultPreview = Optional.ofNullable(resultPreview);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "resultPreview", nulls = Nulls.SKIP)
        public _FinalStage resultPreview(Optional<Map<String, Object>> resultPreview) {
            this.resultPreview = resultPreview;
            return this;
        }

        @java.lang.Override
        public _FinalStage resultHash(Nullable<String> resultHash) {
            if (resultHash.isNull()) {
                this.resultHash = null;
            } else if (resultHash.isEmpty()) {
                this.resultHash = Optional.empty();
            } else {
                this.resultHash = Optional.of(resultHash.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage resultHash(String resultHash) {
            this.resultHash = Optional.ofNullable(resultHash);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "resultHash", nulls = Nulls.SKIP)
        public _FinalStage resultHash(Optional<String> resultHash) {
            this.resultHash = resultHash;
            return this;
        }

        @java.lang.Override
        public _FinalStage finishedAt(Nullable<OffsetDateTime> finishedAt) {
            if (finishedAt.isNull()) {
                this.finishedAt = null;
            } else if (finishedAt.isEmpty()) {
                this.finishedAt = Optional.empty();
            } else {
                this.finishedAt = Optional.of(finishedAt.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage finishedAt(OffsetDateTime finishedAt) {
            this.finishedAt = Optional.ofNullable(finishedAt);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "finishedAt", nulls = Nulls.SKIP)
        public _FinalStage finishedAt(Optional<OffsetDateTime> finishedAt) {
            this.finishedAt = finishedAt;
            return this;
        }

        @java.lang.Override
        public _FinalStage error(Nullable<AgentSnapshotRunsItemToolCallsItemError> error) {
            if (error.isNull()) {
                this.error = null;
            } else if (error.isEmpty()) {
                this.error = Optional.empty();
            } else {
                this.error = Optional.of(error.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage error(AgentSnapshotRunsItemToolCallsItemError error) {
            this.error = Optional.ofNullable(error);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "error", nulls = Nulls.SKIP)
        public _FinalStage error(Optional<AgentSnapshotRunsItemToolCallsItemError> error) {
            this.error = error;
            return this;
        }

        @java.lang.Override
        public _FinalStage durationMs(Nullable<Integer> durationMs) {
            if (durationMs.isNull()) {
                this.durationMs = null;
            } else if (durationMs.isEmpty()) {
                this.durationMs = Optional.empty();
            } else {
                this.durationMs = Optional.of(durationMs.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage durationMs(Integer durationMs) {
            this.durationMs = Optional.ofNullable(durationMs);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "durationMs", nulls = Nulls.SKIP)
        public _FinalStage durationMs(Optional<Integer> durationMs) {
            this.durationMs = durationMs;
            return this;
        }

        /**
         * <p>Optional small preview of the tool args.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage argsPreview(Nullable<Map<String, Object>> argsPreview) {
            if (argsPreview.isNull()) {
                this.argsPreview = null;
            } else if (argsPreview.isEmpty()) {
                this.argsPreview = Optional.empty();
            } else {
                this.argsPreview = Optional.of(argsPreview.get());
            }
            return this;
        }

        /**
         * <p>Optional small preview of the tool args.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage argsPreview(Map<String, Object> argsPreview) {
            this.argsPreview = Optional.ofNullable(argsPreview);
            return this;
        }

        /**
         * <p>Optional small preview of the tool args.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "argsPreview", nulls = Nulls.SKIP)
        public _FinalStage argsPreview(Optional<Map<String, Object>> argsPreview) {
            this.argsPreview = argsPreview;
            return this;
        }

        @java.lang.Override
        public _FinalStage argsHash(Nullable<String> argsHash) {
            if (argsHash.isNull()) {
                this.argsHash = null;
            } else if (argsHash.isEmpty()) {
                this.argsHash = Optional.empty();
            } else {
                this.argsHash = Optional.of(argsHash.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage argsHash(String argsHash) {
            this.argsHash = Optional.ofNullable(argsHash);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "argsHash", nulls = Nulls.SKIP)
        public _FinalStage argsHash(Optional<String> argsHash) {
            this.argsHash = argsHash;
            return this;
        }

        @java.lang.Override
        public AgentSnapshotRunsItemToolCallsItem build() {
            return new AgentSnapshotRunsItemToolCallsItem(
                    argsHash,
                    argsPreview,
                    callId,
                    durationMs,
                    error,
                    finishedAt,
                    resultHash,
                    resultPreview,
                    startedAt,
                    status,
                    toolName,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
