/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.chronicle.labs.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class AgentSnapshotVersionsItemStatus {
    public static final AgentSnapshotVersionsItemStatus CURRENT =
            new AgentSnapshotVersionsItemStatus(Value.CURRENT, "current");

    public static final AgentSnapshotVersionsItemStatus STABLE =
            new AgentSnapshotVersionsItemStatus(Value.STABLE, "stable");

    public static final AgentSnapshotVersionsItemStatus DEPRECATED =
            new AgentSnapshotVersionsItemStatus(Value.DEPRECATED, "deprecated");

    public static final AgentSnapshotVersionsItemStatus DRAFT =
            new AgentSnapshotVersionsItemStatus(Value.DRAFT, "draft");

    private final Value value;

    private final String string;

    AgentSnapshotVersionsItemStatus(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof AgentSnapshotVersionsItemStatus
                        && this.string.equals(((AgentSnapshotVersionsItemStatus) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case CURRENT:
                return visitor.visitCurrent();
            case STABLE:
                return visitor.visitStable();
            case DEPRECATED:
                return visitor.visitDeprecated();
            case DRAFT:
                return visitor.visitDraft();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static AgentSnapshotVersionsItemStatus valueOf(String value) {
        switch (value) {
            case "current":
                return CURRENT;
            case "stable":
                return STABLE;
            case "deprecated":
                return DEPRECATED;
            case "draft":
                return DRAFT;
            default:
                return new AgentSnapshotVersionsItemStatus(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        CURRENT,

        STABLE,

        DEPRECATED,

        DRAFT,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitCurrent();

        T visitStable();

        T visitDeprecated();

        T visitDraft();

        T visitUnknown(String unknownType);
    }
}
