/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.chronicle.labs.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class AgentSnapshotSummaryFramework {
  public static final AgentSnapshotSummaryFramework LLAMAINDEX = new AgentSnapshotSummaryFramework(Value.LLAMAINDEX, "llamaindex");

  public static final AgentSnapshotSummaryFramework OPENAI_AGENTS_PYTHON = new AgentSnapshotSummaryFramework(Value.OPENAI_AGENTS_PYTHON, "openai-agents-python");

  public static final AgentSnapshotSummaryFramework PYDANTIC_AI = new AgentSnapshotSummaryFramework(Value.PYDANTIC_AI, "pydantic-ai");

  public static final AgentSnapshotSummaryFramework GOOGLE_ADK = new AgentSnapshotSummaryFramework(Value.GOOGLE_ADK, "google-adk");

  public static final AgentSnapshotSummaryFramework CREWAI = new AgentSnapshotSummaryFramework(Value.CREWAI, "crewai");

  public static final AgentSnapshotSummaryFramework EVE = new AgentSnapshotSummaryFramework(Value.EVE, "eve");

  public static final AgentSnapshotSummaryFramework LANGCHAIN = new AgentSnapshotSummaryFramework(Value.LANGCHAIN, "langchain");

  public static final AgentSnapshotSummaryFramework STRANDS = new AgentSnapshotSummaryFramework(Value.STRANDS, "strands");

  public static final AgentSnapshotSummaryFramework SALESFORCE_AGENTFORCE = new AgentSnapshotSummaryFramework(Value.SALESFORCE_AGENTFORCE, "salesforce-agentforce");

  public static final AgentSnapshotSummaryFramework AUTOGEN = new AgentSnapshotSummaryFramework(Value.AUTOGEN, "autogen");

  public static final AgentSnapshotSummaryFramework LANGCHAIN_PYTHON = new AgentSnapshotSummaryFramework(Value.LANGCHAIN_PYTHON, "langchain-python");

  public static final AgentSnapshotSummaryFramework VERCEL_AI_SDK = new AgentSnapshotSummaryFramework(Value.VERCEL_AI_SDK, "vercel-ai-sdk");

  public static final AgentSnapshotSummaryFramework MASTRA = new AgentSnapshotSummaryFramework(Value.MASTRA, "mastra");

  public static final AgentSnapshotSummaryFramework SMOLAGENTS = new AgentSnapshotSummaryFramework(Value.SMOLAGENTS, "smolagents");

  public static final AgentSnapshotSummaryFramework OPENAI_AGENTS = new AgentSnapshotSummaryFramework(Value.OPENAI_AGENTS, "openai-agents");

  private final Value value;

  private final String string;

  AgentSnapshotSummaryFramework(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof AgentSnapshotSummaryFramework && this.string.equals(((AgentSnapshotSummaryFramework) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case LLAMAINDEX:
        return visitor.visitLlamaindex();
      case OPENAI_AGENTS_PYTHON:
        return visitor.visitOpenaiAgentsPython();
      case PYDANTIC_AI:
        return visitor.visitPydanticAi();
      case GOOGLE_ADK:
        return visitor.visitGoogleAdk();
      case CREWAI:
        return visitor.visitCrewai();
      case EVE:
        return visitor.visitEve();
      case LANGCHAIN:
        return visitor.visitLangchain();
      case STRANDS:
        return visitor.visitStrands();
      case SALESFORCE_AGENTFORCE:
        return visitor.visitSalesforceAgentforce();
      case AUTOGEN:
        return visitor.visitAutogen();
      case LANGCHAIN_PYTHON:
        return visitor.visitLangchainPython();
      case VERCEL_AI_SDK:
        return visitor.visitVercelAiSdk();
      case MASTRA:
        return visitor.visitMastra();
      case SMOLAGENTS:
        return visitor.visitSmolagents();
      case OPENAI_AGENTS:
        return visitor.visitOpenaiAgents();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static AgentSnapshotSummaryFramework valueOf(String value) {
    switch (value) {
      case "llamaindex":
        return LLAMAINDEX;
      case "openai-agents-python":
        return OPENAI_AGENTS_PYTHON;
      case "pydantic-ai":
        return PYDANTIC_AI;
      case "google-adk":
        return GOOGLE_ADK;
      case "crewai":
        return CREWAI;
      case "eve":
        return EVE;
      case "langchain":
        return LANGCHAIN;
      case "strands":
        return STRANDS;
      case "salesforce-agentforce":
        return SALESFORCE_AGENTFORCE;
      case "autogen":
        return AUTOGEN;
      case "langchain-python":
        return LANGCHAIN_PYTHON;
      case "vercel-ai-sdk":
        return VERCEL_AI_SDK;
      case "mastra":
        return MASTRA;
      case "smolagents":
        return SMOLAGENTS;
      case "openai-agents":
        return OPENAI_AGENTS;
      default:
        return new AgentSnapshotSummaryFramework(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    VERCEL_AI_SDK,

    OPENAI_AGENTS,

    LANGCHAIN,

    MASTRA,

    LANGCHAIN_PYTHON,

    LLAMAINDEX,

    CREWAI,

    SMOLAGENTS,

    PYDANTIC_AI,

    STRANDS,

    GOOGLE_ADK,

    OPENAI_AGENTS_PYTHON,

    AUTOGEN,

    EVE,

    SALESFORCE_AGENTFORCE,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitVercelAiSdk();

    T visitOpenaiAgents();

    T visitLangchain();

    T visitMastra();

    T visitLangchainPython();

    T visitLlamaindex();

    T visitCrewai();

    T visitSmolagents();

    T visitPydanticAi();

    T visitStrands();

    T visitGoogleAdk();

    T visitOpenaiAgentsPython();

    T visitAutogen();

    T visitEve();

    T visitSalesforceAgentforce();

    T visitUnknown(String unknownType);
  }
}
