/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.chronicle.labs.api.types;

import com.chronicle.labs.api.core.Nullable;
import com.chronicle.labs.api.core.NullableNonemptyFilter;
import com.chronicle.labs.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = AgentSnapshotVersionsItemArtifactProvenance.Builder.class)
public final class AgentSnapshotVersionsItemArtifactProvenance {
    private final Optional<String> aiSdkVersion;

    private final OffsetDateTime createdAt;

    private final Optional<String> dependencyLockHash;

    private final Optional<String> frameworkVersion;

    private final Optional<String> gitSha;

    private final Optional<String> publishedBy;

    private final Map<String, Object> additionalProperties;

    private AgentSnapshotVersionsItemArtifactProvenance(
            Optional<String> aiSdkVersion,
            OffsetDateTime createdAt,
            Optional<String> dependencyLockHash,
            Optional<String> frameworkVersion,
            Optional<String> gitSha,
            Optional<String> publishedBy,
            Map<String, Object> additionalProperties) {
        this.aiSdkVersion = aiSdkVersion;
        this.createdAt = createdAt;
        this.dependencyLockHash = dependencyLockHash;
        this.frameworkVersion = frameworkVersion;
        this.gitSha = gitSha;
        this.publishedBy = publishedBy;
        this.additionalProperties = additionalProperties;
    }

    @JsonIgnore
    public Optional<String> getAiSdkVersion() {
        if (aiSdkVersion == null) {
            return Optional.empty();
        }
        return aiSdkVersion;
    }

    @JsonProperty("createdAt")
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    @JsonIgnore
    public Optional<String> getDependencyLockHash() {
        if (dependencyLockHash == null) {
            return Optional.empty();
        }
        return dependencyLockHash;
    }

    @JsonIgnore
    public Optional<String> getFrameworkVersion() {
        if (frameworkVersion == null) {
            return Optional.empty();
        }
        return frameworkVersion;
    }

    @JsonIgnore
    public Optional<String> getGitSha() {
        if (gitSha == null) {
            return Optional.empty();
        }
        return gitSha;
    }

    @JsonIgnore
    public Optional<String> getPublishedBy() {
        if (publishedBy == null) {
            return Optional.empty();
        }
        return publishedBy;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("aiSdkVersion")
    private Optional<String> _getAiSdkVersion() {
        return aiSdkVersion;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("dependencyLockHash")
    private Optional<String> _getDependencyLockHash() {
        return dependencyLockHash;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("frameworkVersion")
    private Optional<String> _getFrameworkVersion() {
        return frameworkVersion;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("gitSha")
    private Optional<String> _getGitSha() {
        return gitSha;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("publishedBy")
    private Optional<String> _getPublishedBy() {
        return publishedBy;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof AgentSnapshotVersionsItemArtifactProvenance
                && equalTo((AgentSnapshotVersionsItemArtifactProvenance) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(AgentSnapshotVersionsItemArtifactProvenance other) {
        return aiSdkVersion.equals(other.aiSdkVersion)
                && createdAt.equals(other.createdAt)
                && dependencyLockHash.equals(other.dependencyLockHash)
                && frameworkVersion.equals(other.frameworkVersion)
                && gitSha.equals(other.gitSha)
                && publishedBy.equals(other.publishedBy);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.aiSdkVersion,
                this.createdAt,
                this.dependencyLockHash,
                this.frameworkVersion,
                this.gitSha,
                this.publishedBy);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static CreatedAtStage builder() {
        return new Builder();
    }

    public interface CreatedAtStage {
        _FinalStage createdAt(@NotNull OffsetDateTime createdAt);

        Builder from(AgentSnapshotVersionsItemArtifactProvenance other);
    }

    public interface _FinalStage {
        AgentSnapshotVersionsItemArtifactProvenance build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage aiSdkVersion(Optional<String> aiSdkVersion);

        _FinalStage aiSdkVersion(String aiSdkVersion);

        _FinalStage aiSdkVersion(Nullable<String> aiSdkVersion);

        _FinalStage dependencyLockHash(Optional<String> dependencyLockHash);

        _FinalStage dependencyLockHash(String dependencyLockHash);

        _FinalStage dependencyLockHash(Nullable<String> dependencyLockHash);

        _FinalStage frameworkVersion(Optional<String> frameworkVersion);

        _FinalStage frameworkVersion(String frameworkVersion);

        _FinalStage frameworkVersion(Nullable<String> frameworkVersion);

        _FinalStage gitSha(Optional<String> gitSha);

        _FinalStage gitSha(String gitSha);

        _FinalStage gitSha(Nullable<String> gitSha);

        _FinalStage publishedBy(Optional<String> publishedBy);

        _FinalStage publishedBy(String publishedBy);

        _FinalStage publishedBy(Nullable<String> publishedBy);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements CreatedAtStage, _FinalStage {
        private OffsetDateTime createdAt;

        private Optional<String> publishedBy = Optional.empty();

        private Optional<String> gitSha = Optional.empty();

        private Optional<String> frameworkVersion = Optional.empty();

        private Optional<String> dependencyLockHash = Optional.empty();

        private Optional<String> aiSdkVersion = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(AgentSnapshotVersionsItemArtifactProvenance other) {
            aiSdkVersion(other.getAiSdkVersion());
            createdAt(other.getCreatedAt());
            dependencyLockHash(other.getDependencyLockHash());
            frameworkVersion(other.getFrameworkVersion());
            gitSha(other.getGitSha());
            publishedBy(other.getPublishedBy());
            return this;
        }

        @java.lang.Override
        @JsonSetter("createdAt")
        public _FinalStage createdAt(@NotNull OffsetDateTime createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage publishedBy(Nullable<String> publishedBy) {
            if (publishedBy.isNull()) {
                this.publishedBy = null;
            } else if (publishedBy.isEmpty()) {
                this.publishedBy = Optional.empty();
            } else {
                this.publishedBy = Optional.of(publishedBy.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage publishedBy(String publishedBy) {
            this.publishedBy = Optional.ofNullable(publishedBy);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "publishedBy", nulls = Nulls.SKIP)
        public _FinalStage publishedBy(Optional<String> publishedBy) {
            this.publishedBy = publishedBy;
            return this;
        }

        @java.lang.Override
        public _FinalStage gitSha(Nullable<String> gitSha) {
            if (gitSha.isNull()) {
                this.gitSha = null;
            } else if (gitSha.isEmpty()) {
                this.gitSha = Optional.empty();
            } else {
                this.gitSha = Optional.of(gitSha.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage gitSha(String gitSha) {
            this.gitSha = Optional.ofNullable(gitSha);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "gitSha", nulls = Nulls.SKIP)
        public _FinalStage gitSha(Optional<String> gitSha) {
            this.gitSha = gitSha;
            return this;
        }

        @java.lang.Override
        public _FinalStage frameworkVersion(Nullable<String> frameworkVersion) {
            if (frameworkVersion.isNull()) {
                this.frameworkVersion = null;
            } else if (frameworkVersion.isEmpty()) {
                this.frameworkVersion = Optional.empty();
            } else {
                this.frameworkVersion = Optional.of(frameworkVersion.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage frameworkVersion(String frameworkVersion) {
            this.frameworkVersion = Optional.ofNullable(frameworkVersion);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "frameworkVersion", nulls = Nulls.SKIP)
        public _FinalStage frameworkVersion(Optional<String> frameworkVersion) {
            this.frameworkVersion = frameworkVersion;
            return this;
        }

        @java.lang.Override
        public _FinalStage dependencyLockHash(Nullable<String> dependencyLockHash) {
            if (dependencyLockHash.isNull()) {
                this.dependencyLockHash = null;
            } else if (dependencyLockHash.isEmpty()) {
                this.dependencyLockHash = Optional.empty();
            } else {
                this.dependencyLockHash = Optional.of(dependencyLockHash.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage dependencyLockHash(String dependencyLockHash) {
            this.dependencyLockHash = Optional.ofNullable(dependencyLockHash);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "dependencyLockHash", nulls = Nulls.SKIP)
        public _FinalStage dependencyLockHash(Optional<String> dependencyLockHash) {
            this.dependencyLockHash = dependencyLockHash;
            return this;
        }

        @java.lang.Override
        public _FinalStage aiSdkVersion(Nullable<String> aiSdkVersion) {
            if (aiSdkVersion.isNull()) {
                this.aiSdkVersion = null;
            } else if (aiSdkVersion.isEmpty()) {
                this.aiSdkVersion = Optional.empty();
            } else {
                this.aiSdkVersion = Optional.of(aiSdkVersion.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage aiSdkVersion(String aiSdkVersion) {
            this.aiSdkVersion = Optional.ofNullable(aiSdkVersion);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "aiSdkVersion", nulls = Nulls.SKIP)
        public _FinalStage aiSdkVersion(Optional<String> aiSdkVersion) {
            this.aiSdkVersion = aiSdkVersion;
            return this;
        }

        @java.lang.Override
        public AgentSnapshotVersionsItemArtifactProvenance build() {
            return new AgentSnapshotVersionsItemArtifactProvenance(
                    aiSdkVersion,
                    createdAt,
                    dependencyLockHash,
                    frameworkVersion,
                    gitSha,
                    publishedBy,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
