/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.chronicle.labs.api.types;

import com.chronicle.labs.api.core.Nullable;
import com.chronicle.labs.api.core.NullableNonemptyFilter;
import com.chronicle.labs.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Integer;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = AgentSnapshotRunsItemResponseUsage.Builder.class
)
public final class AgentSnapshotRunsItemResponseUsage {
  private final Optional<Integer> cachedInputTokens;

  private final Optional<Integer> inputTokens;

  private final Optional<Integer> outputTokens;

  private final Optional<Integer> reasoningTokens;

  private final Optional<Integer> totalTokens;

  private final Map<String, Object> additionalProperties;

  private AgentSnapshotRunsItemResponseUsage(Optional<Integer> cachedInputTokens,
      Optional<Integer> inputTokens, Optional<Integer> outputTokens,
      Optional<Integer> reasoningTokens, Optional<Integer> totalTokens,
      Map<String, Object> additionalProperties) {
    this.cachedInputTokens = cachedInputTokens;
    this.inputTokens = inputTokens;
    this.outputTokens = outputTokens;
    this.reasoningTokens = reasoningTokens;
    this.totalTokens = totalTokens;
    this.additionalProperties = additionalProperties;
  }

  @JsonIgnore
  public Optional<Integer> getCachedInputTokens() {
    if (cachedInputTokens == null) {
      return Optional.empty();
    }
    return cachedInputTokens;
  }

  @JsonIgnore
  public Optional<Integer> getInputTokens() {
    if (inputTokens == null) {
      return Optional.empty();
    }
    return inputTokens;
  }

  @JsonIgnore
  public Optional<Integer> getOutputTokens() {
    if (outputTokens == null) {
      return Optional.empty();
    }
    return outputTokens;
  }

  @JsonIgnore
  public Optional<Integer> getReasoningTokens() {
    if (reasoningTokens == null) {
      return Optional.empty();
    }
    return reasoningTokens;
  }

  @JsonIgnore
  public Optional<Integer> getTotalTokens() {
    if (totalTokens == null) {
      return Optional.empty();
    }
    return totalTokens;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("cachedInputTokens")
  private Optional<Integer> _getCachedInputTokens() {
    return cachedInputTokens;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("inputTokens")
  private Optional<Integer> _getInputTokens() {
    return inputTokens;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("outputTokens")
  private Optional<Integer> _getOutputTokens() {
    return outputTokens;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("reasoningTokens")
  private Optional<Integer> _getReasoningTokens() {
    return reasoningTokens;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("totalTokens")
  private Optional<Integer> _getTotalTokens() {
    return totalTokens;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof AgentSnapshotRunsItemResponseUsage && equalTo((AgentSnapshotRunsItemResponseUsage) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(AgentSnapshotRunsItemResponseUsage other) {
    return cachedInputTokens.equals(other.cachedInputTokens) && inputTokens.equals(other.inputTokens) && outputTokens.equals(other.outputTokens) && reasoningTokens.equals(other.reasoningTokens) && totalTokens.equals(other.totalTokens);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.cachedInputTokens, this.inputTokens, this.outputTokens, this.reasoningTokens, this.totalTokens);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<Integer> cachedInputTokens = Optional.empty();

    private Optional<Integer> inputTokens = Optional.empty();

    private Optional<Integer> outputTokens = Optional.empty();

    private Optional<Integer> reasoningTokens = Optional.empty();

    private Optional<Integer> totalTokens = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(AgentSnapshotRunsItemResponseUsage other) {
      cachedInputTokens(other.getCachedInputTokens());
      inputTokens(other.getInputTokens());
      outputTokens(other.getOutputTokens());
      reasoningTokens(other.getReasoningTokens());
      totalTokens(other.getTotalTokens());
      return this;
    }

    @JsonSetter(
        value = "cachedInputTokens",
        nulls = Nulls.SKIP
    )
    public Builder cachedInputTokens(Optional<Integer> cachedInputTokens) {
      this.cachedInputTokens = cachedInputTokens;
      return this;
    }

    public Builder cachedInputTokens(Integer cachedInputTokens) {
      this.cachedInputTokens = Optional.ofNullable(cachedInputTokens);
      return this;
    }

    public Builder cachedInputTokens(Nullable<Integer> cachedInputTokens) {
      if (cachedInputTokens.isNull()) {
        this.cachedInputTokens = null;
      }
      else if (cachedInputTokens.isEmpty()) {
        this.cachedInputTokens = Optional.empty();
      }
      else {
        this.cachedInputTokens = Optional.of(cachedInputTokens.get());
      }
      return this;
    }

    @JsonSetter(
        value = "inputTokens",
        nulls = Nulls.SKIP
    )
    public Builder inputTokens(Optional<Integer> inputTokens) {
      this.inputTokens = inputTokens;
      return this;
    }

    public Builder inputTokens(Integer inputTokens) {
      this.inputTokens = Optional.ofNullable(inputTokens);
      return this;
    }

    public Builder inputTokens(Nullable<Integer> inputTokens) {
      if (inputTokens.isNull()) {
        this.inputTokens = null;
      }
      else if (inputTokens.isEmpty()) {
        this.inputTokens = Optional.empty();
      }
      else {
        this.inputTokens = Optional.of(inputTokens.get());
      }
      return this;
    }

    @JsonSetter(
        value = "outputTokens",
        nulls = Nulls.SKIP
    )
    public Builder outputTokens(Optional<Integer> outputTokens) {
      this.outputTokens = outputTokens;
      return this;
    }

    public Builder outputTokens(Integer outputTokens) {
      this.outputTokens = Optional.ofNullable(outputTokens);
      return this;
    }

    public Builder outputTokens(Nullable<Integer> outputTokens) {
      if (outputTokens.isNull()) {
        this.outputTokens = null;
      }
      else if (outputTokens.isEmpty()) {
        this.outputTokens = Optional.empty();
      }
      else {
        this.outputTokens = Optional.of(outputTokens.get());
      }
      return this;
    }

    @JsonSetter(
        value = "reasoningTokens",
        nulls = Nulls.SKIP
    )
    public Builder reasoningTokens(Optional<Integer> reasoningTokens) {
      this.reasoningTokens = reasoningTokens;
      return this;
    }

    public Builder reasoningTokens(Integer reasoningTokens) {
      this.reasoningTokens = Optional.ofNullable(reasoningTokens);
      return this;
    }

    public Builder reasoningTokens(Nullable<Integer> reasoningTokens) {
      if (reasoningTokens.isNull()) {
        this.reasoningTokens = null;
      }
      else if (reasoningTokens.isEmpty()) {
        this.reasoningTokens = Optional.empty();
      }
      else {
        this.reasoningTokens = Optional.of(reasoningTokens.get());
      }
      return this;
    }

    @JsonSetter(
        value = "totalTokens",
        nulls = Nulls.SKIP
    )
    public Builder totalTokens(Optional<Integer> totalTokens) {
      this.totalTokens = totalTokens;
      return this;
    }

    public Builder totalTokens(Integer totalTokens) {
      this.totalTokens = Optional.ofNullable(totalTokens);
      return this;
    }

    public Builder totalTokens(Nullable<Integer> totalTokens) {
      if (totalTokens.isNull()) {
        this.totalTokens = null;
      }
      else if (totalTokens.isEmpty()) {
        this.totalTokens = Optional.empty();
      }
      else {
        this.totalTokens = Optional.of(totalTokens.get());
      }
      return this;
    }

    public AgentSnapshotRunsItemResponseUsage build() {
      return new AgentSnapshotRunsItemResponseUsage(cachedInputTokens, inputTokens, outputTokens, reasoningTokens, totalTokens, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
