/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.chronicle.labs.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class AgentSnapshotRunsItemStatus {
  public static final AgentSnapshotRunsItemStatus SUCCESS = new AgentSnapshotRunsItemStatus(Value.SUCCESS, "success");

  public static final AgentSnapshotRunsItemStatus ERROR = new AgentSnapshotRunsItemStatus(Value.ERROR, "error");

  public static final AgentSnapshotRunsItemStatus STARTED = new AgentSnapshotRunsItemStatus(Value.STARTED, "started");

  private final Value value;

  private final String string;

  AgentSnapshotRunsItemStatus(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof AgentSnapshotRunsItemStatus && this.string.equals(((AgentSnapshotRunsItemStatus) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case SUCCESS:
        return visitor.visitSuccess();
      case ERROR:
        return visitor.visitError();
      case STARTED:
        return visitor.visitStarted();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static AgentSnapshotRunsItemStatus valueOf(String value) {
    switch (value) {
      case "success":
        return SUCCESS;
      case "error":
        return ERROR;
      case "started":
        return STARTED;
      default:
        return new AgentSnapshotRunsItemStatus(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    STARTED,

    SUCCESS,

    ERROR,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitStarted();

    T visitSuccess();

    T visitError();

    T visitUnknown(String unknownType);
  }
}
