/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.chronicle.labs.api.types;

import com.chronicle.labs.api.core.Nullable;
import com.chronicle.labs.api.core.NullableNonemptyFilter;
import com.chronicle.labs.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = AgentVersionSummaryArtifactKnowledgeSourcesItem.Builder.class
)
public final class AgentVersionSummaryArtifactKnowledgeSourcesItem {
  private final Optional<String> href;

  private final String id;

  private final AgentVersionSummaryArtifactKnowledgeSourcesItemKind kind;

  private final String label;

  private final Optional<String> sizeLabel;

  private final Map<String, Object> additionalProperties;

  private AgentVersionSummaryArtifactKnowledgeSourcesItem(Optional<String> href, String id,
      AgentVersionSummaryArtifactKnowledgeSourcesItemKind kind, String label,
      Optional<String> sizeLabel, Map<String, Object> additionalProperties) {
    this.href = href;
    this.id = id;
    this.kind = kind;
    this.label = label;
    this.sizeLabel = sizeLabel;
    this.additionalProperties = additionalProperties;
  }

  /**
   * @return Optional jump-out link.
   */
  @JsonIgnore
  public Optional<String> getHref() {
    if (href == null) {
      return Optional.empty();
    }
    return href;
  }

  @JsonProperty("id")
  public String getId() {
    return id;
  }

  @JsonProperty("kind")
  public AgentVersionSummaryArtifactKnowledgeSourcesItemKind getKind() {
    return kind;
  }

  @JsonProperty("label")
  public String getLabel() {
    return label;
  }

  /**
   * @return Optional human-readable size hint, e.g. &quot;12.4k docs&quot;.
   */
  @JsonIgnore
  public Optional<String> getSizeLabel() {
    if (sizeLabel == null) {
      return Optional.empty();
    }
    return sizeLabel;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("href")
  private Optional<String> _getHref() {
    return href;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("sizeLabel")
  private Optional<String> _getSizeLabel() {
    return sizeLabel;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof AgentVersionSummaryArtifactKnowledgeSourcesItem && equalTo((AgentVersionSummaryArtifactKnowledgeSourcesItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(AgentVersionSummaryArtifactKnowledgeSourcesItem other) {
    return href.equals(other.href) && id.equals(other.id) && kind.equals(other.kind) && label.equals(other.label) && sizeLabel.equals(other.sizeLabel);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.href, this.id, this.kind, this.label, this.sizeLabel);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static IdStage builder() {
    return new Builder();
  }

  public interface IdStage {
    KindStage id(@NotNull String id);

    Builder from(AgentVersionSummaryArtifactKnowledgeSourcesItem other);
  }

  public interface KindStage {
    LabelStage kind(@NotNull AgentVersionSummaryArtifactKnowledgeSourcesItemKind kind);
  }

  public interface LabelStage {
    _FinalStage label(@NotNull String label);
  }

  public interface _FinalStage {
    AgentVersionSummaryArtifactKnowledgeSourcesItem build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    /**
     * <p>Optional jump-out link.</p>
     */
    _FinalStage href(Optional<String> href);

    _FinalStage href(String href);

    _FinalStage href(Nullable<String> href);

    /**
     * <p>Optional human-readable size hint, e.g. &quot;12.4k docs&quot;.</p>
     */
    _FinalStage sizeLabel(Optional<String> sizeLabel);

    _FinalStage sizeLabel(String sizeLabel);

    _FinalStage sizeLabel(Nullable<String> sizeLabel);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements IdStage, KindStage, LabelStage, _FinalStage {
    private String id;

    private AgentVersionSummaryArtifactKnowledgeSourcesItemKind kind;

    private String label;

    private Optional<String> sizeLabel = Optional.empty();

    private Optional<String> href = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(AgentVersionSummaryArtifactKnowledgeSourcesItem other) {
      href(other.getHref());
      id(other.getId());
      kind(other.getKind());
      label(other.getLabel());
      sizeLabel(other.getSizeLabel());
      return this;
    }

    @java.lang.Override
    @JsonSetter("id")
    public KindStage id(@NotNull String id) {
      this.id = Objects.requireNonNull(id, "id must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("kind")
    public LabelStage kind(@NotNull AgentVersionSummaryArtifactKnowledgeSourcesItemKind kind) {
      this.kind = Objects.requireNonNull(kind, "kind must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("label")
    public _FinalStage label(@NotNull String label) {
      this.label = Objects.requireNonNull(label, "label must not be null");
      return this;
    }

    /**
     * <p>Optional human-readable size hint, e.g. &quot;12.4k docs&quot;.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage sizeLabel(Nullable<String> sizeLabel) {
      if (sizeLabel.isNull()) {
        this.sizeLabel = null;
      }
      else if (sizeLabel.isEmpty()) {
        this.sizeLabel = Optional.empty();
      }
      else {
        this.sizeLabel = Optional.of(sizeLabel.get());
      }
      return this;
    }

    /**
     * <p>Optional human-readable size hint, e.g. &quot;12.4k docs&quot;.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage sizeLabel(String sizeLabel) {
      this.sizeLabel = Optional.ofNullable(sizeLabel);
      return this;
    }

    /**
     * <p>Optional human-readable size hint, e.g. &quot;12.4k docs&quot;.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "sizeLabel",
        nulls = Nulls.SKIP
    )
    public _FinalStage sizeLabel(Optional<String> sizeLabel) {
      this.sizeLabel = sizeLabel;
      return this;
    }

    /**
     * <p>Optional jump-out link.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage href(Nullable<String> href) {
      if (href.isNull()) {
        this.href = null;
      }
      else if (href.isEmpty()) {
        this.href = Optional.empty();
      }
      else {
        this.href = Optional.of(href.get());
      }
      return this;
    }

    /**
     * <p>Optional jump-out link.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage href(String href) {
      this.href = Optional.ofNullable(href);
      return this;
    }

    /**
     * <p>Optional jump-out link.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "href",
        nulls = Nulls.SKIP
    )
    public _FinalStage href(Optional<String> href) {
      this.href = href;
      return this;
    }

    @java.lang.Override
    public AgentVersionSummaryArtifactKnowledgeSourcesItem build() {
      return new AgentVersionSummaryArtifactKnowledgeSourcesItem(href, id, kind, label, sizeLabel, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
