/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.chronicle.labs.api.types;

import com.chronicle.labs.api.core.Nullable;
import com.chronicle.labs.api.core.NullableNonemptyFilter;
import com.chronicle.labs.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = BacktestsAvailabilityDatasetSnapshotsValueTasksItemVerifiersItemJudge.Builder.class)
public final class BacktestsAvailabilityDatasetSnapshotsValueTasksItemVerifiersItemJudge {
    private final Optional<Boolean> allowSkip;

    private final Optional<List<BacktestsAvailabilityDatasetSnapshotsValueTasksItemVerifiersItemJudgeChoiceScoresItem>>
            choiceScores;

    private final Optional<String> model;

    private final Optional<Boolean> useCot;

    private final Map<String, Object> additionalProperties;

    private BacktestsAvailabilityDatasetSnapshotsValueTasksItemVerifiersItemJudge(
            Optional<Boolean> allowSkip,
            Optional<List<BacktestsAvailabilityDatasetSnapshotsValueTasksItemVerifiersItemJudgeChoiceScoresItem>>
                    choiceScores,
            Optional<String> model,
            Optional<Boolean> useCot,
            Map<String, Object> additionalProperties) {
        this.allowSkip = allowSkip;
        this.choiceScores = choiceScores;
        this.model = model;
        this.useCot = useCot;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Allow the judge to decline non-applicable cases; skipped cases emit no reward key instead of scoring 0.
     */
    @JsonProperty("allowSkip")
    public Optional<Boolean> getAllowSkip() {
        return allowSkip;
    }

    /**
     * @return Choice→score mapping. Non-empty forces the judge to pick one choice; the mapped score is the result.
     */
    @JsonProperty("choiceScores")
    public Optional<List<BacktestsAvailabilityDatasetSnapshotsValueTasksItemVerifiersItemJudgeChoiceScoresItem>>
            getChoiceScores() {
        return choiceScores;
    }

    /**
     * @return Judge model override; <code>None</code> uses the server default.
     */
    @JsonIgnore
    public Optional<String> getModel() {
        if (model == null) {
            return Optional.empty();
        }
        return model;
    }

    /**
     * @return Ask the judge to reason step-by-step before answering.
     */
    @JsonProperty("useCot")
    public Optional<Boolean> getUseCot() {
        return useCot;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("model")
    private Optional<String> _getModel() {
        return model;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof BacktestsAvailabilityDatasetSnapshotsValueTasksItemVerifiersItemJudge
                && equalTo((BacktestsAvailabilityDatasetSnapshotsValueTasksItemVerifiersItemJudge) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(BacktestsAvailabilityDatasetSnapshotsValueTasksItemVerifiersItemJudge other) {
        return allowSkip.equals(other.allowSkip)
                && choiceScores.equals(other.choiceScores)
                && model.equals(other.model)
                && useCot.equals(other.useCot);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.allowSkip, this.choiceScores, this.model, this.useCot);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private Optional<Boolean> allowSkip = Optional.empty();

        private Optional<List<BacktestsAvailabilityDatasetSnapshotsValueTasksItemVerifiersItemJudgeChoiceScoresItem>>
                choiceScores = Optional.empty();

        private Optional<String> model = Optional.empty();

        private Optional<Boolean> useCot = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(BacktestsAvailabilityDatasetSnapshotsValueTasksItemVerifiersItemJudge other) {
            allowSkip(other.getAllowSkip());
            choiceScores(other.getChoiceScores());
            model(other.getModel());
            useCot(other.getUseCot());
            return this;
        }

        /**
         * <p>Allow the judge to decline non-applicable cases; skipped cases emit no reward key instead of scoring 0.</p>
         */
        @JsonSetter(value = "allowSkip", nulls = Nulls.SKIP)
        public Builder allowSkip(Optional<Boolean> allowSkip) {
            this.allowSkip = allowSkip;
            return this;
        }

        public Builder allowSkip(Boolean allowSkip) {
            this.allowSkip = Optional.ofNullable(allowSkip);
            return this;
        }

        /**
         * <p>Choice→score mapping. Non-empty forces the judge to pick one choice; the mapped score is the result.</p>
         */
        @JsonSetter(value = "choiceScores", nulls = Nulls.SKIP)
        public Builder choiceScores(
                Optional<List<BacktestsAvailabilityDatasetSnapshotsValueTasksItemVerifiersItemJudgeChoiceScoresItem>>
                        choiceScores) {
            this.choiceScores = choiceScores;
            return this;
        }

        public Builder choiceScores(
                List<BacktestsAvailabilityDatasetSnapshotsValueTasksItemVerifiersItemJudgeChoiceScoresItem>
                        choiceScores) {
            this.choiceScores = Optional.ofNullable(choiceScores);
            return this;
        }

        /**
         * <p>Judge model override; <code>None</code> uses the server default.</p>
         */
        @JsonSetter(value = "model", nulls = Nulls.SKIP)
        public Builder model(Optional<String> model) {
            this.model = model;
            return this;
        }

        public Builder model(String model) {
            this.model = Optional.ofNullable(model);
            return this;
        }

        public Builder model(Nullable<String> model) {
            if (model.isNull()) {
                this.model = null;
            } else if (model.isEmpty()) {
                this.model = Optional.empty();
            } else {
                this.model = Optional.of(model.get());
            }
            return this;
        }

        /**
         * <p>Ask the judge to reason step-by-step before answering.</p>
         */
        @JsonSetter(value = "useCot", nulls = Nulls.SKIP)
        public Builder useCot(Optional<Boolean> useCot) {
            this.useCot = useCot;
            return this;
        }

        public Builder useCot(Boolean useCot) {
            this.useCot = Optional.ofNullable(useCot);
            return this;
        }

        public BacktestsAvailabilityDatasetSnapshotsValueTasksItemVerifiersItemJudge build() {
            return new BacktestsAvailabilityDatasetSnapshotsValueTasksItemVerifiersItemJudge(
                    allowSkip, choiceScores, model, useCot, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
