/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.chronicle.labs.api.types;

import com.chronicle.labs.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = BacktestTrialDetailResponseTrialException.Builder.class
)
public final class BacktestTrialDetailResponseTrialException {
  private final String kind;

  private final String message;

  private final Map<String, Object> additionalProperties;

  private BacktestTrialDetailResponseTrialException(String kind, String message,
      Map<String, Object> additionalProperties) {
    this.kind = kind;
    this.message = message;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("kind")
  public String getKind() {
    return kind;
  }

  @JsonProperty("message")
  public String getMessage() {
    return message;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof BacktestTrialDetailResponseTrialException && equalTo((BacktestTrialDetailResponseTrialException) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(BacktestTrialDetailResponseTrialException other) {
    return kind.equals(other.kind) && message.equals(other.message);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.kind, this.message);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static KindStage builder() {
    return new Builder();
  }

  public interface KindStage {
    MessageStage kind(@NotNull String kind);

    Builder from(BacktestTrialDetailResponseTrialException other);
  }

  public interface MessageStage {
    _FinalStage message(@NotNull String message);
  }

  public interface _FinalStage {
    BacktestTrialDetailResponseTrialException build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements KindStage, MessageStage, _FinalStage {
    private String kind;

    private String message;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(BacktestTrialDetailResponseTrialException other) {
      kind(other.getKind());
      message(other.getMessage());
      return this;
    }

    @java.lang.Override
    @JsonSetter("kind")
    public MessageStage kind(@NotNull String kind) {
      this.kind = Objects.requireNonNull(kind, "kind must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("message")
    public _FinalStage message(@NotNull String message) {
      this.message = Objects.requireNonNull(message, "message must not be null");
      return this;
    }

    @java.lang.Override
    public BacktestTrialDetailResponseTrialException build() {
      return new BacktestTrialDetailResponseTrialException(kind, message, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
