/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.chronicle.labs.api.types;

import com.chronicle.labs.api.core.Nullable;
import com.chronicle.labs.api.core.NullableNonemptyFilter;
import com.chronicle.labs.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = BacktestTrialDetailResponseTrialTimings.Builder.class
)
public final class BacktestTrialDetailResponseTrialTimings {
  private final Optional<OffsetDateTime> agentRunFinishedAt;

  private final Optional<OffsetDateTime> agentRunStartedAt;

  private final Optional<OffsetDateTime> agentSetupFinishedAt;

  private final Optional<OffsetDateTime> agentSetupStartedAt;

  private final Optional<OffsetDateTime> envSetupFinishedAt;

  private final Optional<OffsetDateTime> envSetupStartedAt;

  private final Optional<OffsetDateTime> verifierFinishedAt;

  private final Optional<OffsetDateTime> verifierStartedAt;

  private final Map<String, Object> additionalProperties;

  private BacktestTrialDetailResponseTrialTimings(Optional<OffsetDateTime> agentRunFinishedAt,
      Optional<OffsetDateTime> agentRunStartedAt, Optional<OffsetDateTime> agentSetupFinishedAt,
      Optional<OffsetDateTime> agentSetupStartedAt, Optional<OffsetDateTime> envSetupFinishedAt,
      Optional<OffsetDateTime> envSetupStartedAt, Optional<OffsetDateTime> verifierFinishedAt,
      Optional<OffsetDateTime> verifierStartedAt, Map<String, Object> additionalProperties) {
    this.agentRunFinishedAt = agentRunFinishedAt;
    this.agentRunStartedAt = agentRunStartedAt;
    this.agentSetupFinishedAt = agentSetupFinishedAt;
    this.agentSetupStartedAt = agentSetupStartedAt;
    this.envSetupFinishedAt = envSetupFinishedAt;
    this.envSetupStartedAt = envSetupStartedAt;
    this.verifierFinishedAt = verifierFinishedAt;
    this.verifierStartedAt = verifierStartedAt;
    this.additionalProperties = additionalProperties;
  }

  @JsonIgnore
  public Optional<OffsetDateTime> getAgentRunFinishedAt() {
    if (agentRunFinishedAt == null) {
      return Optional.empty();
    }
    return agentRunFinishedAt;
  }

  @JsonIgnore
  public Optional<OffsetDateTime> getAgentRunStartedAt() {
    if (agentRunStartedAt == null) {
      return Optional.empty();
    }
    return agentRunStartedAt;
  }

  @JsonIgnore
  public Optional<OffsetDateTime> getAgentSetupFinishedAt() {
    if (agentSetupFinishedAt == null) {
      return Optional.empty();
    }
    return agentSetupFinishedAt;
  }

  @JsonIgnore
  public Optional<OffsetDateTime> getAgentSetupStartedAt() {
    if (agentSetupStartedAt == null) {
      return Optional.empty();
    }
    return agentSetupStartedAt;
  }

  @JsonIgnore
  public Optional<OffsetDateTime> getEnvSetupFinishedAt() {
    if (envSetupFinishedAt == null) {
      return Optional.empty();
    }
    return envSetupFinishedAt;
  }

  @JsonIgnore
  public Optional<OffsetDateTime> getEnvSetupStartedAt() {
    if (envSetupStartedAt == null) {
      return Optional.empty();
    }
    return envSetupStartedAt;
  }

  @JsonIgnore
  public Optional<OffsetDateTime> getVerifierFinishedAt() {
    if (verifierFinishedAt == null) {
      return Optional.empty();
    }
    return verifierFinishedAt;
  }

  @JsonIgnore
  public Optional<OffsetDateTime> getVerifierStartedAt() {
    if (verifierStartedAt == null) {
      return Optional.empty();
    }
    return verifierStartedAt;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("agentRunFinishedAt")
  private Optional<OffsetDateTime> _getAgentRunFinishedAt() {
    return agentRunFinishedAt;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("agentRunStartedAt")
  private Optional<OffsetDateTime> _getAgentRunStartedAt() {
    return agentRunStartedAt;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("agentSetupFinishedAt")
  private Optional<OffsetDateTime> _getAgentSetupFinishedAt() {
    return agentSetupFinishedAt;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("agentSetupStartedAt")
  private Optional<OffsetDateTime> _getAgentSetupStartedAt() {
    return agentSetupStartedAt;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("envSetupFinishedAt")
  private Optional<OffsetDateTime> _getEnvSetupFinishedAt() {
    return envSetupFinishedAt;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("envSetupStartedAt")
  private Optional<OffsetDateTime> _getEnvSetupStartedAt() {
    return envSetupStartedAt;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("verifierFinishedAt")
  private Optional<OffsetDateTime> _getVerifierFinishedAt() {
    return verifierFinishedAt;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("verifierStartedAt")
  private Optional<OffsetDateTime> _getVerifierStartedAt() {
    return verifierStartedAt;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof BacktestTrialDetailResponseTrialTimings && equalTo((BacktestTrialDetailResponseTrialTimings) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(BacktestTrialDetailResponseTrialTimings other) {
    return agentRunFinishedAt.equals(other.agentRunFinishedAt) && agentRunStartedAt.equals(other.agentRunStartedAt) && agentSetupFinishedAt.equals(other.agentSetupFinishedAt) && agentSetupStartedAt.equals(other.agentSetupStartedAt) && envSetupFinishedAt.equals(other.envSetupFinishedAt) && envSetupStartedAt.equals(other.envSetupStartedAt) && verifierFinishedAt.equals(other.verifierFinishedAt) && verifierStartedAt.equals(other.verifierStartedAt);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.agentRunFinishedAt, this.agentRunStartedAt, this.agentSetupFinishedAt, this.agentSetupStartedAt, this.envSetupFinishedAt, this.envSetupStartedAt, this.verifierFinishedAt, this.verifierStartedAt);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<OffsetDateTime> agentRunFinishedAt = Optional.empty();

    private Optional<OffsetDateTime> agentRunStartedAt = Optional.empty();

    private Optional<OffsetDateTime> agentSetupFinishedAt = Optional.empty();

    private Optional<OffsetDateTime> agentSetupStartedAt = Optional.empty();

    private Optional<OffsetDateTime> envSetupFinishedAt = Optional.empty();

    private Optional<OffsetDateTime> envSetupStartedAt = Optional.empty();

    private Optional<OffsetDateTime> verifierFinishedAt = Optional.empty();

    private Optional<OffsetDateTime> verifierStartedAt = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(BacktestTrialDetailResponseTrialTimings other) {
      agentRunFinishedAt(other.getAgentRunFinishedAt());
      agentRunStartedAt(other.getAgentRunStartedAt());
      agentSetupFinishedAt(other.getAgentSetupFinishedAt());
      agentSetupStartedAt(other.getAgentSetupStartedAt());
      envSetupFinishedAt(other.getEnvSetupFinishedAt());
      envSetupStartedAt(other.getEnvSetupStartedAt());
      verifierFinishedAt(other.getVerifierFinishedAt());
      verifierStartedAt(other.getVerifierStartedAt());
      return this;
    }

    @JsonSetter(
        value = "agentRunFinishedAt",
        nulls = Nulls.SKIP
    )
    public Builder agentRunFinishedAt(Optional<OffsetDateTime> agentRunFinishedAt) {
      this.agentRunFinishedAt = agentRunFinishedAt;
      return this;
    }

    public Builder agentRunFinishedAt(OffsetDateTime agentRunFinishedAt) {
      this.agentRunFinishedAt = Optional.ofNullable(agentRunFinishedAt);
      return this;
    }

    public Builder agentRunFinishedAt(Nullable<OffsetDateTime> agentRunFinishedAt) {
      if (agentRunFinishedAt.isNull()) {
        this.agentRunFinishedAt = null;
      }
      else if (agentRunFinishedAt.isEmpty()) {
        this.agentRunFinishedAt = Optional.empty();
      }
      else {
        this.agentRunFinishedAt = Optional.of(agentRunFinishedAt.get());
      }
      return this;
    }

    @JsonSetter(
        value = "agentRunStartedAt",
        nulls = Nulls.SKIP
    )
    public Builder agentRunStartedAt(Optional<OffsetDateTime> agentRunStartedAt) {
      this.agentRunStartedAt = agentRunStartedAt;
      return this;
    }

    public Builder agentRunStartedAt(OffsetDateTime agentRunStartedAt) {
      this.agentRunStartedAt = Optional.ofNullable(agentRunStartedAt);
      return this;
    }

    public Builder agentRunStartedAt(Nullable<OffsetDateTime> agentRunStartedAt) {
      if (agentRunStartedAt.isNull()) {
        this.agentRunStartedAt = null;
      }
      else if (agentRunStartedAt.isEmpty()) {
        this.agentRunStartedAt = Optional.empty();
      }
      else {
        this.agentRunStartedAt = Optional.of(agentRunStartedAt.get());
      }
      return this;
    }

    @JsonSetter(
        value = "agentSetupFinishedAt",
        nulls = Nulls.SKIP
    )
    public Builder agentSetupFinishedAt(Optional<OffsetDateTime> agentSetupFinishedAt) {
      this.agentSetupFinishedAt = agentSetupFinishedAt;
      return this;
    }

    public Builder agentSetupFinishedAt(OffsetDateTime agentSetupFinishedAt) {
      this.agentSetupFinishedAt = Optional.ofNullable(agentSetupFinishedAt);
      return this;
    }

    public Builder agentSetupFinishedAt(Nullable<OffsetDateTime> agentSetupFinishedAt) {
      if (agentSetupFinishedAt.isNull()) {
        this.agentSetupFinishedAt = null;
      }
      else if (agentSetupFinishedAt.isEmpty()) {
        this.agentSetupFinishedAt = Optional.empty();
      }
      else {
        this.agentSetupFinishedAt = Optional.of(agentSetupFinishedAt.get());
      }
      return this;
    }

    @JsonSetter(
        value = "agentSetupStartedAt",
        nulls = Nulls.SKIP
    )
    public Builder agentSetupStartedAt(Optional<OffsetDateTime> agentSetupStartedAt) {
      this.agentSetupStartedAt = agentSetupStartedAt;
      return this;
    }

    public Builder agentSetupStartedAt(OffsetDateTime agentSetupStartedAt) {
      this.agentSetupStartedAt = Optional.ofNullable(agentSetupStartedAt);
      return this;
    }

    public Builder agentSetupStartedAt(Nullable<OffsetDateTime> agentSetupStartedAt) {
      if (agentSetupStartedAt.isNull()) {
        this.agentSetupStartedAt = null;
      }
      else if (agentSetupStartedAt.isEmpty()) {
        this.agentSetupStartedAt = Optional.empty();
      }
      else {
        this.agentSetupStartedAt = Optional.of(agentSetupStartedAt.get());
      }
      return this;
    }

    @JsonSetter(
        value = "envSetupFinishedAt",
        nulls = Nulls.SKIP
    )
    public Builder envSetupFinishedAt(Optional<OffsetDateTime> envSetupFinishedAt) {
      this.envSetupFinishedAt = envSetupFinishedAt;
      return this;
    }

    public Builder envSetupFinishedAt(OffsetDateTime envSetupFinishedAt) {
      this.envSetupFinishedAt = Optional.ofNullable(envSetupFinishedAt);
      return this;
    }

    public Builder envSetupFinishedAt(Nullable<OffsetDateTime> envSetupFinishedAt) {
      if (envSetupFinishedAt.isNull()) {
        this.envSetupFinishedAt = null;
      }
      else if (envSetupFinishedAt.isEmpty()) {
        this.envSetupFinishedAt = Optional.empty();
      }
      else {
        this.envSetupFinishedAt = Optional.of(envSetupFinishedAt.get());
      }
      return this;
    }

    @JsonSetter(
        value = "envSetupStartedAt",
        nulls = Nulls.SKIP
    )
    public Builder envSetupStartedAt(Optional<OffsetDateTime> envSetupStartedAt) {
      this.envSetupStartedAt = envSetupStartedAt;
      return this;
    }

    public Builder envSetupStartedAt(OffsetDateTime envSetupStartedAt) {
      this.envSetupStartedAt = Optional.ofNullable(envSetupStartedAt);
      return this;
    }

    public Builder envSetupStartedAt(Nullable<OffsetDateTime> envSetupStartedAt) {
      if (envSetupStartedAt.isNull()) {
        this.envSetupStartedAt = null;
      }
      else if (envSetupStartedAt.isEmpty()) {
        this.envSetupStartedAt = Optional.empty();
      }
      else {
        this.envSetupStartedAt = Optional.of(envSetupStartedAt.get());
      }
      return this;
    }

    @JsonSetter(
        value = "verifierFinishedAt",
        nulls = Nulls.SKIP
    )
    public Builder verifierFinishedAt(Optional<OffsetDateTime> verifierFinishedAt) {
      this.verifierFinishedAt = verifierFinishedAt;
      return this;
    }

    public Builder verifierFinishedAt(OffsetDateTime verifierFinishedAt) {
      this.verifierFinishedAt = Optional.ofNullable(verifierFinishedAt);
      return this;
    }

    public Builder verifierFinishedAt(Nullable<OffsetDateTime> verifierFinishedAt) {
      if (verifierFinishedAt.isNull()) {
        this.verifierFinishedAt = null;
      }
      else if (verifierFinishedAt.isEmpty()) {
        this.verifierFinishedAt = Optional.empty();
      }
      else {
        this.verifierFinishedAt = Optional.of(verifierFinishedAt.get());
      }
      return this;
    }

    @JsonSetter(
        value = "verifierStartedAt",
        nulls = Nulls.SKIP
    )
    public Builder verifierStartedAt(Optional<OffsetDateTime> verifierStartedAt) {
      this.verifierStartedAt = verifierStartedAt;
      return this;
    }

    public Builder verifierStartedAt(OffsetDateTime verifierStartedAt) {
      this.verifierStartedAt = Optional.ofNullable(verifierStartedAt);
      return this;
    }

    public Builder verifierStartedAt(Nullable<OffsetDateTime> verifierStartedAt) {
      if (verifierStartedAt.isNull()) {
        this.verifierStartedAt = null;
      }
      else if (verifierStartedAt.isEmpty()) {
        this.verifierStartedAt = Optional.empty();
      }
      else {
        this.verifierStartedAt = Optional.of(verifierStartedAt.get());
      }
      return this;
    }

    public BacktestTrialDetailResponseTrialTimings build() {
      return new BacktestTrialDetailResponseTrialTimings(agentRunFinishedAt, agentRunStartedAt, agentSetupFinishedAt, agentSetupStartedAt, envSetupFinishedAt, envSetupStartedAt, verifierFinishedAt, verifierStartedAt, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
