/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.chronicle.labs.api.types;

import com.chronicle.labs.api.core.Nullable;
import com.chronicle.labs.api.core.NullableNonemptyFilter;
import com.chronicle.labs.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = BacktestJobDetailResponseRun.Builder.class)
public final class BacktestJobDetailResponseRun {
    private final List<String> agentIds;

    private final String datasetLabel;

    private final Optional<Integer> divergences;

    private final Optional<String> environmentLabel;

    private final Optional<String> hue;

    private final String id;

    private final BacktestJobDetailResponseRunMode mode;

    private final String name;

    private final Optional<String> owner;

    private final Optional<OffsetDateTime> scheduledFor;

    private final BacktestJobDetailResponseRunStatus status;

    private final Optional<Integer> totalRuns;

    private final OffsetDateTime updatedAt;

    private final Optional<String> verdict;

    private final Map<String, Object> additionalProperties;

    private BacktestJobDetailResponseRun(
            List<String> agentIds,
            String datasetLabel,
            Optional<Integer> divergences,
            Optional<String> environmentLabel,
            Optional<String> hue,
            String id,
            BacktestJobDetailResponseRunMode mode,
            String name,
            Optional<String> owner,
            Optional<OffsetDateTime> scheduledFor,
            BacktestJobDetailResponseRunStatus status,
            Optional<Integer> totalRuns,
            OffsetDateTime updatedAt,
            Optional<String> verdict,
            Map<String, Object> additionalProperties) {
        this.agentIds = agentIds;
        this.datasetLabel = datasetLabel;
        this.divergences = divergences;
        this.environmentLabel = environmentLabel;
        this.hue = hue;
        this.id = id;
        this.mode = mode;
        this.name = name;
        this.owner = owner;
        this.scheduledFor = scheduledFor;
        this.status = status;
        this.totalRuns = totalRuns;
        this.updatedAt = updatedAt;
        this.verdict = verdict;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Agent ids participating in the run; the first is the baseline.
     */
    @JsonProperty("agentIds")
    public List<String> getAgentIds() {
        return agentIds;
    }

    /**
     * @return Display label for the dataset / production window seed.
     */
    @JsonProperty("datasetLabel")
    public String getDatasetLabel() {
        return datasetLabel;
    }

    /**
     * @return Divergences observed (only set when status is <code>done</code> / <code>failed</code>).
     */
    @JsonIgnore
    public Optional<Integer> getDivergences() {
        if (divergences == null) {
            return Optional.empty();
        }
        return divergences;
    }

    @JsonIgnore
    public Optional<String> getEnvironmentLabel() {
        if (environmentLabel == null) {
            return Optional.empty();
        }
        return environmentLabel;
    }

    @JsonIgnore
    public Optional<String> getHue() {
        if (hue == null) {
            return Optional.empty();
        }
        return hue;
    }

    @JsonProperty("id")
    public String getId() {
        return id;
    }

    @JsonProperty("mode")
    public BacktestJobDetailResponseRunMode getMode() {
        return mode;
    }

    /**
     * @return Display name of the run (matches <code>BacktestRecipe.name</code>).
     */
    @JsonProperty("name")
    public String getName() {
        return name;
    }

    @JsonIgnore
    public Optional<String> getOwner() {
        if (owner == null) {
            return Optional.empty();
        }
        return owner;
    }

    @JsonIgnore
    public Optional<OffsetDateTime> getScheduledFor() {
        if (scheduledFor == null) {
            return Optional.empty();
        }
        return scheduledFor;
    }

    @JsonProperty("status")
    public BacktestJobDetailResponseRunStatus getStatus() {
        return status;
    }

    /**
     * @return Total cases × agents; null while still drafting.
     */
    @JsonIgnore
    public Optional<Integer> getTotalRuns() {
        if (totalRuns == null) {
            return Optional.empty();
        }
        return totalRuns;
    }

    /**
     * @return ISO timestamp of the most recent state change — drives &quot;ago&quot;.
     */
    @JsonProperty("updatedAt")
    public OffsetDateTime getUpdatedAt() {
        return updatedAt;
    }

    @JsonIgnore
    public Optional<String> getVerdict() {
        if (verdict == null) {
            return Optional.empty();
        }
        return verdict;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("divergences")
    private Optional<Integer> _getDivergences() {
        return divergences;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("environmentLabel")
    private Optional<String> _getEnvironmentLabel() {
        return environmentLabel;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("hue")
    private Optional<String> _getHue() {
        return hue;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("owner")
    private Optional<String> _getOwner() {
        return owner;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("scheduledFor")
    private Optional<OffsetDateTime> _getScheduledFor() {
        return scheduledFor;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("totalRuns")
    private Optional<Integer> _getTotalRuns() {
        return totalRuns;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("verdict")
    private Optional<String> _getVerdict() {
        return verdict;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof BacktestJobDetailResponseRun && equalTo((BacktestJobDetailResponseRun) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(BacktestJobDetailResponseRun other) {
        return agentIds.equals(other.agentIds)
                && datasetLabel.equals(other.datasetLabel)
                && divergences.equals(other.divergences)
                && environmentLabel.equals(other.environmentLabel)
                && hue.equals(other.hue)
                && id.equals(other.id)
                && mode.equals(other.mode)
                && name.equals(other.name)
                && owner.equals(other.owner)
                && scheduledFor.equals(other.scheduledFor)
                && status.equals(other.status)
                && totalRuns.equals(other.totalRuns)
                && updatedAt.equals(other.updatedAt)
                && verdict.equals(other.verdict);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.agentIds,
                this.datasetLabel,
                this.divergences,
                this.environmentLabel,
                this.hue,
                this.id,
                this.mode,
                this.name,
                this.owner,
                this.scheduledFor,
                this.status,
                this.totalRuns,
                this.updatedAt,
                this.verdict);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static DatasetLabelStage builder() {
        return new Builder();
    }

    public interface DatasetLabelStage {
        /**
         * <p>Display label for the dataset / production window seed.</p>
         */
        IdStage datasetLabel(@NotNull String datasetLabel);

        Builder from(BacktestJobDetailResponseRun other);
    }

    public interface IdStage {
        ModeStage id(@NotNull String id);
    }

    public interface ModeStage {
        NameStage mode(@NotNull BacktestJobDetailResponseRunMode mode);
    }

    public interface NameStage {
        /**
         * <p>Display name of the run (matches <code>BacktestRecipe.name</code>).</p>
         */
        StatusStage name(@NotNull String name);
    }

    public interface StatusStage {
        UpdatedAtStage status(@NotNull BacktestJobDetailResponseRunStatus status);
    }

    public interface UpdatedAtStage {
        /**
         * <p>ISO timestamp of the most recent state change — drives &quot;ago&quot;.</p>
         */
        _FinalStage updatedAt(@NotNull OffsetDateTime updatedAt);
    }

    public interface _FinalStage {
        BacktestJobDetailResponseRun build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p>Agent ids participating in the run; the first is the baseline.</p>
         */
        _FinalStage agentIds(List<String> agentIds);

        _FinalStage addAgentIds(String agentIds);

        _FinalStage addAllAgentIds(List<String> agentIds);

        /**
         * <p>Divergences observed (only set when status is <code>done</code> / <code>failed</code>).</p>
         */
        _FinalStage divergences(Optional<Integer> divergences);

        _FinalStage divergences(Integer divergences);

        _FinalStage divergences(Nullable<Integer> divergences);

        _FinalStage environmentLabel(Optional<String> environmentLabel);

        _FinalStage environmentLabel(String environmentLabel);

        _FinalStage environmentLabel(Nullable<String> environmentLabel);

        _FinalStage hue(Optional<String> hue);

        _FinalStage hue(String hue);

        _FinalStage hue(Nullable<String> hue);

        _FinalStage owner(Optional<String> owner);

        _FinalStage owner(String owner);

        _FinalStage owner(Nullable<String> owner);

        _FinalStage scheduledFor(Optional<OffsetDateTime> scheduledFor);

        _FinalStage scheduledFor(OffsetDateTime scheduledFor);

        _FinalStage scheduledFor(Nullable<OffsetDateTime> scheduledFor);

        /**
         * <p>Total cases × agents; null while still drafting.</p>
         */
        _FinalStage totalRuns(Optional<Integer> totalRuns);

        _FinalStage totalRuns(Integer totalRuns);

        _FinalStage totalRuns(Nullable<Integer> totalRuns);

        _FinalStage verdict(Optional<String> verdict);

        _FinalStage verdict(String verdict);

        _FinalStage verdict(Nullable<String> verdict);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements DatasetLabelStage, IdStage, ModeStage, NameStage, StatusStage, UpdatedAtStage, _FinalStage {
        private String datasetLabel;

        private String id;

        private BacktestJobDetailResponseRunMode mode;

        private String name;

        private BacktestJobDetailResponseRunStatus status;

        private OffsetDateTime updatedAt;

        private Optional<String> verdict = Optional.empty();

        private Optional<Integer> totalRuns = Optional.empty();

        private Optional<OffsetDateTime> scheduledFor = Optional.empty();

        private Optional<String> owner = Optional.empty();

        private Optional<String> hue = Optional.empty();

        private Optional<String> environmentLabel = Optional.empty();

        private Optional<Integer> divergences = Optional.empty();

        private List<String> agentIds = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(BacktestJobDetailResponseRun other) {
            agentIds(other.getAgentIds());
            datasetLabel(other.getDatasetLabel());
            divergences(other.getDivergences());
            environmentLabel(other.getEnvironmentLabel());
            hue(other.getHue());
            id(other.getId());
            mode(other.getMode());
            name(other.getName());
            owner(other.getOwner());
            scheduledFor(other.getScheduledFor());
            status(other.getStatus());
            totalRuns(other.getTotalRuns());
            updatedAt(other.getUpdatedAt());
            verdict(other.getVerdict());
            return this;
        }

        /**
         * <p>Display label for the dataset / production window seed.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("datasetLabel")
        public IdStage datasetLabel(@NotNull String datasetLabel) {
            this.datasetLabel = Objects.requireNonNull(datasetLabel, "datasetLabel must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("id")
        public ModeStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("mode")
        public NameStage mode(@NotNull BacktestJobDetailResponseRunMode mode) {
            this.mode = Objects.requireNonNull(mode, "mode must not be null");
            return this;
        }

        /**
         * <p>Display name of the run (matches <code>BacktestRecipe.name</code>).</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("name")
        public StatusStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("status")
        public UpdatedAtStage status(@NotNull BacktestJobDetailResponseRunStatus status) {
            this.status = Objects.requireNonNull(status, "status must not be null");
            return this;
        }

        /**
         * <p>ISO timestamp of the most recent state change — drives &quot;ago&quot;.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("updatedAt")
        public _FinalStage updatedAt(@NotNull OffsetDateTime updatedAt) {
            this.updatedAt = Objects.requireNonNull(updatedAt, "updatedAt must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage verdict(Nullable<String> verdict) {
            if (verdict.isNull()) {
                this.verdict = null;
            } else if (verdict.isEmpty()) {
                this.verdict = Optional.empty();
            } else {
                this.verdict = Optional.of(verdict.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage verdict(String verdict) {
            this.verdict = Optional.ofNullable(verdict);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "verdict", nulls = Nulls.SKIP)
        public _FinalStage verdict(Optional<String> verdict) {
            this.verdict = verdict;
            return this;
        }

        /**
         * <p>Total cases × agents; null while still drafting.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage totalRuns(Nullable<Integer> totalRuns) {
            if (totalRuns.isNull()) {
                this.totalRuns = null;
            } else if (totalRuns.isEmpty()) {
                this.totalRuns = Optional.empty();
            } else {
                this.totalRuns = Optional.of(totalRuns.get());
            }
            return this;
        }

        /**
         * <p>Total cases × agents; null while still drafting.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage totalRuns(Integer totalRuns) {
            this.totalRuns = Optional.ofNullable(totalRuns);
            return this;
        }

        /**
         * <p>Total cases × agents; null while still drafting.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "totalRuns", nulls = Nulls.SKIP)
        public _FinalStage totalRuns(Optional<Integer> totalRuns) {
            this.totalRuns = totalRuns;
            return this;
        }

        @java.lang.Override
        public _FinalStage scheduledFor(Nullable<OffsetDateTime> scheduledFor) {
            if (scheduledFor.isNull()) {
                this.scheduledFor = null;
            } else if (scheduledFor.isEmpty()) {
                this.scheduledFor = Optional.empty();
            } else {
                this.scheduledFor = Optional.of(scheduledFor.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage scheduledFor(OffsetDateTime scheduledFor) {
            this.scheduledFor = Optional.ofNullable(scheduledFor);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "scheduledFor", nulls = Nulls.SKIP)
        public _FinalStage scheduledFor(Optional<OffsetDateTime> scheduledFor) {
            this.scheduledFor = scheduledFor;
            return this;
        }

        @java.lang.Override
        public _FinalStage owner(Nullable<String> owner) {
            if (owner.isNull()) {
                this.owner = null;
            } else if (owner.isEmpty()) {
                this.owner = Optional.empty();
            } else {
                this.owner = Optional.of(owner.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage owner(String owner) {
            this.owner = Optional.ofNullable(owner);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "owner", nulls = Nulls.SKIP)
        public _FinalStage owner(Optional<String> owner) {
            this.owner = owner;
            return this;
        }

        @java.lang.Override
        public _FinalStage hue(Nullable<String> hue) {
            if (hue.isNull()) {
                this.hue = null;
            } else if (hue.isEmpty()) {
                this.hue = Optional.empty();
            } else {
                this.hue = Optional.of(hue.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage hue(String hue) {
            this.hue = Optional.ofNullable(hue);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "hue", nulls = Nulls.SKIP)
        public _FinalStage hue(Optional<String> hue) {
            this.hue = hue;
            return this;
        }

        @java.lang.Override
        public _FinalStage environmentLabel(Nullable<String> environmentLabel) {
            if (environmentLabel.isNull()) {
                this.environmentLabel = null;
            } else if (environmentLabel.isEmpty()) {
                this.environmentLabel = Optional.empty();
            } else {
                this.environmentLabel = Optional.of(environmentLabel.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage environmentLabel(String environmentLabel) {
            this.environmentLabel = Optional.ofNullable(environmentLabel);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "environmentLabel", nulls = Nulls.SKIP)
        public _FinalStage environmentLabel(Optional<String> environmentLabel) {
            this.environmentLabel = environmentLabel;
            return this;
        }

        /**
         * <p>Divergences observed (only set when status is <code>done</code> / <code>failed</code>).</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage divergences(Nullable<Integer> divergences) {
            if (divergences.isNull()) {
                this.divergences = null;
            } else if (divergences.isEmpty()) {
                this.divergences = Optional.empty();
            } else {
                this.divergences = Optional.of(divergences.get());
            }
            return this;
        }

        /**
         * <p>Divergences observed (only set when status is <code>done</code> / <code>failed</code>).</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage divergences(Integer divergences) {
            this.divergences = Optional.ofNullable(divergences);
            return this;
        }

        /**
         * <p>Divergences observed (only set when status is <code>done</code> / <code>failed</code>).</p>
         */
        @java.lang.Override
        @JsonSetter(value = "divergences", nulls = Nulls.SKIP)
        public _FinalStage divergences(Optional<Integer> divergences) {
            this.divergences = divergences;
            return this;
        }

        /**
         * <p>Agent ids participating in the run; the first is the baseline.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAllAgentIds(List<String> agentIds) {
            if (agentIds != null) {
                this.agentIds.addAll(agentIds);
            }
            return this;
        }

        /**
         * <p>Agent ids participating in the run; the first is the baseline.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage addAgentIds(String agentIds) {
            this.agentIds.add(agentIds);
            return this;
        }

        /**
         * <p>Agent ids participating in the run; the first is the baseline.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "agentIds", nulls = Nulls.SKIP)
        public _FinalStage agentIds(List<String> agentIds) {
            this.agentIds.clear();
            if (agentIds != null) {
                this.agentIds.addAll(agentIds);
            }
            return this;
        }

        @java.lang.Override
        public BacktestJobDetailResponseRun build() {
            return new BacktestJobDetailResponseRun(
                    agentIds,
                    datasetLabel,
                    divergences,
                    environmentLabel,
                    hue,
                    id,
                    mode,
                    name,
                    owner,
                    scheduledFor,
                    status,
                    totalRuns,
                    updatedAt,
                    verdict,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
