/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.chronicle.labs.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class BacktestJobDetailResponseRunStatus {
  public static final BacktestJobDetailResponseRunStatus FAILED = new BacktestJobDetailResponseRunStatus(Value.FAILED, "failed");

  public static final BacktestJobDetailResponseRunStatus CANCELLED = new BacktestJobDetailResponseRunStatus(Value.CANCELLED, "cancelled");

  public static final BacktestJobDetailResponseRunStatus PAUSED = new BacktestJobDetailResponseRunStatus(Value.PAUSED, "paused");

  public static final BacktestJobDetailResponseRunStatus SCHEDULED = new BacktestJobDetailResponseRunStatus(Value.SCHEDULED, "scheduled");

  public static final BacktestJobDetailResponseRunStatus RUNNING = new BacktestJobDetailResponseRunStatus(Value.RUNNING, "running");

  public static final BacktestJobDetailResponseRunStatus DRAFT = new BacktestJobDetailResponseRunStatus(Value.DRAFT, "draft");

  public static final BacktestJobDetailResponseRunStatus DONE = new BacktestJobDetailResponseRunStatus(Value.DONE, "done");

  private final Value value;

  private final String string;

  BacktestJobDetailResponseRunStatus(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof BacktestJobDetailResponseRunStatus && this.string.equals(((BacktestJobDetailResponseRunStatus) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case FAILED:
        return visitor.visitFailed();
      case CANCELLED:
        return visitor.visitCancelled();
      case PAUSED:
        return visitor.visitPaused();
      case SCHEDULED:
        return visitor.visitScheduled();
      case RUNNING:
        return visitor.visitRunning();
      case DRAFT:
        return visitor.visitDraft();
      case DONE:
        return visitor.visitDone();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static BacktestJobDetailResponseRunStatus valueOf(String value) {
    switch (value) {
      case "failed":
        return FAILED;
      case "cancelled":
        return CANCELLED;
      case "paused":
        return PAUSED;
      case "scheduled":
        return SCHEDULED;
      case "running":
        return RUNNING;
      case "draft":
        return DRAFT;
      case "done":
        return DONE;
      default:
        return new BacktestJobDetailResponseRunStatus(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    RUNNING,

    DONE,

    PAUSED,

    SCHEDULED,

    DRAFT,

    FAILED,

    CANCELLED,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitRunning();

    T visitDone();

    T visitPaused();

    T visitScheduled();

    T visitDraft();

    T visitFailed();

    T visitCancelled();

    T visitUnknown(String unknownType);
  }
}
