/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.chronicle.labs.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class BacktestJobDetailResponseJobSandboxDriver {
    public static final BacktestJobDetailResponseJobSandboxDriver DOCKER =
            new BacktestJobDetailResponseJobSandboxDriver(Value.DOCKER, "docker");

    public static final BacktestJobDetailResponseJobSandboxDriver DAYTONA =
            new BacktestJobDetailResponseJobSandboxDriver(Value.DAYTONA, "daytona");

    public static final BacktestJobDetailResponseJobSandboxDriver MOCK =
            new BacktestJobDetailResponseJobSandboxDriver(Value.MOCK, "mock");

    private final Value value;

    private final String string;

    BacktestJobDetailResponseJobSandboxDriver(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof BacktestJobDetailResponseJobSandboxDriver
                        && this.string.equals(((BacktestJobDetailResponseJobSandboxDriver) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case DOCKER:
                return visitor.visitDocker();
            case DAYTONA:
                return visitor.visitDaytona();
            case MOCK:
                return visitor.visitMock();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static BacktestJobDetailResponseJobSandboxDriver valueOf(String value) {
        switch (value) {
            case "docker":
                return DOCKER;
            case "daytona":
                return DAYTONA;
            case "mock":
                return MOCK;
            default:
                return new BacktestJobDetailResponseJobSandboxDriver(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        DOCKER,

        DAYTONA,

        MOCK,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitDocker();

        T visitDaytona();

        T visitMock();

        T visitUnknown(String unknownType);
    }
}
