/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.chronicle.labs.api.types;

import com.chronicle.labs.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = BacktestTrialDetailResponseScorersItem.Builder.class
)
public final class BacktestTrialDetailResponseScorersItem {
  private final BacktestTrialDetailResponseScorersItemGrader grader;

  private final String rewardKey;

  private final Map<String, Object> additionalProperties;

  private BacktestTrialDetailResponseScorersItem(
      BacktestTrialDetailResponseScorersItemGrader grader, String rewardKey,
      Map<String, Object> additionalProperties) {
    this.grader = grader;
    this.rewardKey = rewardKey;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("grader")
  public BacktestTrialDetailResponseScorersItemGrader getGrader() {
    return grader;
  }

  /**
   * @return Reward key this scorer's score is stored under (<code>grader_&lt;id&gt;</code>).
   */
  @JsonProperty("rewardKey")
  public String getRewardKey() {
    return rewardKey;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof BacktestTrialDetailResponseScorersItem && equalTo((BacktestTrialDetailResponseScorersItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(BacktestTrialDetailResponseScorersItem other) {
    return grader.equals(other.grader) && rewardKey.equals(other.rewardKey);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.grader, this.rewardKey);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static GraderStage builder() {
    return new Builder();
  }

  public interface GraderStage {
    RewardKeyStage grader(@NotNull BacktestTrialDetailResponseScorersItemGrader grader);

    Builder from(BacktestTrialDetailResponseScorersItem other);
  }

  public interface RewardKeyStage {
    /**
     * <p>Reward key this scorer's score is stored under (<code>grader_&lt;id&gt;</code>).</p>
     */
    _FinalStage rewardKey(@NotNull String rewardKey);
  }

  public interface _FinalStage {
    BacktestTrialDetailResponseScorersItem build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements GraderStage, RewardKeyStage, _FinalStage {
    private BacktestTrialDetailResponseScorersItemGrader grader;

    private String rewardKey;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(BacktestTrialDetailResponseScorersItem other) {
      grader(other.getGrader());
      rewardKey(other.getRewardKey());
      return this;
    }

    @java.lang.Override
    @JsonSetter("grader")
    public RewardKeyStage grader(@NotNull BacktestTrialDetailResponseScorersItemGrader grader) {
      this.grader = Objects.requireNonNull(grader, "grader must not be null");
      return this;
    }

    /**
     * <p>Reward key this scorer's score is stored under (<code>grader_&lt;id&gt;</code>).</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("rewardKey")
    public _FinalStage rewardKey(@NotNull String rewardKey) {
      this.rewardKey = Objects.requireNonNull(rewardKey, "rewardKey must not be null");
      return this;
    }

    @java.lang.Override
    public BacktestTrialDetailResponseScorersItem build() {
      return new BacktestTrialDetailResponseScorersItem(grader, rewardKey, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
