/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.chronicle.labs.api.types;

import com.chronicle.labs.api.core.Nullable;
import com.chronicle.labs.api.core.NullableNonemptyFilter;
import com.chronicle.labs.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = BacktestTrialDetailResponseStepsItem.Builder.class)
public final class BacktestTrialDetailResponseStepsItem {
    private final BacktestTrialDetailResponseStepsItemActor actor;

    private final OffsetDateTime createdAt;

    private final Optional<OffsetDateTime> endedAt;

    private final Optional<String> graderId;

    private final String id;

    private final BacktestTrialDetailResponseStepsItemKind kind;

    private final int ordinal;

    private final Optional<Object> payload;

    private final Optional<Double> score;

    private final OffsetDateTime startedAt;

    private final Optional<BacktestTrialDetailResponseStepsItemStatus> status;

    private final String title;

    private final String trialId;

    private final Map<String, Object> additionalProperties;

    private BacktestTrialDetailResponseStepsItem(
            BacktestTrialDetailResponseStepsItemActor actor,
            OffsetDateTime createdAt,
            Optional<OffsetDateTime> endedAt,
            Optional<String> graderId,
            String id,
            BacktestTrialDetailResponseStepsItemKind kind,
            int ordinal,
            Optional<Object> payload,
            Optional<Double> score,
            OffsetDateTime startedAt,
            Optional<BacktestTrialDetailResponseStepsItemStatus> status,
            String title,
            String trialId,
            Map<String, Object> additionalProperties) {
        this.actor = actor;
        this.createdAt = createdAt;
        this.endedAt = endedAt;
        this.graderId = graderId;
        this.id = id;
        this.kind = kind;
        this.ordinal = ordinal;
        this.payload = payload;
        this.score = score;
        this.startedAt = startedAt;
        this.status = status;
        this.title = title;
        this.trialId = trialId;
        this.additionalProperties = additionalProperties;
    }

    /**
     * @return Who performed a step; one timeline lane per actor.
     */
    @JsonProperty("actor")
    public BacktestTrialDetailResponseStepsItemActor getActor() {
        return actor;
    }

    @JsonProperty("createdAt")
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    /**
     * @return <code>None</code> for instantaneous steps (seed events, state changes).
     */
    @JsonIgnore
    public Optional<OffsetDateTime> getEndedAt() {
        if (endedAt == null) {
            return Optional.empty();
        }
        return endedAt;
    }

    /**
     * @return Frozen verifier id (or recipe grader id) for <code>grade</code> steps.
     */
    @JsonIgnore
    public Optional<String> getGraderId() {
        if (graderId == null) {
            return Optional.empty();
        }
        return graderId;
    }

    @JsonProperty("id")
    public String getId() {
        return id;
    }

    /**
     * @return What a step is. Drives the glyph on the timeline and which detail renderer opens when the span is clicked.
     */
    @JsonProperty("kind")
    public BacktestTrialDetailResponseStepsItemKind getKind() {
        return kind;
    }

    /**
     * @return Position within the trial; steps are returned ordered by it.
     */
    @JsonProperty("ordinal")
    public int getOrdinal() {
        return ordinal;
    }

    /**
     * @return Free-form detail: <code>request</code>/<code>response</code> for tool calls, <code>text</code> for messages, <code>reasoning</code> for judge grades, and so on.
     */
    @JsonProperty("payload")
    public Optional<Object> getPayload() {
        return payload;
    }

    /**
     * @return Grader score in <code>[0, 1]</code> for <code>grade</code> steps.
     */
    @JsonIgnore
    public Optional<Double> getScore() {
        if (score == null) {
            return Optional.empty();
        }
        return score;
    }

    @JsonProperty("startedAt")
    public OffsetDateTime getStartedAt() {
        return startedAt;
    }

    /**
     * @return Outcome colouring for a step. <code>None</code> renders neutral.
     */
    @JsonIgnore
    public Optional<BacktestTrialDetailResponseStepsItemStatus> getStatus() {
        if (status == null) {
            return Optional.empty();
        }
        return status;
    }

    @JsonProperty("title")
    public String getTitle() {
        return title;
    }

    @JsonProperty("trialId")
    public String getTrialId() {
        return trialId;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("endedAt")
    private Optional<OffsetDateTime> _getEndedAt() {
        return endedAt;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("graderId")
    private Optional<String> _getGraderId() {
        return graderId;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("score")
    private Optional<Double> _getScore() {
        return score;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("status")
    private Optional<BacktestTrialDetailResponseStepsItemStatus> _getStatus() {
        return status;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof BacktestTrialDetailResponseStepsItem
                && equalTo((BacktestTrialDetailResponseStepsItem) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(BacktestTrialDetailResponseStepsItem other) {
        return actor.equals(other.actor)
                && createdAt.equals(other.createdAt)
                && endedAt.equals(other.endedAt)
                && graderId.equals(other.graderId)
                && id.equals(other.id)
                && kind.equals(other.kind)
                && ordinal == other.ordinal
                && payload.equals(other.payload)
                && score.equals(other.score)
                && startedAt.equals(other.startedAt)
                && status.equals(other.status)
                && title.equals(other.title)
                && trialId.equals(other.trialId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.actor,
                this.createdAt,
                this.endedAt,
                this.graderId,
                this.id,
                this.kind,
                this.ordinal,
                this.payload,
                this.score,
                this.startedAt,
                this.status,
                this.title,
                this.trialId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static ActorStage builder() {
        return new Builder();
    }

    public interface ActorStage {
        /**
         * <p>Who performed a step; one timeline lane per actor.</p>
         */
        CreatedAtStage actor(@NotNull BacktestTrialDetailResponseStepsItemActor actor);

        Builder from(BacktestTrialDetailResponseStepsItem other);
    }

    public interface CreatedAtStage {
        IdStage createdAt(@NotNull OffsetDateTime createdAt);
    }

    public interface IdStage {
        KindStage id(@NotNull String id);
    }

    public interface KindStage {
        /**
         * <p>What a step is. Drives the glyph on the timeline and which detail renderer opens when the span is clicked.</p>
         */
        OrdinalStage kind(@NotNull BacktestTrialDetailResponseStepsItemKind kind);
    }

    public interface OrdinalStage {
        /**
         * <p>Position within the trial; steps are returned ordered by it.</p>
         */
        StartedAtStage ordinal(int ordinal);
    }

    public interface StartedAtStage {
        TitleStage startedAt(@NotNull OffsetDateTime startedAt);
    }

    public interface TitleStage {
        TrialIdStage title(@NotNull String title);
    }

    public interface TrialIdStage {
        _FinalStage trialId(@NotNull String trialId);
    }

    public interface _FinalStage {
        BacktestTrialDetailResponseStepsItem build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        /**
         * <p><code>None</code> for instantaneous steps (seed events, state changes).</p>
         */
        _FinalStage endedAt(Optional<OffsetDateTime> endedAt);

        _FinalStage endedAt(OffsetDateTime endedAt);

        _FinalStage endedAt(Nullable<OffsetDateTime> endedAt);

        /**
         * <p>Frozen verifier id (or recipe grader id) for <code>grade</code> steps.</p>
         */
        _FinalStage graderId(Optional<String> graderId);

        _FinalStage graderId(String graderId);

        _FinalStage graderId(Nullable<String> graderId);

        /**
         * <p>Free-form detail: <code>request</code>/<code>response</code> for tool calls, <code>text</code> for messages, <code>reasoning</code> for judge grades, and so on.</p>
         */
        _FinalStage payload(Optional<Object> payload);

        _FinalStage payload(Object payload);

        /**
         * <p>Grader score in <code>[0, 1]</code> for <code>grade</code> steps.</p>
         */
        _FinalStage score(Optional<Double> score);

        _FinalStage score(Double score);

        _FinalStage score(Nullable<Double> score);

        /**
         * <p>Outcome colouring for a step. <code>None</code> renders neutral.</p>
         */
        _FinalStage status(Optional<BacktestTrialDetailResponseStepsItemStatus> status);

        _FinalStage status(BacktestTrialDetailResponseStepsItemStatus status);

        _FinalStage status(Nullable<BacktestTrialDetailResponseStepsItemStatus> status);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements ActorStage,
                    CreatedAtStage,
                    IdStage,
                    KindStage,
                    OrdinalStage,
                    StartedAtStage,
                    TitleStage,
                    TrialIdStage,
                    _FinalStage {
        private BacktestTrialDetailResponseStepsItemActor actor;

        private OffsetDateTime createdAt;

        private String id;

        private BacktestTrialDetailResponseStepsItemKind kind;

        private int ordinal;

        private OffsetDateTime startedAt;

        private String title;

        private String trialId;

        private Optional<BacktestTrialDetailResponseStepsItemStatus> status = Optional.empty();

        private Optional<Double> score = Optional.empty();

        private Optional<Object> payload = Optional.empty();

        private Optional<String> graderId = Optional.empty();

        private Optional<OffsetDateTime> endedAt = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(BacktestTrialDetailResponseStepsItem other) {
            actor(other.getActor());
            createdAt(other.getCreatedAt());
            endedAt(other.getEndedAt());
            graderId(other.getGraderId());
            id(other.getId());
            kind(other.getKind());
            ordinal(other.getOrdinal());
            payload(other.getPayload());
            score(other.getScore());
            startedAt(other.getStartedAt());
            status(other.getStatus());
            title(other.getTitle());
            trialId(other.getTrialId());
            return this;
        }

        /**
         * <p>Who performed a step; one timeline lane per actor.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("actor")
        public CreatedAtStage actor(@NotNull BacktestTrialDetailResponseStepsItemActor actor) {
            this.actor = Objects.requireNonNull(actor, "actor must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("createdAt")
        public IdStage createdAt(@NotNull OffsetDateTime createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("id")
        public KindStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        /**
         * <p>What a step is. Drives the glyph on the timeline and which detail renderer opens when the span is clicked.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("kind")
        public OrdinalStage kind(@NotNull BacktestTrialDetailResponseStepsItemKind kind) {
            this.kind = Objects.requireNonNull(kind, "kind must not be null");
            return this;
        }

        /**
         * <p>Position within the trial; steps are returned ordered by it.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("ordinal")
        public StartedAtStage ordinal(int ordinal) {
            this.ordinal = ordinal;
            return this;
        }

        @java.lang.Override
        @JsonSetter("startedAt")
        public TitleStage startedAt(@NotNull OffsetDateTime startedAt) {
            this.startedAt = Objects.requireNonNull(startedAt, "startedAt must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("title")
        public TrialIdStage title(@NotNull String title) {
            this.title = Objects.requireNonNull(title, "title must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("trialId")
        public _FinalStage trialId(@NotNull String trialId) {
            this.trialId = Objects.requireNonNull(trialId, "trialId must not be null");
            return this;
        }

        /**
         * <p>Outcome colouring for a step. <code>None</code> renders neutral.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage status(Nullable<BacktestTrialDetailResponseStepsItemStatus> status) {
            if (status.isNull()) {
                this.status = null;
            } else if (status.isEmpty()) {
                this.status = Optional.empty();
            } else {
                this.status = Optional.of(status.get());
            }
            return this;
        }

        /**
         * <p>Outcome colouring for a step. <code>None</code> renders neutral.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage status(BacktestTrialDetailResponseStepsItemStatus status) {
            this.status = Optional.ofNullable(status);
            return this;
        }

        /**
         * <p>Outcome colouring for a step. <code>None</code> renders neutral.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "status", nulls = Nulls.SKIP)
        public _FinalStage status(Optional<BacktestTrialDetailResponseStepsItemStatus> status) {
            this.status = status;
            return this;
        }

        /**
         * <p>Grader score in <code>[0, 1]</code> for <code>grade</code> steps.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage score(Nullable<Double> score) {
            if (score.isNull()) {
                this.score = null;
            } else if (score.isEmpty()) {
                this.score = Optional.empty();
            } else {
                this.score = Optional.of(score.get());
            }
            return this;
        }

        /**
         * <p>Grader score in <code>[0, 1]</code> for <code>grade</code> steps.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage score(Double score) {
            this.score = Optional.ofNullable(score);
            return this;
        }

        /**
         * <p>Grader score in <code>[0, 1]</code> for <code>grade</code> steps.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "score", nulls = Nulls.SKIP)
        public _FinalStage score(Optional<Double> score) {
            this.score = score;
            return this;
        }

        /**
         * <p>Free-form detail: <code>request</code>/<code>response</code> for tool calls, <code>text</code> for messages, <code>reasoning</code> for judge grades, and so on.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage payload(Object payload) {
            this.payload = Optional.ofNullable(payload);
            return this;
        }

        /**
         * <p>Free-form detail: <code>request</code>/<code>response</code> for tool calls, <code>text</code> for messages, <code>reasoning</code> for judge grades, and so on.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "payload", nulls = Nulls.SKIP)
        public _FinalStage payload(Optional<Object> payload) {
            this.payload = payload;
            return this;
        }

        /**
         * <p>Frozen verifier id (or recipe grader id) for <code>grade</code> steps.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage graderId(Nullable<String> graderId) {
            if (graderId.isNull()) {
                this.graderId = null;
            } else if (graderId.isEmpty()) {
                this.graderId = Optional.empty();
            } else {
                this.graderId = Optional.of(graderId.get());
            }
            return this;
        }

        /**
         * <p>Frozen verifier id (or recipe grader id) for <code>grade</code> steps.</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage graderId(String graderId) {
            this.graderId = Optional.ofNullable(graderId);
            return this;
        }

        /**
         * <p>Frozen verifier id (or recipe grader id) for <code>grade</code> steps.</p>
         */
        @java.lang.Override
        @JsonSetter(value = "graderId", nulls = Nulls.SKIP)
        public _FinalStage graderId(Optional<String> graderId) {
            this.graderId = graderId;
            return this;
        }

        /**
         * <p><code>None</code> for instantaneous steps (seed events, state changes).</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage endedAt(Nullable<OffsetDateTime> endedAt) {
            if (endedAt.isNull()) {
                this.endedAt = null;
            } else if (endedAt.isEmpty()) {
                this.endedAt = Optional.empty();
            } else {
                this.endedAt = Optional.of(endedAt.get());
            }
            return this;
        }

        /**
         * <p><code>None</code> for instantaneous steps (seed events, state changes).</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage endedAt(OffsetDateTime endedAt) {
            this.endedAt = Optional.ofNullable(endedAt);
            return this;
        }

        /**
         * <p><code>None</code> for instantaneous steps (seed events, state changes).</p>
         */
        @java.lang.Override
        @JsonSetter(value = "endedAt", nulls = Nulls.SKIP)
        public _FinalStage endedAt(Optional<OffsetDateTime> endedAt) {
            this.endedAt = endedAt;
            return this;
        }

        @java.lang.Override
        public BacktestTrialDetailResponseStepsItem build() {
            return new BacktestTrialDetailResponseStepsItem(
                    actor,
                    createdAt,
                    endedAt,
                    graderId,
                    id,
                    kind,
                    ordinal,
                    payload,
                    score,
                    startedAt,
                    status,
                    title,
                    trialId,
                    additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
