/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.chronicle.labs.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class CreateBacktestJobResponseRunStatus {
    public static final CreateBacktestJobResponseRunStatus FAILED =
            new CreateBacktestJobResponseRunStatus(Value.FAILED, "failed");

    public static final CreateBacktestJobResponseRunStatus CANCELLED =
            new CreateBacktestJobResponseRunStatus(Value.CANCELLED, "cancelled");

    public static final CreateBacktestJobResponseRunStatus PAUSED =
            new CreateBacktestJobResponseRunStatus(Value.PAUSED, "paused");

    public static final CreateBacktestJobResponseRunStatus SCHEDULED =
            new CreateBacktestJobResponseRunStatus(Value.SCHEDULED, "scheduled");

    public static final CreateBacktestJobResponseRunStatus RUNNING =
            new CreateBacktestJobResponseRunStatus(Value.RUNNING, "running");

    public static final CreateBacktestJobResponseRunStatus DRAFT =
            new CreateBacktestJobResponseRunStatus(Value.DRAFT, "draft");

    public static final CreateBacktestJobResponseRunStatus DONE =
            new CreateBacktestJobResponseRunStatus(Value.DONE, "done");

    private final Value value;

    private final String string;

    CreateBacktestJobResponseRunStatus(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof CreateBacktestJobResponseRunStatus
                        && this.string.equals(((CreateBacktestJobResponseRunStatus) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case FAILED:
                return visitor.visitFailed();
            case CANCELLED:
                return visitor.visitCancelled();
            case PAUSED:
                return visitor.visitPaused();
            case SCHEDULED:
                return visitor.visitScheduled();
            case RUNNING:
                return visitor.visitRunning();
            case DRAFT:
                return visitor.visitDraft();
            case DONE:
                return visitor.visitDone();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static CreateBacktestJobResponseRunStatus valueOf(String value) {
        switch (value) {
            case "failed":
                return FAILED;
            case "cancelled":
                return CANCELLED;
            case "paused":
                return PAUSED;
            case "scheduled":
                return SCHEDULED;
            case "running":
                return RUNNING;
            case "draft":
                return DRAFT;
            case "done":
                return DONE;
            default:
                return new CreateBacktestJobResponseRunStatus(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        RUNNING,

        DONE,

        PAUSED,

        SCHEDULED,

        DRAFT,

        FAILED,

        CANCELLED,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitRunning();

        T visitDone();

        T visitPaused();

        T visitScheduled();

        T visitDraft();

        T visitFailed();

        T visitCancelled();

        T visitUnknown(String unknownType);
    }
}
