/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.chronicle.labs.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class CreateTaskSuiteWithTraceResponseMembershipPurpose {
    public static final CreateTaskSuiteWithTraceResponseMembershipPurpose TRAINING =
            new CreateTaskSuiteWithTraceResponseMembershipPurpose(Value.TRAINING, "training");

    public static final CreateTaskSuiteWithTraceResponseMembershipPurpose REVIEW =
            new CreateTaskSuiteWithTraceResponseMembershipPurpose(Value.REVIEW, "review");

    public static final CreateTaskSuiteWithTraceResponseMembershipPurpose REPLAY =
            new CreateTaskSuiteWithTraceResponseMembershipPurpose(Value.REPLAY, "replay");

    public static final CreateTaskSuiteWithTraceResponseMembershipPurpose EVAL =
            new CreateTaskSuiteWithTraceResponseMembershipPurpose(Value.EVAL, "eval");

    private final Value value;

    private final String string;

    CreateTaskSuiteWithTraceResponseMembershipPurpose(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof CreateTaskSuiteWithTraceResponseMembershipPurpose
                        && this.string.equals(((CreateTaskSuiteWithTraceResponseMembershipPurpose) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case TRAINING:
                return visitor.visitTraining();
            case REVIEW:
                return visitor.visitReview();
            case REPLAY:
                return visitor.visitReplay();
            case EVAL:
                return visitor.visitEval();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static CreateTaskSuiteWithTraceResponseMembershipPurpose valueOf(String value) {
        switch (value) {
            case "training":
                return TRAINING;
            case "review":
                return REVIEW;
            case "replay":
                return REPLAY;
            case "eval":
                return EVAL;
            default:
                return new CreateTaskSuiteWithTraceResponseMembershipPurpose(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        EVAL,

        TRAINING,

        REPLAY,

        REVIEW,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitEval();

        T visitTraining();

        T visitReplay();

        T visitReview();

        T visitUnknown(String unknownType);
    }
}
