/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.chronicle.labs.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class CreateAgentChatSessionResponseSessionMessagesItemRole {
    public static final CreateAgentChatSessionResponseSessionMessagesItemRole USER =
            new CreateAgentChatSessionResponseSessionMessagesItemRole(Value.USER, "user");

    public static final CreateAgentChatSessionResponseSessionMessagesItemRole AGENT =
            new CreateAgentChatSessionResponseSessionMessagesItemRole(Value.AGENT, "agent");

    private final Value value;

    private final String string;

    CreateAgentChatSessionResponseSessionMessagesItemRole(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof CreateAgentChatSessionResponseSessionMessagesItemRole
                        && this.string.equals(((CreateAgentChatSessionResponseSessionMessagesItemRole) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case USER:
                return visitor.visitUser();
            case AGENT:
                return visitor.visitAgent();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static CreateAgentChatSessionResponseSessionMessagesItemRole valueOf(String value) {
        switch (value) {
            case "user":
                return USER;
            case "agent":
                return AGENT;
            default:
                return new CreateAgentChatSessionResponseSessionMessagesItemRole(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        USER,

        AGENT,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitUser();

        T visitAgent();

        T visitUnknown(String unknownType);
    }
}
