/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.chronicle.labs.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class DatasetSavedViewScope {
  public static final DatasetSavedViewScope PERSONAL = new DatasetSavedViewScope(Value.PERSONAL, "personal");

  public static final DatasetSavedViewScope WORKSPACE = new DatasetSavedViewScope(Value.WORKSPACE, "workspace");

  private final Value value;

  private final String string;

  DatasetSavedViewScope(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof DatasetSavedViewScope && this.string.equals(((DatasetSavedViewScope) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case PERSONAL:
        return visitor.visitPersonal();
      case WORKSPACE:
        return visitor.visitWorkspace();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static DatasetSavedViewScope valueOf(String value) {
    switch (value) {
      case "personal":
        return PERSONAL;
      case "workspace":
        return WORKSPACE;
      default:
        return new DatasetSavedViewScope(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    PERSONAL,

    WORKSPACE,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitPersonal();

    T visitWorkspace();

    T visitUnknown(String unknownType);
  }
}
