/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.chronicle.labs.api.types;

import com.chronicle.labs.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = DatasetSavedViewStateSortingItem.Builder.class
)
public final class DatasetSavedViewStateSortingItem {
  private final boolean desc;

  private final String id;

  private final Map<String, Object> additionalProperties;

  private DatasetSavedViewStateSortingItem(boolean desc, String id,
      Map<String, Object> additionalProperties) {
    this.desc = desc;
    this.id = id;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("desc")
  public boolean getDesc() {
    return desc;
  }

  @JsonProperty("id")
  public String getId() {
    return id;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof DatasetSavedViewStateSortingItem && equalTo((DatasetSavedViewStateSortingItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(DatasetSavedViewStateSortingItem other) {
    return desc == other.desc && id.equals(other.id);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.desc, this.id);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static DescStage builder() {
    return new Builder();
  }

  public interface DescStage {
    IdStage desc(boolean desc);

    Builder from(DatasetSavedViewStateSortingItem other);
  }

  public interface IdStage {
    _FinalStage id(@NotNull String id);
  }

  public interface _FinalStage {
    DatasetSavedViewStateSortingItem build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements DescStage, IdStage, _FinalStage {
    private boolean desc;

    private String id;

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(DatasetSavedViewStateSortingItem other) {
      desc(other.getDesc());
      id(other.getId());
      return this;
    }

    @java.lang.Override
    @JsonSetter("desc")
    public IdStage desc(boolean desc) {
      this.desc = desc;
      return this;
    }

    @java.lang.Override
    @JsonSetter("id")
    public _FinalStage id(@NotNull String id) {
      this.id = Objects.requireNonNull(id, "id must not be null");
      return this;
    }

    @java.lang.Override
    public DatasetSavedViewStateSortingItem build() {
      return new DatasetSavedViewStateSortingItem(desc, id, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
