/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.chronicle.labs.api.types;

import com.chronicle.labs.api.core.Nullable;
import com.chronicle.labs.api.core.NullableNonemptyFilter;
import com.chronicle.labs.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = EnvironmentVersionRecordSpecTwinsItem.Builder.class
)
public final class EnvironmentVersionRecordSpecTwinsItem {
  private final Optional<List<String>> authorities;

  private final Optional<String> image;

  private final String service;

  private final Map<String, Object> additionalProperties;

  private EnvironmentVersionRecordSpecTwinsItem(Optional<List<String>> authorities,
      Optional<String> image, String service, Map<String, Object> additionalProperties) {
    this.authorities = authorities;
    this.image = image;
    this.service = service;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("authorities")
  public Optional<List<String>> getAuthorities() {
    return authorities;
  }

  /**
   * @return Image override; defaults to the platform's per-service template.
   */
  @JsonIgnore
  public Optional<String> getImage() {
    if (image == null) {
      return Optional.empty();
    }
    return image;
  }

  /**
   * @return Twin model name, e.g. <code>slack</code>.
   */
  @JsonProperty("service")
  public String getService() {
    return service;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("image")
  private Optional<String> _getImage() {
    return image;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof EnvironmentVersionRecordSpecTwinsItem && equalTo((EnvironmentVersionRecordSpecTwinsItem) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(EnvironmentVersionRecordSpecTwinsItem other) {
    return authorities.equals(other.authorities) && image.equals(other.image) && service.equals(other.service);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.authorities, this.image, this.service);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static ServiceStage builder() {
    return new Builder();
  }

  public interface ServiceStage {
    /**
     * <p>Twin model name, e.g. <code>slack</code>.</p>
     */
    _FinalStage service(@NotNull String service);

    Builder from(EnvironmentVersionRecordSpecTwinsItem other);
  }

  public interface _FinalStage {
    EnvironmentVersionRecordSpecTwinsItem build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage authorities(Optional<List<String>> authorities);

    _FinalStage authorities(List<String> authorities);

    /**
     * <p>Image override; defaults to the platform's per-service template.</p>
     */
    _FinalStage image(Optional<String> image);

    _FinalStage image(String image);

    _FinalStage image(Nullable<String> image);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements ServiceStage, _FinalStage {
    private String service;

    private Optional<String> image = Optional.empty();

    private Optional<List<String>> authorities = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(EnvironmentVersionRecordSpecTwinsItem other) {
      authorities(other.getAuthorities());
      image(other.getImage());
      service(other.getService());
      return this;
    }

    /**
     * <p>Twin model name, e.g. <code>slack</code>.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    @JsonSetter("service")
    public _FinalStage service(@NotNull String service) {
      this.service = Objects.requireNonNull(service, "service must not be null");
      return this;
    }

    /**
     * <p>Image override; defaults to the platform's per-service template.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage image(Nullable<String> image) {
      if (image.isNull()) {
        this.image = null;
      }
      else if (image.isEmpty()) {
        this.image = Optional.empty();
      }
      else {
        this.image = Optional.of(image.get());
      }
      return this;
    }

    /**
     * <p>Image override; defaults to the platform's per-service template.</p>
     * @return Reference to {@code this} so that method calls can be chained together.
     */
    @java.lang.Override
    public _FinalStage image(String image) {
      this.image = Optional.ofNullable(image);
      return this;
    }

    /**
     * <p>Image override; defaults to the platform's per-service template.</p>
     */
    @java.lang.Override
    @JsonSetter(
        value = "image",
        nulls = Nulls.SKIP
    )
    public _FinalStage image(Optional<String> image) {
      this.image = image;
      return this;
    }

    @java.lang.Override
    public _FinalStage authorities(List<String> authorities) {
      this.authorities = Optional.ofNullable(authorities);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "authorities",
        nulls = Nulls.SKIP
    )
    public _FinalStage authorities(Optional<List<String>> authorities) {
      this.authorities = authorities;
      return this;
    }

    @java.lang.Override
    public EnvironmentVersionRecordSpecTwinsItem build() {
      return new EnvironmentVersionRecordSpecTwinsItem(authorities, image, service, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
