/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.chronicle.labs.api.types;

import com.chronicle.labs.api.core.Nullable;
import com.chronicle.labs.api.core.NullableNonemptyFilter;
import com.chronicle.labs.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EnvironmentVersionRecordSpecServicesItem.Builder.class)
public final class EnvironmentVersionRecordSpecServicesItem {
    private final Optional<List<String>> authorities;

    private final String name;

    private final Optional<String> openapiUri;

    private final Map<String, Object> additionalProperties;

    private EnvironmentVersionRecordSpecServicesItem(
            Optional<List<String>> authorities,
            String name,
            Optional<String> openapiUri,
            Map<String, Object> additionalProperties) {
        this.authorities = authorities;
        this.name = name;
        this.openapiUri = openapiUri;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("authorities")
    public Optional<List<String>> getAuthorities() {
        return authorities;
    }

    @JsonProperty("name")
    public String getName() {
        return name;
    }

    @JsonIgnore
    public Optional<String> getOpenapiUri() {
        if (openapiUri == null) {
            return Optional.empty();
        }
        return openapiUri;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("openapiUri")
    private Optional<String> _getOpenapiUri() {
        return openapiUri;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof EnvironmentVersionRecordSpecServicesItem
                && equalTo((EnvironmentVersionRecordSpecServicesItem) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(EnvironmentVersionRecordSpecServicesItem other) {
        return authorities.equals(other.authorities) && name.equals(other.name) && openapiUri.equals(other.openapiUri);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.authorities, this.name, this.openapiUri);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static NameStage builder() {
        return new Builder();
    }

    public interface NameStage {
        _FinalStage name(@NotNull String name);

        Builder from(EnvironmentVersionRecordSpecServicesItem other);
    }

    public interface _FinalStage {
        EnvironmentVersionRecordSpecServicesItem build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage authorities(Optional<List<String>> authorities);

        _FinalStage authorities(List<String> authorities);

        _FinalStage openapiUri(Optional<String> openapiUri);

        _FinalStage openapiUri(String openapiUri);

        _FinalStage openapiUri(Nullable<String> openapiUri);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements NameStage, _FinalStage {
        private String name;

        private Optional<String> openapiUri = Optional.empty();

        private Optional<List<String>> authorities = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(EnvironmentVersionRecordSpecServicesItem other) {
            authorities(other.getAuthorities());
            name(other.getName());
            openapiUri(other.getOpenapiUri());
            return this;
        }

        @java.lang.Override
        @JsonSetter("name")
        public _FinalStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage openapiUri(Nullable<String> openapiUri) {
            if (openapiUri.isNull()) {
                this.openapiUri = null;
            } else if (openapiUri.isEmpty()) {
                this.openapiUri = Optional.empty();
            } else {
                this.openapiUri = Optional.of(openapiUri.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage openapiUri(String openapiUri) {
            this.openapiUri = Optional.ofNullable(openapiUri);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "openapiUri", nulls = Nulls.SKIP)
        public _FinalStage openapiUri(Optional<String> openapiUri) {
            this.openapiUri = openapiUri;
            return this;
        }

        @java.lang.Override
        public _FinalStage authorities(List<String> authorities) {
            this.authorities = Optional.ofNullable(authorities);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "authorities", nulls = Nulls.SKIP)
        public _FinalStage authorities(Optional<List<String>> authorities) {
            this.authorities = authorities;
            return this;
        }

        @java.lang.Override
        public EnvironmentVersionRecordSpecServicesItem build() {
            return new EnvironmentVersionRecordSpecServicesItem(authorities, name, openapiUri, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
