/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.chronicle.labs.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class ErrorResponseCode {
    public static final ErrorResponseCode RATE_LIMITED = new ErrorResponseCode(Value.RATE_LIMITED, "rate_limited");

    public static final ErrorResponseCode VALIDATION_ERROR =
            new ErrorResponseCode(Value.VALIDATION_ERROR, "validation_error");

    public static final ErrorResponseCode UNSUPPORTED_MEDIA_TYPE =
            new ErrorResponseCode(Value.UNSUPPORTED_MEDIA_TYPE, "unsupported_media_type");

    public static final ErrorResponseCode STREAM_REPLAY_LIMIT_EXCEEDED =
            new ErrorResponseCode(Value.STREAM_REPLAY_LIMIT_EXCEEDED, "stream_replay_limit_exceeded");

    public static final ErrorResponseCode SERVICE_OVERLOADED =
            new ErrorResponseCode(Value.SERVICE_OVERLOADED, "service_overloaded");

    public static final ErrorResponseCode SERVICE_UNAVAILABLE =
            new ErrorResponseCode(Value.SERVICE_UNAVAILABLE, "service_unavailable");

    public static final ErrorResponseCode BAD_REQUEST = new ErrorResponseCode(Value.BAD_REQUEST, "bad_request");

    public static final ErrorResponseCode UNAUTHORIZED = new ErrorResponseCode(Value.UNAUTHORIZED, "unauthorized");

    public static final ErrorResponseCode FORBIDDEN = new ErrorResponseCode(Value.FORBIDDEN, "forbidden");

    public static final ErrorResponseCode CONFLICT = new ErrorResponseCode(Value.CONFLICT, "conflict");

    public static final ErrorResponseCode STREAM_UNAVAILABLE =
            new ErrorResponseCode(Value.STREAM_UNAVAILABLE, "stream_unavailable");

    public static final ErrorResponseCode REQUEST_TIMEOUT =
            new ErrorResponseCode(Value.REQUEST_TIMEOUT, "request_timeout");

    public static final ErrorResponseCode INTERNAL_ERROR =
            new ErrorResponseCode(Value.INTERNAL_ERROR, "internal_error");

    public static final ErrorResponseCode PAYLOAD_TOO_LARGE =
            new ErrorResponseCode(Value.PAYLOAD_TOO_LARGE, "payload_too_large");

    public static final ErrorResponseCode STORE_ERROR = new ErrorResponseCode(Value.STORE_ERROR, "store_error");

    public static final ErrorResponseCode NOT_FOUND = new ErrorResponseCode(Value.NOT_FOUND, "not_found");

    public static final ErrorResponseCode STREAM_ERROR = new ErrorResponseCode(Value.STREAM_ERROR, "stream_error");

    private final Value value;

    private final String string;

    ErrorResponseCode(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof ErrorResponseCode && this.string.equals(((ErrorResponseCode) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case RATE_LIMITED:
                return visitor.visitRateLimited();
            case VALIDATION_ERROR:
                return visitor.visitValidationError();
            case UNSUPPORTED_MEDIA_TYPE:
                return visitor.visitUnsupportedMediaType();
            case STREAM_REPLAY_LIMIT_EXCEEDED:
                return visitor.visitStreamReplayLimitExceeded();
            case SERVICE_OVERLOADED:
                return visitor.visitServiceOverloaded();
            case SERVICE_UNAVAILABLE:
                return visitor.visitServiceUnavailable();
            case BAD_REQUEST:
                return visitor.visitBadRequest();
            case UNAUTHORIZED:
                return visitor.visitUnauthorized();
            case FORBIDDEN:
                return visitor.visitForbidden();
            case CONFLICT:
                return visitor.visitConflict();
            case STREAM_UNAVAILABLE:
                return visitor.visitStreamUnavailable();
            case REQUEST_TIMEOUT:
                return visitor.visitRequestTimeout();
            case INTERNAL_ERROR:
                return visitor.visitInternalError();
            case PAYLOAD_TOO_LARGE:
                return visitor.visitPayloadTooLarge();
            case STORE_ERROR:
                return visitor.visitStoreError();
            case NOT_FOUND:
                return visitor.visitNotFound();
            case STREAM_ERROR:
                return visitor.visitStreamError();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static ErrorResponseCode valueOf(String value) {
        switch (value) {
            case "rate_limited":
                return RATE_LIMITED;
            case "validation_error":
                return VALIDATION_ERROR;
            case "unsupported_media_type":
                return UNSUPPORTED_MEDIA_TYPE;
            case "stream_replay_limit_exceeded":
                return STREAM_REPLAY_LIMIT_EXCEEDED;
            case "service_overloaded":
                return SERVICE_OVERLOADED;
            case "service_unavailable":
                return SERVICE_UNAVAILABLE;
            case "bad_request":
                return BAD_REQUEST;
            case "unauthorized":
                return UNAUTHORIZED;
            case "forbidden":
                return FORBIDDEN;
            case "conflict":
                return CONFLICT;
            case "stream_unavailable":
                return STREAM_UNAVAILABLE;
            case "request_timeout":
                return REQUEST_TIMEOUT;
            case "internal_error":
                return INTERNAL_ERROR;
            case "payload_too_large":
                return PAYLOAD_TOO_LARGE;
            case "store_error":
                return STORE_ERROR;
            case "not_found":
                return NOT_FOUND;
            case "stream_error":
                return STREAM_ERROR;
            default:
                return new ErrorResponseCode(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        NOT_FOUND,

        BAD_REQUEST,

        UNAUTHORIZED,

        FORBIDDEN,

        CONFLICT,

        VALIDATION_ERROR,

        UNSUPPORTED_MEDIA_TYPE,

        PAYLOAD_TOO_LARGE,

        RATE_LIMITED,

        STREAM_REPLAY_LIMIT_EXCEEDED,

        STREAM_UNAVAILABLE,

        SERVICE_OVERLOADED,

        SERVICE_UNAVAILABLE,

        REQUEST_TIMEOUT,

        STREAM_ERROR,

        STORE_ERROR,

        INTERNAL_ERROR,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitNotFound();

        T visitBadRequest();

        T visitUnauthorized();

        T visitForbidden();

        T visitConflict();

        T visitValidationError();

        T visitUnsupportedMediaType();

        T visitPayloadTooLarge();

        T visitRateLimited();

        T visitStreamReplayLimitExceeded();

        T visitStreamUnavailable();

        T visitServiceOverloaded();

        T visitServiceUnavailable();

        T visitRequestTimeout();

        T visitStreamError();

        T visitStoreError();

        T visitInternalError();

        T visitUnknown(String unknownType);
    }
}
