/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.chronicle.labs.api.types;

import com.chronicle.labs.api.core.Nullable;
import com.chronicle.labs.api.core.NullableNonemptyFilter;
import com.chronicle.labs.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EventPage.Builder.class)
public final class EventPage {
    private final List<EventResult> data;

    private final boolean hasMore;

    private final Optional<String> nextCursor;

    private final Map<String, Object> additionalProperties;

    private EventPage(
            List<EventResult> data,
            boolean hasMore,
            Optional<String> nextCursor,
            Map<String, Object> additionalProperties) {
        this.data = data;
        this.hasMore = hasMore;
        this.nextCursor = nextCursor;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("data")
    public List<EventResult> getData() {
        return data;
    }

    /**
     * @return Whether a further page exists
     */
    @JsonProperty("has_more")
    public boolean getHasMore() {
        return hasMore;
    }

    /**
     * @return Opaque cursor to pass as <code>cursor</code> on the next request
     */
    @JsonIgnore
    public Optional<String> getNextCursor() {
        if (nextCursor == null) {
            return Optional.empty();
        }
        return nextCursor;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("next_cursor")
    private Optional<String> _getNextCursor() {
        return nextCursor;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof EventPage && equalTo((EventPage) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(EventPage other) {
        return data.equals(other.data) && hasMore == other.hasMore && nextCursor.equals(other.nextCursor);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.data, this.hasMore, this.nextCursor);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static HasMoreStage builder() {
        return new Builder();
    }

    public interface HasMoreStage {
        /**
         * <p>Whether a further page exists</p>
         */
        _FinalStage hasMore(boolean hasMore);

        Builder from(EventPage other);
    }

    public interface _FinalStage {
        EventPage build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage data(List<EventResult> data);

        _FinalStage addData(EventResult data);

        _FinalStage addAllData(List<EventResult> data);

        /**
         * <p>Opaque cursor to pass as <code>cursor</code> on the next request</p>
         */
        _FinalStage nextCursor(Optional<String> nextCursor);

        _FinalStage nextCursor(String nextCursor);

        _FinalStage nextCursor(Nullable<String> nextCursor);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements HasMoreStage, _FinalStage {
        private boolean hasMore;

        private Optional<String> nextCursor = Optional.empty();

        private List<EventResult> data = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(EventPage other) {
            data(other.getData());
            hasMore(other.getHasMore());
            nextCursor(other.getNextCursor());
            return this;
        }

        /**
         * <p>Whether a further page exists</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        @JsonSetter("has_more")
        public _FinalStage hasMore(boolean hasMore) {
            this.hasMore = hasMore;
            return this;
        }

        /**
         * <p>Opaque cursor to pass as <code>cursor</code> on the next request</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage nextCursor(Nullable<String> nextCursor) {
            if (nextCursor.isNull()) {
                this.nextCursor = null;
            } else if (nextCursor.isEmpty()) {
                this.nextCursor = Optional.empty();
            } else {
                this.nextCursor = Optional.of(nextCursor.get());
            }
            return this;
        }

        /**
         * <p>Opaque cursor to pass as <code>cursor</code> on the next request</p>
         * @return Reference to {@code this} so that method calls can be chained together.
         */
        @java.lang.Override
        public _FinalStage nextCursor(String nextCursor) {
            this.nextCursor = Optional.ofNullable(nextCursor);
            return this;
        }

        /**
         * <p>Opaque cursor to pass as <code>cursor</code> on the next request</p>
         */
        @java.lang.Override
        @JsonSetter(value = "next_cursor", nulls = Nulls.SKIP)
        public _FinalStage nextCursor(Optional<String> nextCursor) {
            this.nextCursor = nextCursor;
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllData(List<EventResult> data) {
            if (data != null) {
                this.data.addAll(data);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addData(EventResult data) {
            this.data.add(data);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "data", nulls = Nulls.SKIP)
        public _FinalStage data(List<EventResult> data) {
            this.data.clear();
            if (data != null) {
                this.data.addAll(data);
            }
            return this;
        }

        @java.lang.Override
        public EventPage build() {
            return new EventPage(data, hasMore, nextCursor, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
