/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.chronicle.labs.api.types;

import com.chronicle.labs.api.core.Nullable;
import com.chronicle.labs.api.core.NullableNonemptyFilter;
import com.chronicle.labs.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = EventListResponse.Builder.class)
public final class EventListResponse {
    private final List<EventResult> data;

    private final Optional<String> nextCursor;

    private final Map<String, Object> additionalProperties;

    private EventListResponse(
            List<EventResult> data, Optional<String> nextCursor, Map<String, Object> additionalProperties) {
        this.data = data;
        this.nextCursor = nextCursor;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("data")
    public List<EventResult> getData() {
        return data;
    }

    /**
     * @return Opaque position for the next request.
     */
    @JsonIgnore
    public Optional<String> getNextCursor() {
        if (nextCursor == null) {
            return Optional.empty();
        }
        return nextCursor;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("next_cursor")
    private Optional<String> _getNextCursor() {
        return nextCursor;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof EventListResponse && equalTo((EventListResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(EventListResponse other) {
        return data.equals(other.data) && nextCursor.equals(other.nextCursor);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.data, this.nextCursor);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private List<EventResult> data = new ArrayList<>();

        private Optional<String> nextCursor = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(EventListResponse other) {
            data(other.getData());
            nextCursor(other.getNextCursor());
            return this;
        }

        @JsonSetter(value = "data", nulls = Nulls.SKIP)
        public Builder data(List<EventResult> data) {
            this.data.clear();
            if (data != null) {
                this.data.addAll(data);
            }
            return this;
        }

        public Builder addData(EventResult data) {
            this.data.add(data);
            return this;
        }

        public Builder addAllData(List<EventResult> data) {
            if (data != null) {
                this.data.addAll(data);
            }
            return this;
        }

        /**
         * <p>Opaque position for the next request.</p>
         */
        @JsonSetter(value = "next_cursor", nulls = Nulls.SKIP)
        public Builder nextCursor(Optional<String> nextCursor) {
            this.nextCursor = nextCursor;
            return this;
        }

        public Builder nextCursor(String nextCursor) {
            this.nextCursor = Optional.ofNullable(nextCursor);
            return this;
        }

        public Builder nextCursor(Nullable<String> nextCursor) {
            if (nextCursor.isNull()) {
                this.nextCursor = null;
            } else if (nextCursor.isEmpty()) {
                this.nextCursor = Optional.empty();
            } else {
                this.nextCursor = Optional.of(nextCursor.get());
            }
            return this;
        }

        public EventListResponse build() {
            return new EventListResponse(data, nextCursor, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
