/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.chronicle.labs.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class HashIndexEntryKind {
    public static final HashIndexEntryKind WORKFLOW_GRAPH =
            new HashIndexEntryKind(Value.WORKFLOW_GRAPH, "workflow.graph");

    public static final HashIndexEntryKind AGENT_ROOT = new HashIndexEntryKind(Value.AGENT_ROOT, "agent.root");

    public static final HashIndexEntryKind DEPENDENCY = new HashIndexEntryKind(Value.DEPENDENCY, "dependency");

    public static final HashIndexEntryKind EFFECTIVE_RUN = new HashIndexEntryKind(Value.EFFECTIVE_RUN, "effective.run");

    public static final HashIndexEntryKind MODEL_CONTRACT =
            new HashIndexEntryKind(Value.MODEL_CONTRACT, "model.contract");

    public static final HashIndexEntryKind OUTPUT = new HashIndexEntryKind(Value.OUTPUT, "output");

    public static final HashIndexEntryKind RUNTIME_POLICY =
            new HashIndexEntryKind(Value.RUNTIME_POLICY, "runtime.policy");

    public static final HashIndexEntryKind PROVIDER_OBSERVATION =
            new HashIndexEntryKind(Value.PROVIDER_OBSERVATION, "provider.observation");

    public static final HashIndexEntryKind PROVIDER_OPTIONS =
            new HashIndexEntryKind(Value.PROVIDER_OPTIONS, "provider.options");

    public static final HashIndexEntryKind OPERATIONAL = new HashIndexEntryKind(Value.OPERATIONAL, "operational");

    public static final HashIndexEntryKind KNOWLEDGE_CONTRACT =
            new HashIndexEntryKind(Value.KNOWLEDGE_CONTRACT, "knowledge.contract");

    public static final HashIndexEntryKind TOOL_CONTRACT = new HashIndexEntryKind(Value.TOOL_CONTRACT, "tool.contract");

    public static final HashIndexEntryKind PROMPT = new HashIndexEntryKind(Value.PROMPT, "prompt");

    private final Value value;

    private final String string;

    HashIndexEntryKind(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof HashIndexEntryKind && this.string.equals(((HashIndexEntryKind) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case WORKFLOW_GRAPH:
                return visitor.visitWorkflowGraph();
            case AGENT_ROOT:
                return visitor.visitAgentRoot();
            case DEPENDENCY:
                return visitor.visitDependency();
            case EFFECTIVE_RUN:
                return visitor.visitEffectiveRun();
            case MODEL_CONTRACT:
                return visitor.visitModelContract();
            case OUTPUT:
                return visitor.visitOutput();
            case RUNTIME_POLICY:
                return visitor.visitRuntimePolicy();
            case PROVIDER_OBSERVATION:
                return visitor.visitProviderObservation();
            case PROVIDER_OPTIONS:
                return visitor.visitProviderOptions();
            case OPERATIONAL:
                return visitor.visitOperational();
            case KNOWLEDGE_CONTRACT:
                return visitor.visitKnowledgeContract();
            case TOOL_CONTRACT:
                return visitor.visitToolContract();
            case PROMPT:
                return visitor.visitPrompt();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static HashIndexEntryKind valueOf(String value) {
        switch (value) {
            case "workflow.graph":
                return WORKFLOW_GRAPH;
            case "agent.root":
                return AGENT_ROOT;
            case "dependency":
                return DEPENDENCY;
            case "effective.run":
                return EFFECTIVE_RUN;
            case "model.contract":
                return MODEL_CONTRACT;
            case "output":
                return OUTPUT;
            case "runtime.policy":
                return RUNTIME_POLICY;
            case "provider.observation":
                return PROVIDER_OBSERVATION;
            case "provider.options":
                return PROVIDER_OPTIONS;
            case "operational":
                return OPERATIONAL;
            case "knowledge.contract":
                return KNOWLEDGE_CONTRACT;
            case "tool.contract":
                return TOOL_CONTRACT;
            case "prompt":
                return PROMPT;
            default:
                return new HashIndexEntryKind(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        AGENT_ROOT,

        PROMPT,

        MODEL_CONTRACT,

        PROVIDER_OPTIONS,

        TOOL_CONTRACT,

        RUNTIME_POLICY,

        DEPENDENCY,

        KNOWLEDGE_CONTRACT,

        WORKFLOW_GRAPH,

        EFFECTIVE_RUN,

        PROVIDER_OBSERVATION,

        OPERATIONAL,

        OUTPUT,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitAgentRoot();

        T visitPrompt();

        T visitModelContract();

        T visitProviderOptions();

        T visitToolContract();

        T visitRuntimePolicy();

        T visitDependency();

        T visitKnowledgeContract();

        T visitWorkflowGraph();

        T visitEffectiveRun();

        T visitProviderObservation();

        T visitOperational();

        T visitOutput();

        T visitUnknown(String unknownType);
    }
}
