/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.chronicle.labs.api.types;

import com.chronicle.labs.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = ListEnvironmentsResponseEnvironmentsItem.Builder.class)
public final class ListEnvironmentsResponseEnvironmentsItem {
    private final EnvironmentRecord environment;

    private final List<EnvironmentVersionRecord> versions;

    private final Map<String, Object> additionalProperties;

    private ListEnvironmentsResponseEnvironmentsItem(
            EnvironmentRecord environment,
            List<EnvironmentVersionRecord> versions,
            Map<String, Object> additionalProperties) {
        this.environment = environment;
        this.versions = versions;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("environment")
    public EnvironmentRecord getEnvironment() {
        return environment;
    }

    @JsonProperty("versions")
    public List<EnvironmentVersionRecord> getVersions() {
        return versions;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof ListEnvironmentsResponseEnvironmentsItem
                && equalTo((ListEnvironmentsResponseEnvironmentsItem) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(ListEnvironmentsResponseEnvironmentsItem other) {
        return environment.equals(other.environment) && versions.equals(other.versions);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.environment, this.versions);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static EnvironmentStage builder() {
        return new Builder();
    }

    public interface EnvironmentStage {
        _FinalStage environment(@NotNull EnvironmentRecord environment);

        Builder from(ListEnvironmentsResponseEnvironmentsItem other);
    }

    public interface _FinalStage {
        ListEnvironmentsResponseEnvironmentsItem build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage versions(List<EnvironmentVersionRecord> versions);

        _FinalStage addVersions(EnvironmentVersionRecord versions);

        _FinalStage addAllVersions(List<EnvironmentVersionRecord> versions);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder implements EnvironmentStage, _FinalStage {
        private EnvironmentRecord environment;

        private List<EnvironmentVersionRecord> versions = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(ListEnvironmentsResponseEnvironmentsItem other) {
            environment(other.getEnvironment());
            versions(other.getVersions());
            return this;
        }

        @java.lang.Override
        @JsonSetter("environment")
        public _FinalStage environment(@NotNull EnvironmentRecord environment) {
            this.environment = Objects.requireNonNull(environment, "environment must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllVersions(List<EnvironmentVersionRecord> versions) {
            if (versions != null) {
                this.versions.addAll(versions);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addVersions(EnvironmentVersionRecord versions) {
            this.versions.add(versions);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "versions", nulls = Nulls.SKIP)
        public _FinalStage versions(List<EnvironmentVersionRecord> versions) {
            this.versions.clear();
            if (versions != null) {
                this.versions.addAll(versions);
            }
            return this;
        }

        @java.lang.Override
        public ListEnvironmentsResponseEnvironmentsItem build() {
            return new ListEnvironmentsResponseEnvironmentsItem(environment, versions, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
