/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.chronicle.labs.api.types;

import com.chronicle.labs.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SdkKeyListResponse.Builder.class)
public final class SdkKeyListResponse {
    private final List<SdkKey> keys;

    private final Map<String, Object> additionalProperties;

    private SdkKeyListResponse(List<SdkKey> keys, Map<String, Object> additionalProperties) {
        this.keys = keys;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("keys")
    public List<SdkKey> getKeys() {
        return keys;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SdkKeyListResponse && equalTo((SdkKeyListResponse) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(SdkKeyListResponse other) {
        return keys.equals(other.keys);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(this.keys);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static Builder builder() {
        return new Builder();
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder {
        private List<SdkKey> keys = new ArrayList<>();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        public Builder from(SdkKeyListResponse other) {
            keys(other.getKeys());
            return this;
        }

        @JsonSetter(value = "keys", nulls = Nulls.SKIP)
        public Builder keys(List<SdkKey> keys) {
            this.keys.clear();
            if (keys != null) {
                this.keys.addAll(keys);
            }
            return this;
        }

        public Builder addKeys(SdkKey keys) {
            this.keys.add(keys);
            return this;
        }

        public Builder addAllKeys(List<SdkKey> keys) {
            if (keys != null) {
                this.keys.addAll(keys);
            }
            return this;
        }

        public SdkKeyListResponse build() {
            return new SdkKeyListResponse(keys, additionalProperties);
        }

        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
