/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.chronicle.labs.api.types;

import com.chronicle.labs.api.core.Nullable;
import com.chronicle.labs.api.core.NullableNonemptyFilter;
import com.chronicle.labs.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(builder = SdkKey.Builder.class)
public final class SdkKey implements ISdkKey {
    private final OffsetDateTime createdAt;

    private final String id;

    private final Optional<OffsetDateTime> lastUsedAt;

    private final String name;

    private final String prefix;

    private final Optional<OffsetDateTime> revokedAt;

    private final List<String> scopes;

    private final String tenantId;

    private final Map<String, Object> additionalProperties;

    private SdkKey(
            OffsetDateTime createdAt,
            String id,
            Optional<OffsetDateTime> lastUsedAt,
            String name,
            String prefix,
            Optional<OffsetDateTime> revokedAt,
            List<String> scopes,
            String tenantId,
            Map<String, Object> additionalProperties) {
        this.createdAt = createdAt;
        this.id = id;
        this.lastUsedAt = lastUsedAt;
        this.name = name;
        this.prefix = prefix;
        this.revokedAt = revokedAt;
        this.scopes = scopes;
        this.tenantId = tenantId;
        this.additionalProperties = additionalProperties;
    }

    @JsonProperty("createdAt")
    @java.lang.Override
    public OffsetDateTime getCreatedAt() {
        return createdAt;
    }

    @JsonProperty("id")
    @java.lang.Override
    public String getId() {
        return id;
    }

    @JsonIgnore
    @java.lang.Override
    public Optional<OffsetDateTime> getLastUsedAt() {
        if (lastUsedAt == null) {
            return Optional.empty();
        }
        return lastUsedAt;
    }

    @JsonProperty("name")
    @java.lang.Override
    public String getName() {
        return name;
    }

    @JsonProperty("prefix")
    @java.lang.Override
    public String getPrefix() {
        return prefix;
    }

    @JsonIgnore
    @java.lang.Override
    public Optional<OffsetDateTime> getRevokedAt() {
        if (revokedAt == null) {
            return Optional.empty();
        }
        return revokedAt;
    }

    @JsonProperty("scopes")
    @java.lang.Override
    public List<String> getScopes() {
        return scopes;
    }

    @JsonProperty("tenantId")
    @java.lang.Override
    public String getTenantId() {
        return tenantId;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("lastUsedAt")
    private Optional<OffsetDateTime> _getLastUsedAt() {
        return lastUsedAt;
    }

    @JsonInclude(value = JsonInclude.Include.CUSTOM, valueFilter = NullableNonemptyFilter.class)
    @JsonProperty("revokedAt")
    private Optional<OffsetDateTime> _getRevokedAt() {
        return revokedAt;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        if (this == other) return true;
        return other instanceof SdkKey && equalTo((SdkKey) other);
    }

    @JsonAnyGetter
    public Map<String, Object> getAdditionalProperties() {
        return this.additionalProperties;
    }

    private boolean equalTo(SdkKey other) {
        return createdAt.equals(other.createdAt)
                && id.equals(other.id)
                && lastUsedAt.equals(other.lastUsedAt)
                && name.equals(other.name)
                && prefix.equals(other.prefix)
                && revokedAt.equals(other.revokedAt)
                && scopes.equals(other.scopes)
                && tenantId.equals(other.tenantId);
    }

    @java.lang.Override
    public int hashCode() {
        return Objects.hash(
                this.createdAt,
                this.id,
                this.lastUsedAt,
                this.name,
                this.prefix,
                this.revokedAt,
                this.scopes,
                this.tenantId);
    }

    @java.lang.Override
    public String toString() {
        return ObjectMappers.stringify(this);
    }

    public static CreatedAtStage builder() {
        return new Builder();
    }

    public interface CreatedAtStage {
        IdStage createdAt(@NotNull OffsetDateTime createdAt);

        Builder from(SdkKey other);
    }

    public interface IdStage {
        NameStage id(@NotNull String id);
    }

    public interface NameStage {
        PrefixStage name(@NotNull String name);
    }

    public interface PrefixStage {
        TenantIdStage prefix(@NotNull String prefix);
    }

    public interface TenantIdStage {
        _FinalStage tenantId(@NotNull String tenantId);
    }

    public interface _FinalStage {
        SdkKey build();

        _FinalStage additionalProperty(String key, Object value);

        _FinalStage additionalProperties(Map<String, Object> additionalProperties);

        _FinalStage lastUsedAt(Optional<OffsetDateTime> lastUsedAt);

        _FinalStage lastUsedAt(OffsetDateTime lastUsedAt);

        _FinalStage lastUsedAt(Nullable<OffsetDateTime> lastUsedAt);

        _FinalStage revokedAt(Optional<OffsetDateTime> revokedAt);

        _FinalStage revokedAt(OffsetDateTime revokedAt);

        _FinalStage revokedAt(Nullable<OffsetDateTime> revokedAt);

        _FinalStage scopes(List<String> scopes);

        _FinalStage addScopes(String scopes);

        _FinalStage addAllScopes(List<String> scopes);
    }

    @JsonIgnoreProperties(ignoreUnknown = true)
    public static final class Builder
            implements CreatedAtStage, IdStage, NameStage, PrefixStage, TenantIdStage, _FinalStage {
        private OffsetDateTime createdAt;

        private String id;

        private String name;

        private String prefix;

        private String tenantId;

        private List<String> scopes = new ArrayList<>();

        private Optional<OffsetDateTime> revokedAt = Optional.empty();

        private Optional<OffsetDateTime> lastUsedAt = Optional.empty();

        @JsonAnySetter
        private Map<String, Object> additionalProperties = new HashMap<>();

        private Builder() {}

        @java.lang.Override
        public Builder from(SdkKey other) {
            createdAt(other.getCreatedAt());
            id(other.getId());
            lastUsedAt(other.getLastUsedAt());
            name(other.getName());
            prefix(other.getPrefix());
            revokedAt(other.getRevokedAt());
            scopes(other.getScopes());
            tenantId(other.getTenantId());
            return this;
        }

        @java.lang.Override
        @JsonSetter("createdAt")
        public IdStage createdAt(@NotNull OffsetDateTime createdAt) {
            this.createdAt = Objects.requireNonNull(createdAt, "createdAt must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("id")
        public NameStage id(@NotNull String id) {
            this.id = Objects.requireNonNull(id, "id must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("name")
        public PrefixStage name(@NotNull String name) {
            this.name = Objects.requireNonNull(name, "name must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("prefix")
        public TenantIdStage prefix(@NotNull String prefix) {
            this.prefix = Objects.requireNonNull(prefix, "prefix must not be null");
            return this;
        }

        @java.lang.Override
        @JsonSetter("tenantId")
        public _FinalStage tenantId(@NotNull String tenantId) {
            this.tenantId = Objects.requireNonNull(tenantId, "tenantId must not be null");
            return this;
        }

        @java.lang.Override
        public _FinalStage addAllScopes(List<String> scopes) {
            if (scopes != null) {
                this.scopes.addAll(scopes);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage addScopes(String scopes) {
            this.scopes.add(scopes);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "scopes", nulls = Nulls.SKIP)
        public _FinalStage scopes(List<String> scopes) {
            this.scopes.clear();
            if (scopes != null) {
                this.scopes.addAll(scopes);
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage revokedAt(Nullable<OffsetDateTime> revokedAt) {
            if (revokedAt.isNull()) {
                this.revokedAt = null;
            } else if (revokedAt.isEmpty()) {
                this.revokedAt = Optional.empty();
            } else {
                this.revokedAt = Optional.of(revokedAt.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage revokedAt(OffsetDateTime revokedAt) {
            this.revokedAt = Optional.ofNullable(revokedAt);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "revokedAt", nulls = Nulls.SKIP)
        public _FinalStage revokedAt(Optional<OffsetDateTime> revokedAt) {
            this.revokedAt = revokedAt;
            return this;
        }

        @java.lang.Override
        public _FinalStage lastUsedAt(Nullable<OffsetDateTime> lastUsedAt) {
            if (lastUsedAt.isNull()) {
                this.lastUsedAt = null;
            } else if (lastUsedAt.isEmpty()) {
                this.lastUsedAt = Optional.empty();
            } else {
                this.lastUsedAt = Optional.of(lastUsedAt.get());
            }
            return this;
        }

        @java.lang.Override
        public _FinalStage lastUsedAt(OffsetDateTime lastUsedAt) {
            this.lastUsedAt = Optional.ofNullable(lastUsedAt);
            return this;
        }

        @java.lang.Override
        @JsonSetter(value = "lastUsedAt", nulls = Nulls.SKIP)
        public _FinalStage lastUsedAt(Optional<OffsetDateTime> lastUsedAt) {
            this.lastUsedAt = lastUsedAt;
            return this;
        }

        @java.lang.Override
        public SdkKey build() {
            return new SdkKey(
                    createdAt, id, lastUsedAt, name, prefix, revokedAt, scopes, tenantId, additionalProperties);
        }

        @java.lang.Override
        public Builder additionalProperty(String key, Object value) {
            this.additionalProperties.put(key, value);
            return this;
        }

        @java.lang.Override
        public Builder additionalProperties(Map<String, Object> additionalProperties) {
            this.additionalProperties.putAll(additionalProperties);
            return this;
        }
    }
}
