/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.chronicle.labs.api.types;

import com.chronicle.labs.api.core.Nullable;
import com.chronicle.labs.api.core.NullableNonemptyFilter;
import com.chronicle.labs.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Object;
import java.lang.String;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import org.jetbrains.annotations.NotNull;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = SourceInfo.Builder.class
)
public final class SourceInfo {
  private final String source;

  private final List<String> eventTypes;

  private final long eventCount;

  private final Optional<OffsetDateTime> firstSeen;

  private final Optional<OffsetDateTime> lastSeen;

  private final Map<String, Object> additionalProperties;

  private SourceInfo(String source, List<String> eventTypes, long eventCount,
      Optional<OffsetDateTime> firstSeen, Optional<OffsetDateTime> lastSeen,
      Map<String, Object> additionalProperties) {
    this.source = source;
    this.eventTypes = eventTypes;
    this.eventCount = eventCount;
    this.firstSeen = firstSeen;
    this.lastSeen = lastSeen;
    this.additionalProperties = additionalProperties;
  }

  @JsonProperty("source")
  public String getSource() {
    return source;
  }

  @JsonProperty("event_types")
  public List<String> getEventTypes() {
    return eventTypes;
  }

  @JsonProperty("event_count")
  public long getEventCount() {
    return eventCount;
  }

  @JsonIgnore
  public Optional<OffsetDateTime> getFirstSeen() {
    if (firstSeen == null) {
      return Optional.empty();
    }
    return firstSeen;
  }

  @JsonIgnore
  public Optional<OffsetDateTime> getLastSeen() {
    if (lastSeen == null) {
      return Optional.empty();
    }
    return lastSeen;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("first_seen")
  private Optional<OffsetDateTime> _getFirstSeen() {
    return firstSeen;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("last_seen")
  private Optional<OffsetDateTime> _getLastSeen() {
    return lastSeen;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof SourceInfo && equalTo((SourceInfo) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(SourceInfo other) {
    return source.equals(other.source) && eventTypes.equals(other.eventTypes) && eventCount == other.eventCount && firstSeen.equals(other.firstSeen) && lastSeen.equals(other.lastSeen);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.source, this.eventTypes, this.eventCount, this.firstSeen, this.lastSeen);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static SourceStage builder() {
    return new Builder();
  }

  public interface SourceStage {
    EventCountStage source(@NotNull String source);

    Builder from(SourceInfo other);
  }

  public interface EventCountStage {
    _FinalStage eventCount(long eventCount);
  }

  public interface _FinalStage {
    SourceInfo build();

    _FinalStage additionalProperty(String key, Object value);

    _FinalStage additionalProperties(Map<String, Object> additionalProperties);

    _FinalStage eventTypes(List<String> eventTypes);

    _FinalStage addEventTypes(String eventTypes);

    _FinalStage addAllEventTypes(List<String> eventTypes);

    _FinalStage firstSeen(Optional<OffsetDateTime> firstSeen);

    _FinalStage firstSeen(OffsetDateTime firstSeen);

    _FinalStage firstSeen(Nullable<OffsetDateTime> firstSeen);

    _FinalStage lastSeen(Optional<OffsetDateTime> lastSeen);

    _FinalStage lastSeen(OffsetDateTime lastSeen);

    _FinalStage lastSeen(Nullable<OffsetDateTime> lastSeen);
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder implements SourceStage, EventCountStage, _FinalStage {
    private String source;

    private long eventCount;

    private Optional<OffsetDateTime> lastSeen = Optional.empty();

    private Optional<OffsetDateTime> firstSeen = Optional.empty();

    private List<String> eventTypes = new ArrayList<>();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    @java.lang.Override
    public Builder from(SourceInfo other) {
      source(other.getSource());
      eventTypes(other.getEventTypes());
      eventCount(other.getEventCount());
      firstSeen(other.getFirstSeen());
      lastSeen(other.getLastSeen());
      return this;
    }

    @java.lang.Override
    @JsonSetter("source")
    public EventCountStage source(@NotNull String source) {
      this.source = Objects.requireNonNull(source, "source must not be null");
      return this;
    }

    @java.lang.Override
    @JsonSetter("event_count")
    public _FinalStage eventCount(long eventCount) {
      this.eventCount = eventCount;
      return this;
    }

    @java.lang.Override
    public _FinalStage lastSeen(Nullable<OffsetDateTime> lastSeen) {
      if (lastSeen.isNull()) {
        this.lastSeen = null;
      }
      else if (lastSeen.isEmpty()) {
        this.lastSeen = Optional.empty();
      }
      else {
        this.lastSeen = Optional.of(lastSeen.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage lastSeen(OffsetDateTime lastSeen) {
      this.lastSeen = Optional.ofNullable(lastSeen);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "last_seen",
        nulls = Nulls.SKIP
    )
    public _FinalStage lastSeen(Optional<OffsetDateTime> lastSeen) {
      this.lastSeen = lastSeen;
      return this;
    }

    @java.lang.Override
    public _FinalStage firstSeen(Nullable<OffsetDateTime> firstSeen) {
      if (firstSeen.isNull()) {
        this.firstSeen = null;
      }
      else if (firstSeen.isEmpty()) {
        this.firstSeen = Optional.empty();
      }
      else {
        this.firstSeen = Optional.of(firstSeen.get());
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage firstSeen(OffsetDateTime firstSeen) {
      this.firstSeen = Optional.ofNullable(firstSeen);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "first_seen",
        nulls = Nulls.SKIP
    )
    public _FinalStage firstSeen(Optional<OffsetDateTime> firstSeen) {
      this.firstSeen = firstSeen;
      return this;
    }

    @java.lang.Override
    public _FinalStage addAllEventTypes(List<String> eventTypes) {
      if (eventTypes != null) {
        this.eventTypes.addAll(eventTypes);
      }
      return this;
    }

    @java.lang.Override
    public _FinalStage addEventTypes(String eventTypes) {
      this.eventTypes.add(eventTypes);
      return this;
    }

    @java.lang.Override
    @JsonSetter(
        value = "event_types",
        nulls = Nulls.SKIP
    )
    public _FinalStage eventTypes(List<String> eventTypes) {
      this.eventTypes.clear();
      if (eventTypes != null) {
        this.eventTypes.addAll(eventTypes);
      }
      return this;
    }

    @java.lang.Override
    public SourceInfo build() {
      return new SourceInfo(source, eventTypes, eventCount, firstSeen, lastSeen, additionalProperties);
    }

    @java.lang.Override
    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    @java.lang.Override
    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
