/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.chronicle.labs.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

public final class TaskSuiteSnapshotTracesItemStatus {
    public static final TaskSuiteSnapshotTracesItemStatus WARN =
            new TaskSuiteSnapshotTracesItemStatus(Value.WARN, "warn");

    public static final TaskSuiteSnapshotTracesItemStatus OK = new TaskSuiteSnapshotTracesItemStatus(Value.OK, "ok");

    public static final TaskSuiteSnapshotTracesItemStatus ERROR =
            new TaskSuiteSnapshotTracesItemStatus(Value.ERROR, "error");

    private final Value value;

    private final String string;

    TaskSuiteSnapshotTracesItemStatus(Value value, String string) {
        this.value = value;
        this.string = string;
    }

    public Value getEnumValue() {
        return value;
    }

    @java.lang.Override
    @JsonValue
    public String toString() {
        return this.string;
    }

    @java.lang.Override
    public boolean equals(Object other) {
        return (this == other)
                || (other instanceof TaskSuiteSnapshotTracesItemStatus
                        && this.string.equals(((TaskSuiteSnapshotTracesItemStatus) other).string));
    }

    @java.lang.Override
    public int hashCode() {
        return this.string.hashCode();
    }

    public <T> T visit(Visitor<T> visitor) {
        switch (value) {
            case WARN:
                return visitor.visitWarn();
            case OK:
                return visitor.visitOk();
            case ERROR:
                return visitor.visitError();
            case UNKNOWN:
            default:
                return visitor.visitUnknown(string);
        }
    }

    @JsonCreator(mode = JsonCreator.Mode.DELEGATING)
    public static TaskSuiteSnapshotTracesItemStatus valueOf(String value) {
        switch (value) {
            case "warn":
                return WARN;
            case "ok":
                return OK;
            case "error":
                return ERROR;
            default:
                return new TaskSuiteSnapshotTracesItemStatus(Value.UNKNOWN, value);
        }
    }

    public enum Value {
        OK,

        WARN,

        ERROR,

        UNKNOWN
    }

    public interface Visitor<T> {
        T visitOk();

        T visitWarn();

        T visitError();

        T visitUnknown(String unknownType);
    }
}
