/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.chronicle.labs.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class TaskSplit {
  public static final TaskSplit VALIDATION = new TaskSplit(Value.VALIDATION, "validation");

  public static final TaskSplit TRAIN = new TaskSplit(Value.TRAIN, "train");

  public static final TaskSplit TEST = new TaskSplit(Value.TEST, "test");

  private final Value value;

  private final String string;

  TaskSplit(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof TaskSplit && this.string.equals(((TaskSplit) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case VALIDATION:
        return visitor.visitValidation();
      case TRAIN:
        return visitor.visitTrain();
      case TEST:
        return visitor.visitTest();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static TaskSplit valueOf(String value) {
    switch (value) {
      case "validation":
        return VALIDATION;
      case "train":
        return TRAIN;
      case "test":
        return TEST;
      default:
        return new TaskSplit(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    TRAIN,

    VALIDATION,

    TEST,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitTrain();

    T visitValidation();

    T visitTest();

    T visitUnknown(String unknownType);
  }
}
