/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.chronicle.labs.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class TaskSubjectKind {
  public static final TaskSubjectKind TRACE = new TaskSubjectKind(Value.TRACE, "trace");

  public static final TaskSubjectKind EVENT = new TaskSubjectKind(Value.EVENT, "event");

  public static final TaskSubjectKind TASK = new TaskSubjectKind(Value.TASK, "task");

  private final Value value;

  private final String string;

  TaskSubjectKind(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof TaskSubjectKind && this.string.equals(((TaskSubjectKind) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case TRACE:
        return visitor.visitTrace();
      case EVENT:
        return visitor.visitEvent();
      case TASK:
        return visitor.visitTask();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static TaskSubjectKind valueOf(String value) {
    switch (value) {
      case "trace":
        return TRACE;
      case "event":
        return EVENT;
      case "task":
        return TASK;
      default:
        return new TaskSubjectKind(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    TRACE,

    EVENT,

    TASK,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitTrace();

    T visitEvent();

    T visitTask();

    T visitUnknown(String unknownType);
  }
}
