/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.chronicle.labs.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class TaskPageItemsItemTaskConfigNetworkMode {
  public static final TaskPageItemsItemTaskConfigNetworkMode PUBLIC = new TaskPageItemsItemTaskConfigNetworkMode(Value.PUBLIC, "public");

  public static final TaskPageItemsItemTaskConfigNetworkMode NO_NETWORK = new TaskPageItemsItemTaskConfigNetworkMode(Value.NO_NETWORK, "no-network");

  private final Value value;

  private final String string;

  TaskPageItemsItemTaskConfigNetworkMode(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof TaskPageItemsItemTaskConfigNetworkMode && this.string.equals(((TaskPageItemsItemTaskConfigNetworkMode) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case PUBLIC:
        return visitor.visitPublic();
      case NO_NETWORK:
        return visitor.visitNoNetwork();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static TaskPageItemsItemTaskConfigNetworkMode valueOf(String value) {
    switch (value) {
      case "public":
        return PUBLIC;
      case "no-network":
        return NO_NETWORK;
      default:
        return new TaskPageItemsItemTaskConfigNetworkMode(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    PUBLIC,

    NO_NETWORK,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitPublic();

    T visitNoNetwork();

    T visitUnknown(String unknownType);
  }
}
