/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.chronicle.labs.api.types;

import com.chronicle.labs.api.core.Nullable;
import com.chronicle.labs.api.core.NullableNonemptyFilter;
import com.chronicle.labs.api.core.ObjectMappers;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.annotation.Nulls;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import java.lang.Double;
import java.lang.Object;
import java.lang.String;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;

@JsonInclude(JsonInclude.Include.NON_ABSENT)
@JsonDeserialize(
    builder = TaskTaskConfig.Builder.class
)
public final class TaskTaskConfig {
  private final Optional<Double> agentTimeoutSec;

  private final Optional<TaskTaskConfigNetworkMode> networkMode;

  private final Optional<Double> verifierTimeoutSec;

  private final Map<String, Object> additionalProperties;

  private TaskTaskConfig(Optional<Double> agentTimeoutSec,
      Optional<TaskTaskConfigNetworkMode> networkMode, Optional<Double> verifierTimeoutSec,
      Map<String, Object> additionalProperties) {
    this.agentTimeoutSec = agentTimeoutSec;
    this.networkMode = networkMode;
    this.verifierTimeoutSec = verifierTimeoutSec;
    this.additionalProperties = additionalProperties;
  }

  @JsonIgnore
  public Optional<Double> getAgentTimeoutSec() {
    if (agentTimeoutSec == null) {
      return Optional.empty();
    }
    return agentTimeoutSec;
  }

  /**
   * @return Network policy for the agent sandbox, mirroring Harbor's <code>[environment].network_mode</code>.
   */
  @JsonIgnore
  public Optional<TaskTaskConfigNetworkMode> getNetworkMode() {
    if (networkMode == null) {
      return Optional.empty();
    }
    return networkMode;
  }

  @JsonIgnore
  public Optional<Double> getVerifierTimeoutSec() {
    if (verifierTimeoutSec == null) {
      return Optional.empty();
    }
    return verifierTimeoutSec;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("agentTimeoutSec")
  private Optional<Double> _getAgentTimeoutSec() {
    return agentTimeoutSec;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("networkMode")
  private Optional<TaskTaskConfigNetworkMode> _getNetworkMode() {
    return networkMode;
  }

  @JsonInclude(
      value = JsonInclude.Include.CUSTOM,
      valueFilter = NullableNonemptyFilter.class
  )
  @JsonProperty("verifierTimeoutSec")
  private Optional<Double> _getVerifierTimeoutSec() {
    return verifierTimeoutSec;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    if (this == other) return true;
    return other instanceof TaskTaskConfig && equalTo((TaskTaskConfig) other);
  }

  @JsonAnyGetter
  public Map<String, Object> getAdditionalProperties() {
    return this.additionalProperties;
  }

  private boolean equalTo(TaskTaskConfig other) {
    return agentTimeoutSec.equals(other.agentTimeoutSec) && networkMode.equals(other.networkMode) && verifierTimeoutSec.equals(other.verifierTimeoutSec);
  }

  @java.lang.Override
  public int hashCode() {
    return Objects.hash(this.agentTimeoutSec, this.networkMode, this.verifierTimeoutSec);
  }

  @java.lang.Override
  public String toString() {
    return ObjectMappers.stringify(this);
  }

  public static Builder builder() {
    return new Builder();
  }

  @JsonIgnoreProperties(
      ignoreUnknown = true
  )
  public static final class Builder {
    private Optional<Double> agentTimeoutSec = Optional.empty();

    private Optional<TaskTaskConfigNetworkMode> networkMode = Optional.empty();

    private Optional<Double> verifierTimeoutSec = Optional.empty();

    @JsonAnySetter
    private Map<String, Object> additionalProperties = new HashMap<>();

    private Builder() {
    }

    public Builder from(TaskTaskConfig other) {
      agentTimeoutSec(other.getAgentTimeoutSec());
      networkMode(other.getNetworkMode());
      verifierTimeoutSec(other.getVerifierTimeoutSec());
      return this;
    }

    @JsonSetter(
        value = "agentTimeoutSec",
        nulls = Nulls.SKIP
    )
    public Builder agentTimeoutSec(Optional<Double> agentTimeoutSec) {
      this.agentTimeoutSec = agentTimeoutSec;
      return this;
    }

    public Builder agentTimeoutSec(Double agentTimeoutSec) {
      this.agentTimeoutSec = Optional.ofNullable(agentTimeoutSec);
      return this;
    }

    public Builder agentTimeoutSec(Nullable<Double> agentTimeoutSec) {
      if (agentTimeoutSec.isNull()) {
        this.agentTimeoutSec = null;
      }
      else if (agentTimeoutSec.isEmpty()) {
        this.agentTimeoutSec = Optional.empty();
      }
      else {
        this.agentTimeoutSec = Optional.of(agentTimeoutSec.get());
      }
      return this;
    }

    /**
     * <p>Network policy for the agent sandbox, mirroring Harbor's <code>[environment].network_mode</code>.</p>
     */
    @JsonSetter(
        value = "networkMode",
        nulls = Nulls.SKIP
    )
    public Builder networkMode(Optional<TaskTaskConfigNetworkMode> networkMode) {
      this.networkMode = networkMode;
      return this;
    }

    public Builder networkMode(TaskTaskConfigNetworkMode networkMode) {
      this.networkMode = Optional.ofNullable(networkMode);
      return this;
    }

    public Builder networkMode(Nullable<TaskTaskConfigNetworkMode> networkMode) {
      if (networkMode.isNull()) {
        this.networkMode = null;
      }
      else if (networkMode.isEmpty()) {
        this.networkMode = Optional.empty();
      }
      else {
        this.networkMode = Optional.of(networkMode.get());
      }
      return this;
    }

    @JsonSetter(
        value = "verifierTimeoutSec",
        nulls = Nulls.SKIP
    )
    public Builder verifierTimeoutSec(Optional<Double> verifierTimeoutSec) {
      this.verifierTimeoutSec = verifierTimeoutSec;
      return this;
    }

    public Builder verifierTimeoutSec(Double verifierTimeoutSec) {
      this.verifierTimeoutSec = Optional.ofNullable(verifierTimeoutSec);
      return this;
    }

    public Builder verifierTimeoutSec(Nullable<Double> verifierTimeoutSec) {
      if (verifierTimeoutSec.isNull()) {
        this.verifierTimeoutSec = null;
      }
      else if (verifierTimeoutSec.isEmpty()) {
        this.verifierTimeoutSec = Optional.empty();
      }
      else {
        this.verifierTimeoutSec = Optional.of(verifierTimeoutSec.get());
      }
      return this;
    }

    public TaskTaskConfig build() {
      return new TaskTaskConfig(agentTimeoutSec, networkMode, verifierTimeoutSec, additionalProperties);
    }

    public Builder additionalProperty(String key, Object value) {
      this.additionalProperties.put(key, value);
      return this;
    }

    public Builder additionalProperties(Map<String, Object> additionalProperties) {
      this.additionalProperties.putAll(additionalProperties);
      return this;
    }
  }
}
