/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.chronicle.labs.api.types;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.Object;
import java.lang.String;

public final class TrialEventJobFinishedStatus {
  public static final TrialEventJobFinishedStatus FAILED = new TrialEventJobFinishedStatus(Value.FAILED, "failed");

  public static final TrialEventJobFinishedStatus SUCCEEDED = new TrialEventJobFinishedStatus(Value.SUCCEEDED, "succeeded");

  public static final TrialEventJobFinishedStatus PENDING = new TrialEventJobFinishedStatus(Value.PENDING, "pending");

  public static final TrialEventJobFinishedStatus CANCELLED = new TrialEventJobFinishedStatus(Value.CANCELLED, "cancelled");

  public static final TrialEventJobFinishedStatus RUNNING = new TrialEventJobFinishedStatus(Value.RUNNING, "running");

  private final Value value;

  private final String string;

  TrialEventJobFinishedStatus(Value value, String string) {
    this.value = value;
    this.string = string;
  }

  public Value getEnumValue() {
    return value;
  }

  @java.lang.Override
  @JsonValue
  public String toString() {
    return this.string;
  }

  @java.lang.Override
  public boolean equals(Object other) {
    return (this == other) 
      || (other instanceof TrialEventJobFinishedStatus && this.string.equals(((TrialEventJobFinishedStatus) other).string));
  }

  @java.lang.Override
  public int hashCode() {
    return this.string.hashCode();
  }

  public <T> T visit(Visitor<T> visitor) {
    switch (value) {
      case FAILED:
        return visitor.visitFailed();
      case SUCCEEDED:
        return visitor.visitSucceeded();
      case PENDING:
        return visitor.visitPending();
      case CANCELLED:
        return visitor.visitCancelled();
      case RUNNING:
        return visitor.visitRunning();
      case UNKNOWN:
      default:
        return visitor.visitUnknown(string);
    }
  }

  @JsonCreator(
      mode = JsonCreator.Mode.DELEGATING
  )
  public static TrialEventJobFinishedStatus valueOf(String value) {
    switch (value) {
      case "failed":
        return FAILED;
      case "succeeded":
        return SUCCEEDED;
      case "pending":
        return PENDING;
      case "cancelled":
        return CANCELLED;
      case "running":
        return RUNNING;
      default:
        return new TrialEventJobFinishedStatus(Value.UNKNOWN, value);
    }
  }

  public enum Value {
    PENDING,

    RUNNING,

    SUCCEEDED,

    FAILED,

    CANCELLED,

    UNKNOWN
  }

  public interface Visitor<T> {
    T visitPending();

    T visitRunning();

    T visitSucceeded();

    T visitFailed();

    T visitCancelled();

    T visitUnknown(String unknownType);
  }
}
