/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.chronicle.labs.api.resources.search;

import com.chronicle.labs.api.core.ClientOptions;
import com.chronicle.labs.api.core.RequestOptions;
import com.chronicle.labs.api.resources.search.requests.SearchRequest;
import com.chronicle.labs.api.types.EventListResponse;

public class SearchClient {
  protected final ClientOptions clientOptions;

  private final RawSearchClient rawClient;

  public SearchClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
    this.rawClient = new RawSearchClient(clientOptions);
  }

  /**
   * Get responses with HTTP metadata like headers
   */
  public RawSearchClient withRawResponse() {
    return this.rawClient;
  }

  /**
   * Requires scope events:read or events:write. The page size is capped at 200 and a cursor can advance through at most 1,000 relevance-ranked results. Each request consumes 5 rate-limit units.
   */
  public EventListResponse events(SearchRequest request) {
    return this.rawClient.events(request).body();
  }

  /**
   * Requires scope events:read or events:write. The page size is capped at 200 and a cursor can advance through at most 1,000 relevance-ranked results. Each request consumes 5 rate-limit units.
   */
  public EventListResponse events(SearchRequest request, RequestOptions requestOptions) {
    return this.rawClient.events(request, requestOptions).body();
  }
}
