/**
 * This file was auto-generated by Fern from our API Definition.
 */
package com.chronicle.labs.api.errors;

import com.chronicle.labs.api.core.ChronicleLabsApiApiException;
import com.chronicle.labs.api.types.ErrorResponse;
import okhttp3.Response;

public final class ConflictError extends ChronicleLabsApiApiException {
    /**
     * The body of the response that triggered the exception.
     */
    private final ErrorResponse body;

    public ConflictError(ErrorResponse body) {
        super("ConflictError", 409, body);
        this.body = body;
    }

    public ConflictError(ErrorResponse body, Response rawResponse) {
        super("ConflictError", 409, body, rawResponse);
        this.body = body;
    }

    /**
     * @return the body
     */
    @java.lang.Override
    public ErrorResponse body() {
        return this.body;
    }
}
