/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.chronicle.labs.api.errors;

import com.chronicle.labs.api.core.ChronicleLabsApiApiException;
import com.chronicle.labs.api.types.ErrorResponse;
import okhttp3.Response;

public final class NotFoundError extends ChronicleLabsApiApiException {
  /**
   * The body of the response that triggered the exception.
   */
  private final ErrorResponse body;

  public NotFoundError(ErrorResponse body) {
    super("NotFoundError", 404, body);
    this.body = body;
  }

  public NotFoundError(ErrorResponse body, Response rawResponse) {
    super("NotFoundError", 404, body, rawResponse);
    this.body = body;
  }

  /**
   * @return the body
   */
  @java.lang.Override
  public ErrorResponse body() {
    return this.body;
  }
}
