/**
 * This file was auto-generated by Fern from our API Definition.
 */

package com.chronicle.labs.api.resources.events;

import com.chronicle.labs.api.core.ChronicleLabsApiApiException;
import com.chronicle.labs.api.core.ChronicleLabsApiException;
import com.chronicle.labs.api.core.ChronicleLabsApiHttpResponse;
import com.chronicle.labs.api.core.ClientOptions;
import com.chronicle.labs.api.core.MediaTypes;
import com.chronicle.labs.api.core.ObjectMappers;
import com.chronicle.labs.api.core.QueryStringMapper;
import com.chronicle.labs.api.core.RequestOptions;
import com.chronicle.labs.api.core.ResponseBodyReader;
import com.chronicle.labs.api.core.RetryInterceptor;
import com.chronicle.labs.api.core.Stream;
import com.chronicle.labs.api.errors.BadRequestError;
import com.chronicle.labs.api.errors.ConflictError;
import com.chronicle.labs.api.errors.ContentTooLargeError;
import com.chronicle.labs.api.errors.GatewayTimeoutError;
import com.chronicle.labs.api.errors.InternalServerError;
import com.chronicle.labs.api.errors.ServiceUnavailableError;
import com.chronicle.labs.api.errors.TooManyRequestsError;
import com.chronicle.labs.api.errors.UnauthorizedError;
import com.chronicle.labs.api.errors.UnprocessableEntityError;
import com.chronicle.labs.api.errors.UnsupportedMediaTypeError;
import com.chronicle.labs.api.resources.events.requests.QueryEventsRequest;
import com.chronicle.labs.api.resources.events.requests.StreamEventsRequest;
import com.chronicle.labs.api.types.ErrorResponse;
import com.chronicle.labs.api.types.EventListResponse;
import com.chronicle.labs.api.types.EventResult;
import com.chronicle.labs.api.types.IngestRequest;
import com.chronicle.labs.api.types.IngestResponse;
import com.fasterxml.jackson.core.JsonProcessingException;
import java.io.IOException;
import java.lang.Iterable;
import java.lang.Object;
import java.lang.String;
import java.util.List;
import java.util.concurrent.TimeUnit;
import okhttp3.Headers;
import okhttp3.HttpUrl;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.RequestBody;
import okhttp3.Response;
import okhttp3.ResponseBody;

public class RawEventsClient {
  protected final ClientOptions clientOptions;

  public RawEventsClient(ClientOptions clientOptions) {
    this.clientOptions = clientOptions;
  }

  /**
   * Requires scope events:read or events:write. Results are scoped to the tenant of the API key and ordered newest first by event time and event ID. Pass the opaque <code>next_cursor</code> as <code>cursor</code> to continue without an offset scan.
   */
  public ChronicleLabsApiHttpResponse<EventListResponse> queryEvents() {
    return queryEvents(QueryEventsRequest.builder().build());
  }

  /**
   * Requires scope events:read or events:write. Results are scoped to the tenant of the API key and ordered newest first by event time and event ID. Pass the opaque <code>next_cursor</code> as <code>cursor</code> to continue without an offset scan.
   */
  public ChronicleLabsApiHttpResponse<EventListResponse> queryEvents(
      RequestOptions requestOptions) {
    return queryEvents(QueryEventsRequest.builder().build(),requestOptions);
  }

  /**
   * Requires scope events:read or events:write. Results are scoped to the tenant of the API key and ordered newest first by event time and event ID. Pass the opaque <code>next_cursor</code> as <code>cursor</code> to continue without an offset scan.
   */
  public ChronicleLabsApiHttpResponse<EventListResponse> queryEvents(QueryEventsRequest request) {
    return queryEvents(request,null);
  }

  /**
   * Requires scope events:read or events:write. Results are scoped to the tenant of the API key and ordered newest first by event time and event ID. Pass the opaque <code>next_cursor</code> as <code>cursor</code> to continue without an offset scan.
   */
  public ChronicleLabsApiHttpResponse<EventListResponse> queryEvents(QueryEventsRequest request,
      RequestOptions requestOptions) {
    HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

      .addPathSegments("v1/events");if (request.getSource().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "source", request.getSource().get(), false);
      }
      if (request.getTopic().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "topic", request.getTopic().get(), false);
      }
      if (request.getEventType().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "event_type", request.getEventType().get(), false);
      }
      if (request.getEntityType().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "entity_type", request.getEntityType().get(), false);
      }
      if (request.getEntityId().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "entity_id", request.getEntityId().get(), false);
      }
      if (request.getLimit().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "limit", request.getLimit().get(), false);
      }
      if (request.getCursor().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "cursor", request.getCursor().get(), false);
      }
      if (request.getSince().isPresent()) {
        QueryStringMapper.addQueryParameter(httpUrl, "since", request.getSince().get(), false);
      }
      if (requestOptions != null) {
        requestOptions.getQueryParameters().forEach((_key, _value) -> {
          httpUrl.addQueryParameter(_key, _value);
        } );
      }
      Request.Builder _requestBuilder = new Request.Builder()
        .url(httpUrl.build())
        .method("GET", null)
        .headers(Headers.of(clientOptions.headers(requestOptions)))
        .addHeader("Accept", "application/json");
      Request okhttpRequest = _requestBuilder.build();
      OkHttpClient client = clientOptions.httpClient();
      if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
        client = clientOptions.httpClientWithTimeout(requestOptions);
      }
      if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
        okhttpRequest = okhttpRequest.newBuilder().tag(RetryInterceptor.MaxRetriesOverride.class, new RetryInterceptor.MaxRetriesOverride(requestOptions.getMaxRetries().get())).build();
      }
      try (Response response = client.newCall(okhttpRequest).execute()) {
        ResponseBody responseBody = response.body();
        String responseBodyString = responseBody != null ? responseBody.string() : "{}";
        if (response.isSuccessful()) {
          return new ChronicleLabsApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, EventListResponse.class), response);
        }
        try {
          switch (response.code()) {
            case 400:throw new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
            case 401:throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
            case 429:throw new TooManyRequestsError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
            case 500:throw new InternalServerError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
            case 503:throw new ServiceUnavailableError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
            case 504:throw new GatewayTimeoutError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
          }
        }
        catch (JsonProcessingException ignored) {
          // unable to map error response, throwing generic error
        }
        Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
        throw new ChronicleLabsApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
      }
      catch (JsonProcessingException e) {
        throw new ChronicleLabsApiException("Failed to deserialize response: " + e.getMessage(), e);
      }
      catch (IOException e) {
        throw new ChronicleLabsApiException("Network error executing HTTP request", e);
      }
    }

    /**
     * Requires scope events:write.
     */
    public ChronicleLabsApiHttpResponse<IngestResponse> ingestEvent(IngestRequest request) {
      return ingestEvent(request,null);
    }

    /**
     * Requires scope events:write.
     */
    public ChronicleLabsApiHttpResponse<IngestResponse> ingestEvent(IngestRequest request,
        RequestOptions requestOptions) {
      HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

        .addPathSegments("v1/events");if (requestOptions != null) {
          requestOptions.getQueryParameters().forEach((_key, _value) -> {
            httpUrl.addQueryParameter(_key, _value);
          } );
        }
        RequestBody body;
        try {
          body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
        }
        catch(JsonProcessingException e) {
          throw new ChronicleLabsApiException("Failed to serialize request", e);
        }
        Request okhttpRequest = new Request.Builder()
          .url(httpUrl.build())
          .method("POST", body)
          .headers(Headers.of(clientOptions.headers(requestOptions)))
          .addHeader("Content-Type", "application/json")
          .addHeader("Accept", "application/json")
          .build();
        OkHttpClient client = clientOptions.httpClient();
        if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
          client = clientOptions.httpClientWithTimeout(requestOptions);
        }
        if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
          okhttpRequest = okhttpRequest.newBuilder().tag(RetryInterceptor.MaxRetriesOverride.class, new RetryInterceptor.MaxRetriesOverride(requestOptions.getMaxRetries().get())).build();
        }
        try (Response response = client.newCall(okhttpRequest).execute()) {
          ResponseBody responseBody = response.body();
          String responseBodyString = responseBody != null ? responseBody.string() : "{}";
          if (response.isSuccessful()) {
            return new ChronicleLabsApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, IngestResponse.class), response);
          }
          try {
            switch (response.code()) {
              case 400:throw new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
              case 401:throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
              case 413:throw new ContentTooLargeError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
              case 415:throw new UnsupportedMediaTypeError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
              case 422:throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
              case 429:throw new TooManyRequestsError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
              case 500:throw new InternalServerError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
              case 503:throw new ServiceUnavailableError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
              case 504:throw new GatewayTimeoutError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
            }
          }
          catch (JsonProcessingException ignored) {
            // unable to map error response, throwing generic error
          }
          Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
          throw new ChronicleLabsApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
        }
        catch (JsonProcessingException e) {
          throw new ChronicleLabsApiException("Failed to deserialize response: " + e.getMessage(), e);
        }
        catch (IOException e) {
          throw new ChronicleLabsApiException("Network error executing HTTP request", e);
        }
      }

      /**
       * Requires scope events:write. Maximum 1000 events per batch; larger batches are rejected with 422. Request bodies over the size limit are rejected with 413. Each request consumes 10 rate-limit units.
       */
      public ChronicleLabsApiHttpResponse<IngestResponse> ingestEventBatch(
          List<IngestRequest> request) {
        return ingestEventBatch(request,null);
      }

      /**
       * Requires scope events:write. Maximum 1000 events per batch; larger batches are rejected with 422. Request bodies over the size limit are rejected with 413. Each request consumes 10 rate-limit units.
       */
      public ChronicleLabsApiHttpResponse<IngestResponse> ingestEventBatch(
          List<IngestRequest> request, RequestOptions requestOptions) {
        HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

          .addPathSegments("v1/events/batch");if (requestOptions != null) {
            requestOptions.getQueryParameters().forEach((_key, _value) -> {
              httpUrl.addQueryParameter(_key, _value);
            } );
          }
          RequestBody body;
          try {
            body = RequestBody.create(ObjectMappers.JSON_MAPPER.writeValueAsBytes(request), MediaTypes.APPLICATION_JSON);
          }
          catch(JsonProcessingException e) {
            throw new ChronicleLabsApiException("Failed to serialize request", e);
          }
          Request okhttpRequest = new Request.Builder()
            .url(httpUrl.build())
            .method("POST", body)
            .headers(Headers.of(clientOptions.headers(requestOptions)))
            .addHeader("Content-Type", "application/json")
            .addHeader("Accept", "application/json")
            .build();
          OkHttpClient client = clientOptions.httpClient();
          if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
            client = clientOptions.httpClientWithTimeout(requestOptions);
          }
          if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
            okhttpRequest = okhttpRequest.newBuilder().tag(RetryInterceptor.MaxRetriesOverride.class, new RetryInterceptor.MaxRetriesOverride(requestOptions.getMaxRetries().get())).build();
          }
          try (Response response = client.newCall(okhttpRequest).execute()) {
            ResponseBody responseBody = response.body();
            String responseBodyString = responseBody != null ? responseBody.string() : "{}";
            if (response.isSuccessful()) {
              return new ChronicleLabsApiHttpResponse<>(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, IngestResponse.class), response);
            }
            try {
              switch (response.code()) {
                case 400:throw new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                case 401:throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                case 413:throw new ContentTooLargeError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                case 415:throw new UnsupportedMediaTypeError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                case 422:throw new UnprocessableEntityError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                case 429:throw new TooManyRequestsError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                case 500:throw new InternalServerError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                case 503:throw new ServiceUnavailableError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                case 504:throw new GatewayTimeoutError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
              }
            }
            catch (JsonProcessingException ignored) {
              // unable to map error response, throwing generic error
            }
            Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
            throw new ChronicleLabsApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
          }
          catch (JsonProcessingException e) {
            throw new ChronicleLabsApiException("Failed to deserialize response: " + e.getMessage(), e);
          }
          catch (IOException e) {
            throw new ChronicleLabsApiException("Network error executing HTTP request", e);
          }
        }

        /**
         * Requires scope events:read or events:write. A Server-Sent Events stream of events matching the optional filters, held open indefinitely.
         * <p>Opening a stream consumes 5 rate-limit units.</p>
         * <p>Each message has <code>event: event</code> and a <code>data</code> field carrying one EventResult as JSON. A comment line arrives every 15 seconds so intermediaries do not close an idle connection.</p>
         * <p>Every message carries an opaque, stream-specific <code>id</code> backed by a monotonic per-tenant delivery sequence. It records ingestion order, independently of the source event's <code>event_time</code>. Record the last id you processed and do not parse or construct it.</p>
         * <p>When <code>Last-Event-ID</code> is present, the server first establishes the live subscription, replays matching stored events strictly after that position in ascending order, and then continues with live delivery. Events committed at the history-to-live boundary may be delivered more than once, so consumers should deduplicate by <code>event_id</code>. This provides at-least-once delivery across a reconnect without leaving a gap.</p>
         * <p>Replay is limited to 1000 matching events. An older position returns 409 before the stream opens. Slow consumers are disconnected when the bounded live buffer fills and should reconnect with their last processed id. Concurrent streams are limited per tenant and may return 429 with <code>Retry-After</code>.</p>
         */
        public ChronicleLabsApiHttpResponse<Iterable<EventResult>> streamEvents() {
          return streamEvents(StreamEventsRequest.builder().build());
        }

        /**
         * Requires scope events:read or events:write. A Server-Sent Events stream of events matching the optional filters, held open indefinitely.
         * <p>Opening a stream consumes 5 rate-limit units.</p>
         * <p>Each message has <code>event: event</code> and a <code>data</code> field carrying one EventResult as JSON. A comment line arrives every 15 seconds so intermediaries do not close an idle connection.</p>
         * <p>Every message carries an opaque, stream-specific <code>id</code> backed by a monotonic per-tenant delivery sequence. It records ingestion order, independently of the source event's <code>event_time</code>. Record the last id you processed and do not parse or construct it.</p>
         * <p>When <code>Last-Event-ID</code> is present, the server first establishes the live subscription, replays matching stored events strictly after that position in ascending order, and then continues with live delivery. Events committed at the history-to-live boundary may be delivered more than once, so consumers should deduplicate by <code>event_id</code>. This provides at-least-once delivery across a reconnect without leaving a gap.</p>
         * <p>Replay is limited to 1000 matching events. An older position returns 409 before the stream opens. Slow consumers are disconnected when the bounded live buffer fills and should reconnect with their last processed id. Concurrent streams are limited per tenant and may return 429 with <code>Retry-After</code>.</p>
         */
        public ChronicleLabsApiHttpResponse<Iterable<EventResult>> streamEvents(
            RequestOptions requestOptions) {
          return streamEvents(StreamEventsRequest.builder().build(),requestOptions);
        }

        /**
         * Requires scope events:read or events:write. A Server-Sent Events stream of events matching the optional filters, held open indefinitely.
         * <p>Opening a stream consumes 5 rate-limit units.</p>
         * <p>Each message has <code>event: event</code> and a <code>data</code> field carrying one EventResult as JSON. A comment line arrives every 15 seconds so intermediaries do not close an idle connection.</p>
         * <p>Every message carries an opaque, stream-specific <code>id</code> backed by a monotonic per-tenant delivery sequence. It records ingestion order, independently of the source event's <code>event_time</code>. Record the last id you processed and do not parse or construct it.</p>
         * <p>When <code>Last-Event-ID</code> is present, the server first establishes the live subscription, replays matching stored events strictly after that position in ascending order, and then continues with live delivery. Events committed at the history-to-live boundary may be delivered more than once, so consumers should deduplicate by <code>event_id</code>. This provides at-least-once delivery across a reconnect without leaving a gap.</p>
         * <p>Replay is limited to 1000 matching events. An older position returns 409 before the stream opens. Slow consumers are disconnected when the bounded live buffer fills and should reconnect with their last processed id. Concurrent streams are limited per tenant and may return 429 with <code>Retry-After</code>.</p>
         */
        public ChronicleLabsApiHttpResponse<Iterable<EventResult>> streamEvents(
            StreamEventsRequest request) {
          return streamEvents(request,null);
        }

        /**
         * Requires scope events:read or events:write. A Server-Sent Events stream of events matching the optional filters, held open indefinitely.
         * <p>Opening a stream consumes 5 rate-limit units.</p>
         * <p>Each message has <code>event: event</code> and a <code>data</code> field carrying one EventResult as JSON. A comment line arrives every 15 seconds so intermediaries do not close an idle connection.</p>
         * <p>Every message carries an opaque, stream-specific <code>id</code> backed by a monotonic per-tenant delivery sequence. It records ingestion order, independently of the source event's <code>event_time</code>. Record the last id you processed and do not parse or construct it.</p>
         * <p>When <code>Last-Event-ID</code> is present, the server first establishes the live subscription, replays matching stored events strictly after that position in ascending order, and then continues with live delivery. Events committed at the history-to-live boundary may be delivered more than once, so consumers should deduplicate by <code>event_id</code>. This provides at-least-once delivery across a reconnect without leaving a gap.</p>
         * <p>Replay is limited to 1000 matching events. An older position returns 409 before the stream opens. Slow consumers are disconnected when the bounded live buffer fills and should reconnect with their last processed id. Concurrent streams are limited per tenant and may return 429 with <code>Retry-After</code>.</p>
         */
        public ChronicleLabsApiHttpResponse<Iterable<EventResult>> streamEvents(
            StreamEventsRequest request, RequestOptions requestOptions) {
          HttpUrl.Builder httpUrl = HttpUrl.parse(this.clientOptions.environment().getUrl()).newBuilder()

            .addPathSegments("v1/events/stream");if (request.getSource().isPresent()) {
              QueryStringMapper.addQueryParameter(httpUrl, "source", request.getSource().get(), false);
            }
            if (request.getEventType().isPresent()) {
              QueryStringMapper.addQueryParameter(httpUrl, "event_type", request.getEventType().get(), false);
            }
            if (request.getEntityType().isPresent()) {
              QueryStringMapper.addQueryParameter(httpUrl, "entity_type", request.getEntityType().get(), false);
            }
            if (request.getEntityId().isPresent()) {
              QueryStringMapper.addQueryParameter(httpUrl, "entity_id", request.getEntityId().get(), false);
            }
            if (requestOptions != null) {
              requestOptions.getQueryParameters().forEach((_key, _value) -> {
                httpUrl.addQueryParameter(_key, _value);
              } );
            }
            Request.Builder _requestBuilder = new Request.Builder()
              .url(httpUrl.build())
              .method("GET", null)
              .headers(Headers.of(clientOptions.headers(requestOptions)));
            if (request.getLastEventId().isPresent()) {
              _requestBuilder.addHeader("Last-Event-ID", request.getLastEventId().get());
            }
            Request okhttpRequest = _requestBuilder.build();
            OkHttpClient client = clientOptions.httpClient();
            if (requestOptions != null && requestOptions.getTimeout().isPresent()) {
              client = clientOptions.httpClientWithTimeout(requestOptions);
            }
            if (requestOptions != null && requestOptions.getMaxRetries().isPresent()) {
              okhttpRequest = okhttpRequest.newBuilder().tag(RetryInterceptor.MaxRetriesOverride.class, new RetryInterceptor.MaxRetriesOverride(requestOptions.getMaxRetries().get())).build();
            }
            client = client.newBuilder().callTimeout(0, TimeUnit.SECONDS).build();
            try {
              Response response = client.newCall(okhttpRequest).execute();
              ResponseBody responseBody = response.body();
              if (response.isSuccessful()) {
                return new ChronicleLabsApiHttpResponse<>(Stream.fromSse(EventResult.class, new ResponseBodyReader(response)), response);
              }
              String responseBodyString = responseBody != null ? responseBody.string() : "{}";
              try {
                switch (response.code()) {
                  case 400:throw new BadRequestError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                  case 401:throw new UnauthorizedError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                  case 409:throw new ConflictError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                  case 429:throw new TooManyRequestsError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                  case 500:throw new InternalServerError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                  case 503:throw new ServiceUnavailableError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                  case 504:throw new GatewayTimeoutError(ObjectMappers.JSON_MAPPER.readValue(responseBodyString, ErrorResponse.class), response);
                }
              }
              catch (JsonProcessingException ignored) {
                // unable to map error response, throwing generic error
              }
              Object errorBody = ObjectMappers.parseErrorBody(responseBodyString);
              throw new ChronicleLabsApiApiException("Error with status code " + response.code(), response.code(), errorBody, response);
            }
            catch (JsonProcessingException e) {
              throw new ChronicleLabsApiException("Failed to deserialize response: " + e.getMessage(), e);
            }
            catch (IOException e) {
              throw new ChronicleLabsApiException("Network error executing HTTP request", e);
            }
          }
        }
